// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const AccountMergeTypeMap = {
  AD_RECHARGE: "FUND_TYPE_AD_RECHARGE",
  JD_PRIVILEGE: "FUND_TYPE_JD_PRIVILEGE",
  JD_WIRELESS_CASH: "FUND_TYPE_JD_WIRELESS_CASH",
  UNION_GIFT: "FUND_TYPE_UNION_GIFT",
  MP_CASH: "FUND_TYPE_MP_CASH",
  MP_BANK: "FUND_TYPE_MP_BANK",
  MP_GIFT: "FUND_TYPE_MP_GIFT",
  CONTRACT_GIFT_VIRTUAL: "FUND_TYPE_CONTRACT_GIFT_VIRTUAL",
  CONTRACT_ASSIGN_VIRTUAL: "FUND_TYPE_CONTRACT_ASSIGN_VIRTUAL",
  COMPENSATE_VIRTUAL: "FUND_TYPE_COMPENSATE_VIRTUAL",
  INTERNAL_QUOTA: "FUND_TYPE_INTERNAL_QUOTA",
  TEST_VIRTUAL: "FUND_TYPE_TEST_VIRTUAL",
  TCC_GIFT: "FUND_TYPE_TCC_GIFT",
  SPECIAL_GIFT: "FUND_TYPE_SPECIAL_GIFT",
  MP_GAME_DEVELOPER_WORKING_FUND: "FUND_TYPE_MP_GAME_DEVELOPER_WORKING_FUND",
  MP_GAME_DEVELOPER_GIFT: "FUND_TYPE_MP_GAME_DEVELOPER_GIFT",
  FLOW_SOURCE_AD_FUND: "FUND_TYPE_FLOW_SOURCE_AD_FUND",
  ANDROID_ORIENTED_GIFT: "FUND_TYPE_ANDROID_ORIENTED_GIFT",
  LOCATION_PROMOTION_REWARDS: "FUND_TYPE_LOCATION_PROMOTION_REWARDS",
  GIFT_RESTRICT: "FUND_TYPE_GIFT_RESTRICT",
  DEBT_FIXED: "FUND_TYPE_DEBT_FIXED",
  DEBT_TEMP: "FUND_TYPE_DEBT_TEMP",
  SHORT_PLAY_GIFT: "FUND_TYPE_SHORT_PLAY_GIFT",
  GAME_CHARGE_INDIRECT_REWARDS_GIFT: "FUND_TYPE_GAME_CHARGE_INDIRECT_REWARDS_GIFT",
  GAME_CHARGE_DIRECT_REWARDS_GIFT: "FUND_TYPE_GAME_CHARGE_DIRECT_REWARDS_GIFT",
  SHORT_PLAY_PUBLISHER_GIFT: "FUND_TYPE_SHORT_PLAY_PUBLISHER_GIFT",
  MP_GAME_SPECIAL_REWARDS_GIFT: "FUND_TYPE_MP_GAME_SPECIAL_REWARDS_GIFT",
  MINIGAME_CREDIT: "FUND_TYPE_MINIGAME_CREDIT",
  MP_GAME_PC_TARGET_GIFT: "FUND_TYPE_MP_GAME_PC_TARGET_GIFT",
  MP_NEW_GAME_SUBSIDY: "FUND_TYPE_MP_NEW_GAME_SUBSIDY",
  INTEGRATED_MARKETING: "FUND_TYPE_INTEGRATED_MARKETING",
  IAA_SHARED_INCOME_COST: "FUND_TYPE_IAA_SHARED_INCOME_COST",
  IAP_SHARED_INCOME_COST: "FUND_TYPE_IAP_SHARED_INCOME_COST",
  UTILITY_PUBLISHER_GIFT: "FUND_TYPE_UTILITY_PUBLISHER_GIFT",
  UNSUPPORTED: "FUND_TYPE_UNSUPPORTED",
} as const;

export type AccountMergeTypeMap = typeof AccountMergeTypeMap[keyof typeof AccountMergeTypeMap];

