// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const AdActionType = {
  CLICK: "CLICK",
  EXPOSURE: "EXPOSURE",
  ORDER: "ORDER",
  APP_FINISH_DOWNLOAD: "APP_FINISH_DOWNLOAD",
  APP_INSTALL: "APP_INSTALL",
  APP_ACTIVATE: "APP_ACTIVATE",
  REGISTRATION_APP: "REGISTRATION_APP",
  APP_ONE_DAY_RETENTION: "APP_ONE_DAY_RETENTION",
  ADD_TO_CART_APP: "ADD_TO_CART_APP",
  APP_PURCHASE: "APP_PURCHASE",
  APP_APPLY: "APP_APPLY",
  REGISTRATION_WEB: "REGISTRATION_WEB",
  ADD_TO_CART_WEB: "ADD_TO_CART_WEB",
  WEB_ONLINE_CONSULT: "WEB_ONLINE_CONSULT",
  WEB_MAKE_PHONE_CALL: "WEB_MAKE_PHONE_CALL",
  WEB_RESERVE_PHONE_NUMBER: "WEB_RESERVE_PHONE_NUMBER",
  WEB_RESERVATION: "WEB_RESERVATION",
  APPLY_WEB: "APPLY_WEB",
  WEB_DELIVER: "WEB_DELIVER",
  PURCHASE_WEB: "PURCHASE_WEB",
  WEB_VIEW_COMMODITY_PAGE: "WEB_VIEW_COMMODITY_PAGE",
} as const;

export type AdActionType = typeof AdActionType[keyof typeof AdActionType];

