// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const AdStatus = {
  NORMAL: "ADSTATUS_NORMAL",
  PENDING: "ADSTATUS_PENDING",
  DENIED: "ADSTATUS_DENIED",
  FROZEN: "ADSTATUS_FROZEN",
  PAY_PENDING: "ADSTATUS_PAY_PENDING",
  PAY_REFUND: "ADSTATUS_PAY_REFUND",
  MANUAL_END: "ADSTATUS_MANUAL_END",
  SUSPEND: "ADSTATUS_SUSPEND",
  WITHDRAW: "ADSTATUS_WITHDRAW",
  INVALID: "ADSTATUS_INVALID",
  TO_BE_STARTED: "ADSTATUS_TO_BE_STARTED",
  ENDED: "ADSTATUS_ENDED",
  PROCESS: "ADSTATUS_PROCESS",
  DRAFT: "ADSTATUS_DRAFT",
  PREPARE: "ADSTATUS_PREPARE",
  DELETED: "ADSTATUS_DELETED",
} as const;

export type AdStatus = typeof AdStatus[keyof typeof AdStatus];

