// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const CatalogType = {
  CATALOG_TYPE_STANDARD: "CATALOG_TYPE_STANDARD",
  CATALOG_TYPE_FENGYE: "CATALOG_TYPE_FENGYE",
  CATALOG_TYPE_LOCAL_STORE: "CATALOG_TYPE_LOCAL_STORE",
  CATALOG_TYPE_YOUZAN: "CATALOG_TYPE_YOUZAN",
  CATALOG_TYPE_WEIMENG: "CATALOG_TYPE_WEIMENG",
  CATALOG_TYPE_MADAO: "CATALOG_TYPE_MADAO",
  PRODUCT_CATALOG_TYPE_STANDARD: "PRODUCT_CATALOG_TYPE_STANDARD",
  PRODUCT_CATALOG_TYPE_FENGYE: "PRODUCT_CATALOG_TYPE_FENGYE",
  PRODUCT_CATALOG_TYPE_SMALLSHOP: "PRODUCT_CATALOG_TYPE_SMALLSHOP",
  PRODUCT_CATALOG_TYPE_YUEBAO: "PRODUCT_CATALOG_TYPE_YUEBAO",
  PRODUCT_CATALOG_TYPE_MAIBAO: "PRODUCT_CATALOG_TYPE_MAIBAO",
  PRODUCT_CATALOG_TYPE_YOUZAN: "PRODUCT_CATALOG_TYPE_YOUZAN",
  PRODUCT_CATALOG_TYPE_WEIMENG: "PRODUCT_CATALOG_TYPE_WEIMENG",
  PRODUCT_CATALOG_TYPE_MADAO: "PRODUCT_CATALOG_TYPE_MADAO",
  CATALOG_TYPE_UNKNOWN: "CATALOG_TYPE_UNKNOWN",
} as const;

export type CatalogType = typeof CatalogType[keyof typeof CatalogType];

