// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const HeadClickType = {
  DEFAULT: "HEAD_CLICK_TYPE_DEFAULT",
  CUSTOMIZED: "HEAD_CLICK_TYPE_CUSTOMIZED",
  CELEBRITY_ACCOUNT: "HEAD_CLICK_TYPE_CELEBRITY_ACCOUNT",
  VIRTUAL_ACCOUNT: "HEAD_CLICK_TYPE_VIRTUAL_ACCOUNT",
  LIVE_PROFILE: "HEAD_CLICK_TYPE_LIVE_PROFILE",
  LIVE_EVENT: "HEAD_CLICK_TYPE_LIVE_EVENT",
  BRAND_PROGRAM: "HEAD_CLICK_TYPE_BRAND_PROGRAM",
  CNY_PROFILE: "HEAD_CLICK_TYPE_CNY_PROFILE",
  SEARCH_BRAND_AREA: "HEAD_CLICK_TYPE_SEARCH_BRAND_AREA",
} as const;

export type HeadClickType = typeof HeadClickType[keyof typeof HeadClickType];

