// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const LeadCluesLeadsIneffectReason = {
  EMPTY: "LEADS_INEFFECT_REASON_EMPTY",
  IDENTITY_MISMATCHED: "LEADS_INEFFECT_REASON_IDENTITY_MISMATCHED",
  REGION_MISMATCHED: "LEADS_INEFFECT_REASON_REGION_MISMATCHED",
  DATA_DUPLICATION: "LEADS_INEFFECT_REASON_DATA_DUPLICATION",
  TEL_NOT_CONNECTED: "LEADS_INEFFECT_REASON_TEL_NOT_CONNECTED",
  NO_INTENTION: "LEADS_INEFFECT_REASON_NO_INTENTION",
  UNKNOWN: "LEADS_INEFFECT_REASON_UNKNOWN",
} as const;

export type LeadCluesLeadsIneffectReason = typeof LeadCluesLeadsIneffectReason[keyof typeof LeadCluesLeadsIneffectReason];

