// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const LeadsSubType = {
  FORM_SUBMIT__UNKNOWN: "FORM_SUBMIT__UNKNOWN",
  FORM_SUBMIT__FORM_SUBMIT: "FORM_SUBMIT__FORM_SUBMIT",
  FORM_SUBMIT__LEAVE_MESSAGE_CONSULT: "FORM_SUBMIT__LEAVE_MESSAGE_CONSULT",
  FORM_SUBMIT__LEAVE_INFORMATION_CONSULT: "FORM_SUBMIT__LEAVE_INFORMATION_CONSULT",
  FORM_SUBMIT__PHONE_CONSULT: "FORM_SUBMIT__PHONE_CONSULT",
  ONE_CLICK_AUTHORIZE__UNKNOWN: "ONE_CLICK_AUTHORIZE__UNKNOWN",
  ONE_CLICK_AUTHORIZE__FORM_SUBMIT: "ONE_CLICK_AUTHORIZE__FORM_SUBMIT",
  ONE_CLICK_AUTHORIZE__PHONE_CONSULT: "ONE_CLICK_AUTHORIZE__PHONE_CONSULT",
  ONE_CLICK_AUTHORIZE__CLICK_FORM: "ONE_CLICK_AUTHORIZE__CLICK_FORM",
  ONE_CLICK_AUTHORIZE__CLICK_CONSULT: "ONE_CLICK_AUTHORIZE__CLICK_CONSULT",
  ONE_CLICK_AUTHORIZE__CLICK_CALL: "ONE_CLICK_AUTHORIZE__CLICK_CALL",
  INTELLIGENT_TOOL__FIRST_TALK: "INTELLIGENT_TOOL__FIRST_TALK",
  INTELLIGENT_TOOL__LEAVE_INFORMATION: "INTELLIGENT_TOOL__LEAVE_INFORMATION",
} as const;

export type LeadsSubType = typeof LeadsSubType[keyof typeof LeadsSubType];

