// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const MarketingCarrierType = {
  UNKNOWN: "MARKETING_CARRIER_TYPE_UNKNOWN",
  APP_ANDROID: "MARKETING_CARRIER_TYPE_APP_ANDROID",
  APP_IOS: "MARKETING_CARRIER_TYPE_APP_IOS",
  WECHAT_OFFICIAL_ACCOUNT: "MARKETING_CARRIER_TYPE_WECHAT_OFFICIAL_ACCOUNT",
  JUMP_PAGE: "MARKETING_CARRIER_TYPE_JUMP_PAGE",
  WECHAT_MINI_GAME: "MARKETING_CARRIER_TYPE_WECHAT_MINI_GAME",
  WECHAT_CHANNELS_LIVE: "MARKETING_CARRIER_TYPE_WECHAT_CHANNELS_LIVE",
  WECHAT_CHANNELS: "MARKETING_CARRIER_TYPE_WECHAT_CHANNELS",
  WECHAT_CHANNELS_LIVE_RESERVATION: "MARKETING_CARRIER_TYPE_WECHAT_CHANNELS_LIVE_RESERVATION",
  MINI_PROGRAM_WECHAT: "MARKETING_CARRIER_TYPE_MINI_PROGRAM_WECHAT",
  APP_QUICK_APP: "MARKETING_CARRIER_TYPE_APP_QUICK_APP",
  JUMP_PAGE2: "MARKETING_CARRIER_TYPE_JUMP_PAGE2",
  MINI_PROGRAM_WECHAT2: "MARKETING_CARRIER_TYPE_MINI_PROGRAM_WECHAT2",
  PC_GAME: "MARKETING_CARRIER_TYPE_PC_GAME",
  QQ_MINI_GAME: "MARKETING_CARRIER_TYPE_QQ_MINI_GAME",
  APP_HARMONY: "MARKETING_CARRIER_TYPE_APP_HARMONY",
} as const;

export type MarketingCarrierType = typeof MarketingCarrierType[keyof typeof MarketingCarrierType];

