// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const MarketingSubGoal = {
  UNKNOWN: "MARKETING_SUB_GOAL_UNKNOWN",
  NEW_GAME_RESERVE: "MARKETING_SUB_GOAL_NEW_GAME_RESERVE",
  NEW_GAME_TEST: "MARKETING_SUB_GOAL_NEW_GAME_TEST",
  NEW_GAME_LAUNCH: "MARKETING_SUB_GOAL_NEW_GAME_LAUNCH",
  PLATEAU_PHASE_LAUNCH: "MARKETING_SUB_GOAL_PLATEAU_PHASE_LAUNCH",
  MINI_GAME_NEW_CUSTOMER_GROWTH: "MARKETING_SUB_GOAL_MINI_GAME_NEW_CUSTOMER_GROWTH",
  MINI_GAME_RETURN_CUSTOMER_ENGAGEMENT: "MARKETING_SUB_GOAL_MINI_GAME_RETURN_CUSTOMER_ENGAGEMENT",
  APP_ACQUISITION: "MARKETING_SUB_GOAL_APP_ACQUISITION",
  APP_ACTIVATION: "MARKETING_SUB_GOAL_APP_ACTIVATION",
  NOT_INSTALL_USER: "MARKETING_SUB_GOAL_NOT_INSTALL_USER",
  PRE_INSTALL_USER: "MARKETING_SUB_GOAL_PRE_INSTALL_USER",
  UNLOADED_USER: "MARKETING_SUB_GOAL_UNLOADED_USER",
  SHORT_INACTIVE_USER: "MARKETING_SUB_GOAL_SHORT_INACTIVE_USER",
  LONG_INACTIVE_USER: "MARKETING_SUB_GOAL_LONG_INACTIVE_USER",
  GAME_VERSION_UPGRADE: "MARKETING_SUB_GOAL_GAME_VERSION_UPGRADE",
  NEW_STORE_OPENING: "MARKETING_SUB_GOAL_NEW_STORE_OPENING",
  EVENING_PROMOTION: "MARKETING_SUB_GOAL_EVENING_PROMOTION",
  SPECIAL_RELEASE: "MARKETING_SUB_GOAL_SPECIAL_RELEASE",
} as const;

export type MarketingSubGoal = typeof MarketingSubGoal[keyof typeof MarketingSubGoal];

