// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const MarketingScene = {
  DEFAULT: "DEFAULT",
  GAME_RESERVATION: "GAME_RESERVATION",
  GAME_PROMOTION: "GAME_PROMOTION",
  APP_ACTIVE_PROMOTION: "APP_ACTIVE_PROMOTION",
  GAME_CLOSED_BETA_TEST: "GAME_CLOSED_BETA_TEST",
  ECOMMERCE_GOODS_DIRECT_PURCHASE_DAILY: "ECOMMERCE_GOODS_DIRECT_PURCHASE_DAILY",
  ECOMMERCE_GOODS_LIVE_PURCHASE_DAILY: "ECOMMERCE_GOODS_LIVE_PURCHASE_DAILY",
  ECOMMERCE_CONSUMER_COLLECT_CLUES_DAILY: "ECOMMERCE_CONSUMER_COLLECT_CLUES_DAILY",
  ECOMMERCE_CONSUMER_ADD_FOLLOWERS_DAILY: "ECOMMERCE_CONSUMER_ADD_FOLLOWERS_DAILY",
  ECOMMERCE_CONSUMER_OFFICIAL_ACCOUNTS_DAILY: "ECOMMERCE_CONSUMER_OFFICIAL_ACCOUNTS_DAILY",
  ECOMMERCE_CONSUMER_CHANNELS_DAILY: "ECOMMERCE_CONSUMER_CHANNELS_DAILY",
  ECOMMERCE_CONSUMER_ANDROID_NEW_DAILY: "ECOMMERCE_CONSUMER_ANDROID_NEW_DAILY",
  ECOMMERCE_CONSUMER_IOS_NEW_DAILY: "ECOMMERCE_CONSUMER_IOS_NEW_DAILY",
  ECOMMERCE_CONTENT_BRAND_DAILY: "ECOMMERCE_CONTENT_BRAND_DAILY",
  ECOMMERCE_CONSUMER_LIVE_FOLLOW_DAILY: "ECOMMERCE_CONSUMER_LIVE_FOLLOW_DAILY",
} as const;

export type MarketingScene = typeof MarketingScene[keyof typeof MarketingScene];

