// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const TourPlaceDomestic = {
  SANYA: "TOUR_PLACE_DOMESTIC_SANYA",
  CHANGSHA: "TOUR_PLACE_DOMESTIC_CHANGSHA",
  XIAMEN: "TOUR_PLACE_DOMESTIC_XIAMEN",
  QINGDAO: "TOUR_PLACE_DOMESTIC_QINGDAO",
  LIJIANG: "TOUR_PLACE_DOMESTIC_LIJIANG",
  DALI: "TOUR_PLACE_DOMESTIC_DALI",
  DALIAN: "TOUR_PLACE_DOMESTIC_DALIAN",
  HK: "TOUR_PLACE_DOMESTIC_HK",
  TAIWAN: "TOUR_PLACE_DOMESTIC_TAIWAN",
  AOMEN: "TOUR_PLACE_DOMESTIC_AOMEN",
  XIANGGELILA: "TOUR_PLACE_DOMESTIC_XIANGGELILA",
  QINGHAI: "TOUR_PLACE_DOMESTIC_QINGHAI",
  XIZANG: "TOUR_PLACE_DOMESTIC_XIZANG",
  DAOCHENG: "TOUR_PLACE_DOMESTIC_DAOCHENG",
  CHONGQING: "TOUR_PLACE_DOMESTIC_CHONGQING",
  SUZHOU: "TOUR_PLACE_DOMESTIC_SUZHOU",
  SHANGHAI: "TOUR_PLACE_DOMESTIC_SHANGHAI",
  HANGZHOU: "TOUR_PLACE_DOMESTIC_HANGZHOU",
  SHENZHEN: "TOUR_PLACE_DOMESTIC_SHENZHEN",
  GUANGZHOU: "TOUR_PLACE_DOMESTIC_GUANGZHOU",
  BEIJING: "TOUR_PLACE_DOMESTIC_BEIJING",
  XIAN: "TOUR_PLACE_DOMESTIC_XIAN",
  CHENGDU: "TOUR_PLACE_DOMESTIC_CHENGDU",
  BEIHAI: "TOUR_PLACE_DOMESTIC_BEIHAI",
  GUILIN: "TOUR_PLACE_DOMESTIC_GUILIN",
  WUHAN: "TOUR_PLACE_DOMESTIC_WUHAN",
  NANJING: "TOUR_PLACE_DOMESTIC_NANJING",
  HAIKOU: "TOUR_PLACE_DOMESTIC_HAIKOU",
} as const;

export type TourPlaceDomestic = typeof TourPlaceDomestic[keyof typeof TourPlaceDomestic];

