// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const TourPlaceForeign = {
  VN: "TOUR_PLACE_FOREIGN_VN",
  AU: "TOUR_PLACE_FOREIGN_AU",
  PALAO: "TOUR_PLACE_FOREIGN_PALAO",
  BALI: "TOUR_PLACE_FOREIGN_BALI",
  FJ: "TOUR_PLACE_FOREIGN_FJ",
  PUJI: "TOUR_PLACE_FOREIGN_PUJI",
  MV: "TOUR_PLACE_FOREIGN_MV",
  JP: "TOUR_PLACE_FOREIGN_JP",
  TR: "TOUR_PLACE_FOREIGN_TR",
  GR: "TOUR_PLACE_FOREIGN_GR",
  FR: "TOUR_PLACE_FOREIGN_FR",
  IT: "TOUR_PLACE_FOREIGN_IT",
  BULAGE: "TOUR_PLACE_FOREIGN_BULAGE",
  XIANBENNA: "TOUR_PLACE_FOREIGN_XIANBENNA",
  MU: "TOUR_PLACE_FOREIGN_MU",
  GE: "TOUR_PLACE_FOREIGN_GE",
  SUMEI: "TOUR_PLACE_FOREIGN_SUMEI",
  SAIBAN: "TOUR_PLACE_FOREIGN_SAIBAN",
  JIZHOU: "TOUR_PLACE_FOREIGN_JIZHOU",
  SHABA: "TOUR_PLACE_FOREIGN_SHABA",
  DE: "TOUR_PLACE_FOREIGN_DE",
  LONDON: "TOUR_PLACE_FOREIGN_LONDON",
  SYDNEY: "TOUR_PLACE_FOREIGN_SYDNEY",
  NZ: "TOUR_PLACE_FOREIGN_NZ",
  JILONGPO: "TOUR_PLACE_FOREIGN_JILONGPO",
} as const;

export type TourPlaceForeign = typeof TourPlaceForeign[keyof typeof TourPlaceForeign];

