// Generated from tencentad/marketing-api-go-sdk
// Do not edit manually.

export const WechatPositionType = {
  WECHAT_OFFICIAL_ACCOUNT_BOTTOM: "POSITION_TYPE_WECHAT_OFFICIAL_ACCOUNT_BOTTOM",
  WECHAT_OFFICIAL_ACCOUNT_TOP: "POSITION_TYPE_WECHAT_OFFICIAL_ACCOUNT_TOP",
  WECHAT_TENCENT_NEWS: "POSITION_TYPE_WECHAT_TENCENT_NEWS",
  WECHAT_OFFICIAL_ACCOUNT_VIDEO: "POSITION_TYPE_WECHAT_OFFICIAL_ACCOUNT_VIDEO",
  WECHAT_OFFICIAL_ACCOUNT_MUTUAL_ELECTION: "POSITION_TYPE_WECHAT_OFFICIAL_ACCOUNT_MUTUAL_ELECTION",
  WECHAT_OFFICIAL_ACCOUNT_MIDDLE: "POSITION_TYPE_WECHAT_OFFICIAL_ACCOUNT_MIDDLE",
  TENCENT_MAILBOX: "POSITION_TYPE_TENCENT_MAILBOX",
  WECHAT_MINI_PROGRAM_BANNER: "POSITION_TYPE_WECHAT_MINI_PROGRAM_BANNER",
  WECHAT_REWARD: "POSITION_TYPE_WECHAT_REWARD",
  WECHAT_OFFICIAL_ACCOUNT_MIDDLE_PRODUCT: "POSITION_TYPE_WECHAT_OFFICIAL_ACCOUNT_MIDDLE_PRODUCT",
  WECHAT_MINI_PROGRAM_INTERSTITIAL: "POSITION_TYPE_WECHAT_MINI_PROGRAM_INTERSTITIAL",
  WECHAT_AD_BOX: "POSITION_TYPE_WECHAT_AD_BOX",
  WECHAT_MOMENTS: "POSITION_TYPE_WECHAT_MOMENTS",
  WECHAT_NULL: "POSITION_TYPE_WECHAT_NULL",
  WECHAT_OTHERS: "POSITION_TYPE_WECHAT_OTHERS",
} as const;

export type WechatPositionType = typeof WechatPositionType[keyof typeof WechatPositionType];

