// Generated from github.com/bububa/kwai-marketing-api/model/unit/unit.go
// Do not edit manually.

import type { KuaishouId } from "../types";
import type { Target } from "../target_v2/target";
import type { AdvCard } from "./adv_card";
import type { BackflowForecast } from "./backflow_forecast";
import type { DiverseData } from "./diverse_data";
import type { GiftData } from "./gift_data";
import type { AdMarketNegativeWordParam } from "./negative_word";
import type { PageGroupDetail } from "./page_group_detail";
import type { Schedule } from "./schedule";

export interface Unit {
  campaign_id?: KuaishouId;
  unit_id?: KuaishouId;
  unit_name?: string;
  status?: number;
  put_status?: number;
  create_channel?: number;
  review_detail?: string;
  study_status?: number;
  compensate_status?: number;
  bid_type?: number;
  bid?: KuaishouId;
  cpa_bid?: KuaishouId;
  smart_bid?: number;
  ocpx_action_type?: number;
  deep_conversion_type?: number;
  deep_conversion_bid?: KuaishouId;
  day_budget?: number;
  day_budget_schedule?: number[];
  roi_ratio?: number;
  speed?: number;
  begin_time?: string;
  end_time?: string;
  schedule?: Schedule;
  schedule_time?: string;
  scene_id?: number[];
  show_mode?: number;
  unit_type?: number;
  convert_id?: number;
  use_app_market?: number;
  app_store?: string[];
  url_type?: number;
  web_uri_type?: number;
  url?: string;
  schema_uri?: string;
  app_id?: KuaishouId;
  app_icon_url?: string;
  diverse_data?: DiverseData;
  target?: Target;
  site_type?: number;
  gift_data?: GiftData;
  video_landing_page?: boolean;
  auto_target?: boolean;
  smart_cover?: boolean;
  asset_mining?: boolean;
  auto_create_photo?: boolean;
  update_time?: string;
  item_id?: KuaishouId;
  fiction_id?: KuaishouId;
  merchant_item_put_type?: number;
  consult_id?: number;
  adv_card_option?: number;
  adv_card_list?: AdvCard[];
  backflow_forecast?: BackflowForecast;
  merchandise_id?: KuaishouId;
  merchandise_type?: number;
  playable_orientation?: number;
  playable_url?: string;
  playable_file_name?: string;
  playable_switch?: number;
  playable_id?: KuaishouId;
  play_button?: string;
  library_id?: KuaishouId;
  outer_id?: string;
  product_id?: KuaishouId;
  product_name?: string;
  product_price?: number;
  product_image?: string;
  intention_target?: boolean;
  splash_ad_switch?: boolean;
  page_group_detail?: PageGroupDetail;
  jingle_bell_id?: KuaishouId;
  live_user_id?: KuaishouId;
  ad_type?: number;
  extend_search?: boolean;
  unit_source?: number;
  negative_word?: AdMarketNegativeWordParam;
  quick_search?: number;
  target_explore?: number;
  schema_id?: string;
  create_time?: string;
  template_id?: number;
  component_id?: number;
  use_ska?: boolean;
}
