// Generated from tencentad/marketing-api-go-sdk pkg/model/v3/model_material_task_status.go
// Do not edit manually.

export const MaterialTaskStatus = {
  UNKNOWN: "MATERIAL_TASK_STATUS_UNKNOWN",
  WATERMARK_PROCESSING: "MATERIAL_TASK_STATUS_WATERMARK_PROCESSING",
  WATERMARK_SUCCESS: "MATERIAL_TASK_STATUS_WATERMARK_SUCCESS",
  WATERMARK_FAILED: "MATERIAL_TASK_STATUS_WATERMARK_FAILED",
  WATERMARK_EXCEPTION: "MATERIAL_TASK_STATUS_WATERMARK_EXCEPTION",
  WATERMARK_DELETED: "MATERIAL_TASK_STATUS_WATERMARK_DELETED",
  PREREVIEW_PROCESSING: "MATERIAL_TASK_STATUS_PREREVIEW_PROCESSING",
  PREREVIEW_HAS_REPAIR_DETAIL: "MATERIAL_TASK_STATUS_PREREVIEW_HAS_REPAIR_DETAIL",
  PREREVIEW_NO_REPAIR_DETAIL: "MATERIAL_TASK_STATUS_PREREVIEW_NO_REPAIR_DETAIL",
  PREREVIEW_EXCEPTION: "MATERIAL_TASK_STATUS_PREREVIEW_EXCEPTION",
} as const;

export type MaterialTaskStatus = typeof MaterialTaskStatus[keyof typeof MaterialTaskStatus];

