// Generated from tencentad/marketing-api-go-sdk pkg/model/v3/model_simple_canvas_webview_type.go
// Do not edit manually.

export const SimpleCanvasWebviewType = {
  UNKNOWN: "SIMPLE_CANVAS_WEBVIEW_TYPE_UNKNOWN",
  XJ_ANDROID_APP_H5: "SIMPLE_CANVAS_WEBVIEW_TYPE_XJ_ANDROID_APP_H5",
  XJ_IOS_APP_H5: "SIMPLE_CANVAS_WEBVIEW_TYPE_XJ_IOS_APP_H5",
  XJ_WEBSITE_H5: "SIMPLE_CANVAS_WEBVIEW_TYPE_XJ_WEBSITE_H5",
  WECHAT_OFFICIAL_ACCOUNT_DETAIL: "SIMPLE_CANVAS_WEBVIEW_TYPE_WECHAT_OFFICIAL_ACCOUNT_DETAIL",
  FENGYE_ECOMMERCE: "SIMPLE_CANVAS_WEBVIEW_TYPE_FENGYE_ECOMMERCE",
  WECHAT_OFFICIAL_ACCOUNT_ARTICLE: "SIMPLE_CANVAS_WEBVIEW_TYPE_WECHAT_OFFICIAL_ACCOUNT_ARTICLE",
} as const;

export type SimpleCanvasWebviewType = typeof SimpleCanvasWebviewType[keyof typeof SimpleCanvasWebviewType];

