// Generated from tencentad/marketing-api-go-sdk pkg/model/v3/model_derive_method_type.go
// Do not edit manually.

export const DeriveMethodType = {
  UNKNOWN: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_UNKNOWN",
  TEMPLATE: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_TEMPLATE",
  OUTPAINTING: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_OUTPAINTING",
  MINI_IMAGE: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_MINI_IMAGE",
  MIX_CUT: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_MIX_CUT",
  NOVEL_DRAMA_IMAGE: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_NOVEL_DRAMA_IMAGE",
  DRAMA_MIX_CUT: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_DRAMA_MIX_CUT",
  DRAMA_TRANSFORM: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_DRAMA_TRANSFORM",
  CONTEXT: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_CONTEXT",
  HOME_IMAGE: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_HOME_IMAGE",
  SMARTGAME_IMG_BG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_SMARTGAME_IMG_BG",
  SMARTGAME_NINE_IMG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_SMARTGAME_NINE_IMG",
  MINIDRAMA_NINE_IMG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_MINIDRAMA_NINE_IMG",
  PRODUCT_IMAGE: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_PRODUCT_IMAGE",
  SMARTGAME_VIDEO: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_SMARTGAME_VIDEO",
  EDU_NINE_IMG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_EDU_NINE_IMG",
  HEALTH_NINE_IMG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_HEALTH_NINE_IMG",
  LOCAL_NINE_IMG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_LOCAL_NINE_IMG",
  FINANCE_NINE_IMG: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_FINANCE_NINE_IMG",
  VIDEO_GENERATION: "AUTO_DERIVED_CREATIVE_METHOD_TYPE_VIDEO_GENERATION",
} as const;

export type DeriveMethodType = typeof DeriveMethodType[keyof typeof DeriveMethodType];

