// Generated from tencentad/marketing-api-go-sdk pkg/model/v3/model_report_daily_level.go
// Do not edit manually.

export const ReportDailyLevel = {
  ADVERTISER: "REPORT_LEVEL_ADVERTISER",
  ADGROUP: "REPORT_LEVEL_ADGROUP",
  DYNAMIC_CREATIVE: "REPORT_LEVEL_DYNAMIC_CREATIVE",
  COMPONENT: "REPORT_LEVEL_COMPONENT",
  CHANNEL: "REPORT_LEVEL_CHANNEL",
  BIDWORD: "REPORT_LEVEL_BIDWORD",
  QUERYWORD: "REPORT_LEVEL_QUERYWORD",
  MATERIAL_IMAGE: "REPORT_LEVEL_MATERIAL_IMAGE",
  MATERIAL_VIDEO: "REPORT_LEVEL_MATERIAL_VIDEO",
  ADVERTISER_TOTAL: "REPORT_LEVEL_ADVERTISER_TOTAL",
  MARKETING_ASSET: "REPORT_LEVEL_MARKETING_ASSET",
  PRODUCT_CATALOG: "REPORT_LEVEL_PRODUCT_CATALOG",
  PROJECT: "REPORT_LEVEL_PROJECT",
  PROJECT_CREATIVE: "REPORT_LEVEL_PROJECT_CREATIVE",
  VIDEO_HIGHLIGHT: "REPORT_LEVEL_VIDEO_HIGHLIGHT",
  CREATIVE_ASSET: "REPORT_LEVEL_CREATIVE_ASSET",
  PRODUCT_CREATIVE_TEMPLATE: "REPORT_LEVEL_PRODUCT_CREATIVE_TEMPLATE",
  WECHAT_SHOP_PRODUCT: "REPORT_LEVEL_WECHAT_SHOP_PRODUCT",
  PLAYLET: "REPORT_LEVEL_PLAYLET",
} as const;

export type ReportDailyLevel = typeof ReportDailyLevel[keyof typeof ReportDailyLevel];

