// Generated from tencentad/marketing-api-go-sdk pkg/model/v3/model_canvas_type.go
// Do not edit manually.

export const CanvasType = {
  BUILDING: "CANVAS_TYPE_BUILDING",
  RSTRNT: "CANVAS_TYPE_RSTRNT",
  BASIC: "CANVAS_TYPE_BASIC",
  APP: "CANVAS_TYPE_APP",
  FOLLOW: "CANVAS_TYPE_FOLLOW",
  VIDEO: "CANVAS_TYPE_VIDEO",
  IMAGE: "CANVAS_TYPE_IMAGE",
  SIMPLE: "CANVAS_TYPE_SIMPLE",
  EGG: "CANVAS_TYPE_EGG",
  SDPA: "CANVAS_TYPE_SDPA",
  REWARD: "CANVAS_TYPE_REWARD",
  LOCALCOUPON: "CANVAS_TYPE_LOCALCOUPON",
  PORTRAIT_VIDEO: "CANVAS_TYPE_PORTRAIT_VIDEO",
  PORTRAIT_VIDEO_2: "CANVAS_TYPE_PORTRAIT_VIDEO_2",
  COMMON_PAGE: "CANVAS_TYPE_COMMON_PAGE",
  EGGS_RANDOM: "CANVAS_TYPE_EGGS_RANDOM",
  EGGS_SINGLE: "CANVAS_TYPE_EGGS_SINGLE",
  EGGS_MOVIE: "CANVAS_TYPE_EGGS_MOVIE",
  VERTICAL_VIDEO_NEW_916: "CANVAS_TYPE_VERTICAL_VIDEO_NEW_916",
  EGGS_RANDOM_SHAKE: "CANVAS_TYPE_EGGS_RANDOM_SHAKE",
  VIDEO_1280_720: "CANVAS_TYPE_VIDEO_1280_720",
  VIDEO_1280_960: "CANVAS_TYPE_VIDEO_1280_960",
  PC_EGG_PLOT: "CANVAS_TYPE_PC_EGG_PLOT",
  EGGS_RANDOM_HALF: "CANVAS_TYPE_EGGS_RANDOM_HALF",
} as const;

export type CanvasType = typeof CanvasType[keyof typeof CanvasType];

