// Generated from tencentad/marketing-api-go-sdk pkg/model/v3/model_conversion_target_type.go
// Do not edit manually.

export const ConversionTargetType = {
  DEFAULT: "CONVERSION_TARGET_DEFAULT",
  GET: "CONVERSION_TARGET_GET",
  RESERVE: "CONVERSION_TARGET_RESERVE",
  BOOK: "CONVERSION_TARGET_BOOK",
  BUY: "CONVERSION_TARGET_BUY",
  APPLY: "CONVERSION_TARGET_APPLY",
  CONSULT: "CONVERSION_TARGET_CONSULT",
  DOWNLOAD: "CONVERSION_TARGET_DOWNLOAD",
  PLAYING: "CONVERSION_TARGET_PLAYING",
  CLICK: "CONVERSION_TARGET_CLICK",
  SEE: "CONVERSION_TARGET_SEE",
  INVOLVE: "CONVERSION_TARGET_INVOLVE",
  OPEN: "CONVERSION_TARGET_OPEN",
  PURCHASE: "CONVERSION_TARGET_PURCHASE",
  BROWSE: "CONVERSION_TARGET_BROWSE",
  TRY: "CONVERSION_TARGET_TRY",
  DRIVE: "CONVERSION_TARGET_DRIVE",
  ENTER: "CONVERSION_TARGET_ENTER",
  READ: "CONVERSION_TARGET_READ",
  FOLLOW: "CONVERSION_TARGET_FOLLOW",
  USE: "CONVERSION_TARGET_USE",
  EXPERIENCE: "CONVERSION_TARGET_EXPERIENCE",
  SETUP: "CONVERSION_TARGET_SETUP",
  SECKILL: "CONVERSION_TARGET_SECKILL",
  ADD_WECOM: "CONVERSION_TARGET_ADD_WECOM",
  LIKE: "CONVERSION_TARGET_LIKE",
  DONATION: "CONVERSION_TARGET_DONATION",
  GOOD_DEED: "CONVERSION_TARGET_GOOD_DEED",
  MEITUAN_RANK: "CONVERSION_TARGET_MEITUAN_RANK",
} as const;

export type ConversionTargetType = typeof ConversionTargetType[keyof typeof ConversionTargetType];

