// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const AdGetV2DataStatus = {
  AD_STATUS_BUDGET_EXCEED: "AD_STATUS_BUDGET_EXCEED",
  AD_STATUS_DSP_AD_DISABLE: "AD_STATUS_DSP_AD_DISABLE",
  AD_STATUS_DELIVERY_OK: "AD_STATUS_DELIVERY_OK",
  AD_STATUS_PRODUCT_OFFLINE: "AD_STATUS_PRODUCT_OFFLINE",
  AD_STATUS_DONE: "AD_STATUS_DONE",
  AD_STATUS_CAMPAIGN_EXCEED: "AD_STATUS_CAMPAIGN_EXCEED",
  AD_STATUS_CAMPAIGN_PRE_OFFLINE_BUDGET: "AD_STATUS_CAMPAIGN_PRE_OFFLINE_BUDGET",
  AD_STATUS_REAUDIT: "AD_STATUS_REAUDIT",
  AD_STATUS_FROZEN: "AD_STATUS_FROZEN",
  AD_STATUS_AUDIT_DENY: "AD_STATUS_AUDIT_DENY",
  AD_STATUS_DELETE: "AD_STATUS_DELETE",
  AD_STATUS_ADVERTISER_PRE_OFFLINE_BUDGET: "AD_STATUS_ADVERTISER_PRE_OFFLINE_BUDGET",
  AD_STATUS_EXTERNAL_URL_DISABLE: "AD_STATUS_EXTERNAL_URL_DISABLE",
  AD_STATUS_SOME_DELIVERY_OK: "AD_STATUS_SOME_DELIVERY_OK",
  AD_STATUS_NOT_START: "AD_STATUS_NOT_START",
  AD_STATUS_CREATE: "AD_STATUS_CREATE",
  AD_STATUS_DISABLE: "AD_STATUS_DISABLE",
  AD_STATUS_CANNOT_EDIT: "AD_STATUS_CANNOT_EDIT",
  AD_STATUS_AWEME_ACCOUNT_DISABLED: "AD_STATUS_AWEME_ACCOUNT_DISABLED",
  AD_STATUS_DRAFT: "AD_STATUS_DRAFT",
  AD_STATUS_DISABLE_BY_QUOTA: "AD_STATUS_DISABLE_BY_QUOTA",
  AD_STATUS_AUDIT: "AD_STATUS_AUDIT",
  AD_STATUS_ADVERTISER_BUDGET_EXCEED: "AD_STATUS_ADVERTISER_BUDGET_EXCEED",
  AD_STATUS_NO_SCHEDULE: "AD_STATUS_NO_SCHEDULE",
  AD_STATUS_PRE_ONLINE: "AD_STATUS_PRE_ONLINE",
  AD_STATUS_PRE_OFFLINE_BUDGET: "AD_STATUS_PRE_OFFLINE_BUDGET",
  AD_STATUS_BALANCE_EXCEED: "AD_STATUS_BALANCE_EXCEED",
  AD_STATUS_AWEME_ACCOUNT_PUNISHED: "AD_STATUS_AWEME_ACCOUNT_PUNISHED",
  AD_STATUS_LIVE_ROOM_OFF: "AD_STATUS_LIVE_ROOM_OFF",
  AD_STATUS_CAMPAIGN_DISABLE: "AD_STATUS_CAMPAIGN_DISABLE",
  AD_STATUS_DATA_ERROR: "AD_STATUS_DATA_ERROR",
  AD_STATUS_LIVE_CANNOT_LAUNCH: "AD_STATUS_LIVE_CANNOT_LAUNCH",
  AD_STATUS_AUDIT_STATUS_ERROR: "AD_STATUS_AUDIT_STATUS_ERROR",
} as const;

export type AdGetV2DataStatus = typeof AdGetV2DataStatus[keyof typeof AdGetV2DataStatus];

