// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const AdGetV2DataStatus = {
  BUDGET_EXCEED: "AD_STATUS_BUDGET_EXCEED",
  DSP_AD_DISABLE: "AD_STATUS_DSP_AD_DISABLE",
  DELIVERY_OK: "AD_STATUS_DELIVERY_OK",
  PRODUCT_OFFLINE: "AD_STATUS_PRODUCT_OFFLINE",
  DONE: "AD_STATUS_DONE",
  CAMPAIGN_EXCEED: "AD_STATUS_CAMPAIGN_EXCEED",
  CAMPAIGN_PRE_OFFLINE_BUDGET: "AD_STATUS_CAMPAIGN_PRE_OFFLINE_BUDGET",
  REAUDIT: "AD_STATUS_REAUDIT",
  FROZEN: "AD_STATUS_FROZEN",
  AUDIT_DENY: "AD_STATUS_AUDIT_DENY",
  DELETE: "AD_STATUS_DELETE",
  ADVERTISER_PRE_OFFLINE_BUDGET: "AD_STATUS_ADVERTISER_PRE_OFFLINE_BUDGET",
  EXTERNAL_URL_DISABLE: "AD_STATUS_EXTERNAL_URL_DISABLE",
  SOME_DELIVERY_OK: "AD_STATUS_SOME_DELIVERY_OK",
  NOT_START: "AD_STATUS_NOT_START",
  CREATE: "AD_STATUS_CREATE",
  DISABLE: "AD_STATUS_DISABLE",
  CANNOT_EDIT: "AD_STATUS_CANNOT_EDIT",
  AWEME_ACCOUNT_DISABLED: "AD_STATUS_AWEME_ACCOUNT_DISABLED",
  DRAFT: "AD_STATUS_DRAFT",
  DISABLE_BY_QUOTA: "AD_STATUS_DISABLE_BY_QUOTA",
  AUDIT: "AD_STATUS_AUDIT",
  ADVERTISER_BUDGET_EXCEED: "AD_STATUS_ADVERTISER_BUDGET_EXCEED",
  NO_SCHEDULE: "AD_STATUS_NO_SCHEDULE",
  PRE_ONLINE: "AD_STATUS_PRE_ONLINE",
  PRE_OFFLINE_BUDGET: "AD_STATUS_PRE_OFFLINE_BUDGET",
  BALANCE_EXCEED: "AD_STATUS_BALANCE_EXCEED",
  AWEME_ACCOUNT_PUNISHED: "AD_STATUS_AWEME_ACCOUNT_PUNISHED",
  LIVE_ROOM_OFF: "AD_STATUS_LIVE_ROOM_OFF",
  CAMPAIGN_DISABLE: "AD_STATUS_CAMPAIGN_DISABLE",
  DATA_ERROR: "AD_STATUS_DATA_ERROR",
  LIVE_CANNOT_LAUNCH: "AD_STATUS_LIVE_CANNOT_LAUNCH",
  AUDIT_STATUS_ERROR: "AD_STATUS_AUDIT_STATUS_ERROR",
} as const;

export type AdGetV2DataStatus = typeof AdGetV2DataStatus[keyof typeof AdGetV2DataStatus];

