// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const AdGetV2FilteringStatus = {
  NOT_START: "AD_STATUS_NOT_START",
  BUDGET_EXCEED: "AD_STATUS_BUDGET_EXCEED",
  NO_SCHEDULE: "AD_STATUS_NO_SCHEDULE",
  REAUDIT: "AD_STATUS_REAUDIT",
  DELETE: "AD_STATUS_DELETE",
  CREATE: "AD_STATUS_CREATE",
  BALANCE_EXCEED: "AD_STATUS_BALANCE_EXCEED",
  DISABLE: "AD_STATUS_DISABLE",
  DELIVERY_OK: "AD_STATUS_DELIVERY_OK",
  ALL: "AD_STATUS_ALL",
  AUDIT_DENY: "AD_STATUS_AUDIT_DENY",
  DONE: "AD_STATUS_DONE",
  AUDIT: "AD_STATUS_AUDIT",
  CAMPAIGN_DISABLE: "AD_STATUS_CAMPAIGN_DISABLE",
  NOT_DELETE: "AD_STATUS_NOT_DELETE",
  CAMPAIGN_EXCEED: "AD_STATUS_CAMPAIGN_EXCEED",
} as const;

export type AdGetV2FilteringStatus = typeof AdGetV2FilteringStatus[keyof typeof AdGetV2FilteringStatus];

