// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const AdvertiserDeliveryQualificationListV30DataListQualificationType = {
  AGENT_ARRANGEMENT: "AGENT_ARRANGEMENT",
  AUTHORIZATION_CONTRACT: "AUTHORIZATION_CONTRACT",
  DISTRIBUTION_AUTHORIZATION: "DISTRIBUTION_AUTHORIZATION",
  FOOD_BUSINESS_LICENSE: "FOOD_BUSINESS_LICENSE",
  ICP_RECORD_AUTHORIZATION: "ICP_RECORD_AUTHORIZATION",
  OTHER_CERTIFICATION: "OTHER_CERTIFICATION",
  PATENT_CERTIFICATE: "PATENT_CERTIFICATE",
  PORTRAIT_AUTHORIZATION: "PORTRAIT_AUTHORIZATION",
  QUALITY_REPORT: "QUALITY_REPORT",
  SOFTWARE_COPYRIGHT_REGISTRATION_CERTIFICATE: "SOFTWARE_COPYRIGHT_REGISTRATION_CERTIFICATE",
  TRADEMARK_REGISTRATION_CERTIFICATE: "TRADEMARK_REGISTRATION_CERTIFICATE",
  VIDEO_MATERIAL_PRODUCTION_IP_AUTHORIZATION: "VIDEO_MATERIAL_PRODUCTION_IP_AUTHORIZATION",
} as const;

export type AdvertiserDeliveryQualificationListV30DataListQualificationType = typeof AdvertiserDeliveryQualificationListV30DataListQualificationType[keyof typeof AdvertiserDeliveryQualificationListV30DataListQualificationType];

