// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const AdvertiserQualificationSubmitV30SubjectQualificationType = {
  ASSOCIATION_REGISTER_CODE: "ASSOCIATION_REGISTER_CODE",
  COMMERCIAL_REGISTER_NUMBER: "COMMERCIAL_REGISTER_NUMBER",
  COMPANY_CREDIT_CODE: "COMPANY_CREDIT_CODE",
  COMPANY_REGISTER_CODE: "COMPANY_REGISTER_CODE",
  CREDIT_CODE: "CREDIT_CODE",
  HK_MACAO_TAIWAN_ID: "HK_MACAO_TAIWAN_ID",
  HK_REGISTER_CODE: "HK_REGISTER_CODE",
  ID: "ID",
  INDIVIDUAL_CREDIT_CODE: "INDIVIDUAL_CREDIT_CODE",
  INDIVIDUAL_REGISTER_CODE: "INDIVIDUAL_REGISTER_CODE",
  LAWYER_CERTIFICATE_NUMBER: "LAWYER_CERTIFICATE_NUMBER",
  LAWYER_PERMIT_CODE: "LAWYER_PERMIT_CODE",
  LEGAL_PERSON_CREDIT_CODE: "LEGAL_PERSON_CREDIT_CODE",
  ORGANIZATION_REGISTER_CODE: "ORGANIZATION_REGISTER_CODE",
  OTHER: "OTHER",
  OVERSEA_REGISTER_CODE: "OVERSEA_REGISTER_CODE",
  PASSPORT_ID: "PASSPORT_ID",
  SCHOOL_PERMIT_CODE: "SCHOOL_PERMIT_CODE",
  SOCIAL_REGISTER_CODE: "SOCIAL_REGISTER_CODE",
} as const;

export type AdvertiserQualificationSubmitV30SubjectQualificationType = typeof AdvertiserQualificationSubmitV30SubjectQualificationType[keyof typeof AdvertiserQualificationSubmitV30SubjectQualificationType];

