// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const AdvertiserInfoV2DataStatus = {
  LIMIT: "STATUS_LIMIT",
  PENDING_CONFIRM: "STATUS_PENDING_CONFIRM",
  PENDING_VERIFIED: "STATUS_PENDING_VERIFIED",
  CONFIRM_FAIL_END: "STATUS_CONFIRM_FAIL_END",
  CONFIRM_FAIL: "STATUS_CONFIRM_FAIL",
  SELF_SERVICE_UNAUDITED: "STATUS_SELF_SERVICE_UNAUDITED",
  ENABLE: "STATUS_ENABLE",
  DISABLE: "STATUS_DISABLE",
  PENDING_CONFIRM_MODIFY: "STATUS_PENDING_CONFIRM_MODIFY",
  WAIT_FOR_PUBLIC_AUTH: "STATUS_WAIT_FOR_PUBLIC_AUTH",
  WAIT_FOR_BPM_AUDIT: "STATUS_WAIT_FOR_BPM_AUDIT",
  CONFIRM_MODIFY_FAIL: "STATUS_CONFIRM_MODIFY_FAIL",
} as const;

export type AdvertiserInfoV2DataStatus = typeof AdvertiserInfoV2DataStatus[keyof typeof AdvertiserInfoV2DataStatus];

