// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { BrandCreativeGetV30DataCreativesCreativeAdvancedCreativeInfoAdvancedCreativeType, BrandCreativeGetV30ResponseDataCreativesInnerCreativeAdvancedCreativeInfoCard, BrandCreativeGetV30ResponseDataCreativesInnerCreativeAdvancedCreativeInfoLiveCard } from "../models";

export interface BrandCreativeGetV30ResponseDataCreativesInnerCreativeAdvancedCreativeInfo {
  advanced_creative_type?: BrandCreativeGetV30DataCreativesCreativeAdvancedCreativeInfoAdvancedCreativeType;
  card?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeAdvancedCreativeInfoCard;
  live_card?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeAdvancedCreativeInfoLiveCard;
}

