// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

import type { BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTimeWipeAfterImage, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTimeWipeBeforeImage, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTimeWipeImage } from "../models";

export interface BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTime {
  advanced_duration?: number;
  wipe_after_image?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTimeWipeAfterImage;
  wipe_before_image?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTimeWipeBeforeImage;
  wipe_image?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTimeWipeImage;
  wipe_text?: string;
}

