// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImageImageInfoBkListInner, BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImageImageInfoListInner } from "../models";

export interface BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImage {
  image_info_bk_list?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImageImageInfoBkListInner[];
  image_info_list?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImageImageInfoListInner[];
}

