// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const BrandMaterialListV30DataMaterialsCreativeTemplate = {
  DOUYINCONTENTPLANTGRASSADNORMAL: "DouyinContentPlantGrassAdNormal",
  DOUYINCONTENTPLANTGRASSADSEARCHEXPLORE: "DouyinContentPlantGrassAdSearchExplore",
  DOUYINCONTENTPLANTGRASSADSEARCHIMAGE: "DouyinContentPlantGrassAdSearchImage",
  DOUYINCONTENTPLANTGRASSADSEARCHDIMAGE: "DouyinContentPlantGrassAdSearchdImage",
  DOUYINCONTENTPLANTGRASSNORMAL: "DouyinContentPlantGrassNormal",
  DOUYINCONTENTPLANTGRASSSEARCH: "DouyinContentPlantGrassSearch",
  DOUYINFEEDAPPDOWNLOADINTERACTIVESPACE: "DouyinFeedAppDownloadInteractiveSpace",
  DOUYINFEEDAPPDOWNLOADNORMAL: "DouyinFeedAppDownloadNormal",
  DOUYINFEEDEXTERNALCARD: "DouyinFeedExternalCard",
  DOUYINFEEDEXTERNALCOUPON: "DouyinFeedExternalCoupon",
  DOUYINFEEDEXTERNALINTERACTIVESPACE: "DouyinFeedExternalInteractiveSpace",
  DOUYINFEEDEXTERNALNORMAL: "DouyinFeedExternalNormal",
  DOUYINFEEDNATIVEAPPINTERACTIVESPACE: "DouyinFeedNativeAppInteractiveSpace",
  DOUYINFEEDNATIVEAPPNORMAL: "DouyinFeedNativeAppNormal",
  DOUYINFEEDNATIVECARD: "DouyinFeedNativeCard",
  DOUYINFEEDNATIVECOUPON: "DouyinFeedNativeCoupon",
  DOUYINFEEDNATIVEINTERACTIVESPACE: "DouyinFeedNativeInteractiveSpace",
  DOUYINFEEDNATIVENORMAL: "DouyinFeedNativeNormal",
  DOUYINFEEDSLIVEADNORMAL: "DouyinFeedsLiveAdNormal",
  DOUYINFEEDSLIVESERVICENORMAL: "DouyinFeedsLiveServiceNormal",
  DOUYINSPLASHNORMAL: "DouyinSplashNormal",
  DOUYINSPLASHSEMICCIRCLEBUTTON: "DouyinSplashSemicCircleButton",
  DOUYINSPLASHSHOW: "DouyinSplashShow",
  DOUYINSPLASHSIDESLIDE: "DouyinSplashSideSlide",
  DOUYINSPLASHSTATICTWIST: "DouyinSplashStaticTwist",
  DOUYINSPLASHUPSIDE: "DouyinSplashUpSide",
  DOUYINSPLASHUPSIDECARD: "DouyinSplashUpSideCard",
  DOUYINSPLASHVIDEOTWIST: "DouyinSplashVideoTwist",
  DOUYINVIDEOLIVEADCARD: "DouyinVideoLiveAdCard",
  DOUYINVIDEOLIVEADNORMAL: "DouyinVideoLiveAdNormal",
  TOUTIAOFEEDAPPDOWNLOADNORMAL: "ToutiaoFeedAppDownloadNormal",
  TOUTIAOFEEDAPPDOWNLOADVIDEONORMAL: "ToutiaoFeedAppDownloadVideoNormal",
  TOUTIAOFEEDARTICLENORMAL: "ToutiaoFeedArticleNormal",
  TOUTIAOFEEDARTICLEVIDEONORMAL: "ToutiaoFeedArticleVideoNormal",
  TOUTIAOFEEDLIVENORMAL: "ToutiaoFeedLiveNormal",
  TOUTIAOFEEDWEBHORIZONTALVIDEO: "ToutiaoFeedWebHorizontalVideo",
  TOUTIAOFEEDWEBNORMAL: "ToutiaoFeedWebNormal",
  TOUTIAOPROMOTIONCARD: "ToutiaoPromotionCard",
  TOUTIAOPROMOTIONNORMAL: "ToutiaoPromotionNormal",
  TOUTIAOSPLASHARTICLENORMAL: "ToutiaoSplashArticleNormal",
  TOUTIAOSPLASHARTICLESIDESLIDE: "ToutiaoSplashArticleSideSlide",
  TOUTIAOSPLASHARTICLESTATICTWIST: "ToutiaoSplashArticleStaticTwist",
  TOUTIAOSPLASHARTICLEUPSIDE: "ToutiaoSplashArticleUpSide",
  TOUTIAOSPLASHARTICLEUPSIDECARD: "ToutiaoSplashArticleUpSideCard",
  TOUTIAOSPLASHARTICLEVIDEOTWIST: "ToutiaoSplashArticleVideoTwist",
  TOUTIAOSPLASHEXTERNALNORMAL: "ToutiaoSplashExternalNormal",
  TOUTIAOSPLASHEXTERNALSIDESLIDE: "ToutiaoSplashExternalSideSlide",
  TOUTIAOSPLASHEXTERNALSTATICTWIST: "ToutiaoSplashExternalStaticTwist",
  TOUTIAOSPLASHEXTERNALUPSIDE: "ToutiaoSplashExternalUpSide",
  TOUTIAOSPLASHEXTERNALUPSIDECARD: "ToutiaoSplashExternalUpSideCard",
  TOUTIAOSPLASHEXTERNALVIDEOTWIST: "ToutiaoSplashExternalVideoTwist",
  TOUTIAOSPLASHSHOW: "ToutiaoSplashShow",
  XIGUAFEEDAPPDOWNLOADHORIZONTALVIDEONORMAL: "XiguaFeedAppDownloadHorizontalVideoNormal",
  XIGUAFEEDAPPDOWNLOADNORMAL: "XiguaFeedAppDownloadNormal",
  XIGUAFEEDEXTERNALHORIZONTALVIDEONORMAL: "XiguaFeedExternalHorizontalVideoNormal",
  XIGUAFEEDEXTERNALNORMAL: "XiguaFeedExternalNormal",
  XIGUASPLASHARTICLENORMAL: "XiguaSplashArticleNormal",
  XIGUASPLASHARTICLESIDESLIDE: "XiguaSplashArticleSideSlide",
  XIGUASPLASHARTICLESTATICTWIST: "XiguaSplashArticleStaticTwist",
  XIGUASPLASHARTICLEUPSIDE: "XiguaSplashArticleUpSide",
  XIGUASPLASHARTICLEUPSIDECARD: "XiguaSplashArticleUpSideCard",
  XIGUASPLASHARTICLEVIDEOTWIST: "XiguaSplashArticleVideoTwist",
  XIGUASPLASHEXTERNALNORMAL: "XiguaSplashExternalNormal",
  XIGUASPLASHEXTERNALSIDESLIDE: "XiguaSplashExternalSideSlide",
  XIGUASPLASHEXTERNALSTATICTWIST: "XiguaSplashExternalStaticTwist",
  XIGUASPLASHEXTERNALUPSIDE: "XiguaSplashExternalUpSide",
  XIGUASPLASHEXTERNALUPSIDECARD: "XiguaSplashExternalUpSideCard",
  XIGUASPLASHEXTERNALVIDEOTWIST: "XiguaSplashExternalVideoTwist",
  XIGUASPLASHSHOW: "XiguaSplashShow",
} as const;

export type BrandMaterialListV30DataMaterialsCreativeTemplate = typeof BrandMaterialListV30DataMaterialsCreativeTemplate[keyof typeof BrandMaterialListV30DataMaterialsCreativeTemplate];

