// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const BrandMaterialListV30DataMaterialsCreativeTemplate = {
  DOUYIN_CONTENT_PLANT_GRASS_AD_NORMAL: "DouyinContentPlantGrassAdNormal",
  DOUYIN_CONTENT_PLANT_GRASS_AD_SEARCH_EXPLORE: "DouyinContentPlantGrassAdSearchExplore",
  DOUYIN_CONTENT_PLANT_GRASS_AD_SEARCH_IMAGE: "DouyinContentPlantGrassAdSearchImage",
  DOUYIN_CONTENT_PLANT_GRASS_AD_SEARCHD_IMAGE: "DouyinContentPlantGrassAdSearchdImage",
  DOUYIN_CONTENT_PLANT_GRASS_NORMAL: "DouyinContentPlantGrassNormal",
  DOUYIN_CONTENT_PLANT_GRASS_SEARCH: "DouyinContentPlantGrassSearch",
  DOUYIN_FEED_APP_DOWNLOAD_INTERACTIVE_SPACE: "DouyinFeedAppDownloadInteractiveSpace",
  DOUYIN_FEED_APP_DOWNLOAD_NORMAL: "DouyinFeedAppDownloadNormal",
  DOUYIN_FEED_EXTERNAL_CARD: "DouyinFeedExternalCard",
  DOUYIN_FEED_EXTERNAL_COUPON: "DouyinFeedExternalCoupon",
  DOUYIN_FEED_EXTERNAL_INTERACTIVE_SPACE: "DouyinFeedExternalInteractiveSpace",
  DOUYIN_FEED_EXTERNAL_NORMAL: "DouyinFeedExternalNormal",
  DOUYIN_FEED_NATIVE_APP_INTERACTIVE_SPACE: "DouyinFeedNativeAppInteractiveSpace",
  DOUYIN_FEED_NATIVE_APP_NORMAL: "DouyinFeedNativeAppNormal",
  DOUYIN_FEED_NATIVE_CARD: "DouyinFeedNativeCard",
  DOUYIN_FEED_NATIVE_COUPON: "DouyinFeedNativeCoupon",
  DOUYIN_FEED_NATIVE_INTERACTIVE_SPACE: "DouyinFeedNativeInteractiveSpace",
  DOUYIN_FEED_NATIVE_NORMAL: "DouyinFeedNativeNormal",
  DOUYIN_FEEDS_LIVE_AD_NORMAL: "DouyinFeedsLiveAdNormal",
  DOUYIN_FEEDS_LIVE_SERVICE_NORMAL: "DouyinFeedsLiveServiceNormal",
  DOUYIN_SPLASH_NORMAL: "DouyinSplashNormal",
  DOUYIN_SPLASH_SEMIC_CIRCLE_BUTTON: "DouyinSplashSemicCircleButton",
  DOUYIN_SPLASH_SHOW: "DouyinSplashShow",
  DOUYIN_SPLASH_SIDE_SLIDE: "DouyinSplashSideSlide",
  DOUYIN_SPLASH_STATIC_TWIST: "DouyinSplashStaticTwist",
  DOUYIN_SPLASH_UP_SIDE: "DouyinSplashUpSide",
  DOUYIN_SPLASH_UP_SIDE_CARD: "DouyinSplashUpSideCard",
  DOUYIN_SPLASH_VIDEO_TWIST: "DouyinSplashVideoTwist",
  DOUYIN_VIDEO_LIVE_AD_CARD: "DouyinVideoLiveAdCard",
  DOUYIN_VIDEO_LIVE_AD_NORMAL: "DouyinVideoLiveAdNormal",
  TOUTIAO_FEED_APP_DOWNLOAD_NORMAL: "ToutiaoFeedAppDownloadNormal",
  TOUTIAO_FEED_APP_DOWNLOAD_VIDEO_NORMAL: "ToutiaoFeedAppDownloadVideoNormal",
  TOUTIAO_FEED_ARTICLE_NORMAL: "ToutiaoFeedArticleNormal",
  TOUTIAO_FEED_ARTICLE_VIDEO_NORMAL: "ToutiaoFeedArticleVideoNormal",
  TOUTIAO_FEED_LIVE_NORMAL: "ToutiaoFeedLiveNormal",
  TOUTIAO_FEED_WEB_HORIZONTAL_VIDEO: "ToutiaoFeedWebHorizontalVideo",
  TOUTIAO_FEED_WEB_NORMAL: "ToutiaoFeedWebNormal",
  TOUTIAO_PROMOTION_CARD: "ToutiaoPromotionCard",
  TOUTIAO_PROMOTION_NORMAL: "ToutiaoPromotionNormal",
  TOUTIAO_SPLASH_ARTICLE_NORMAL: "ToutiaoSplashArticleNormal",
  TOUTIAO_SPLASH_ARTICLE_SIDE_SLIDE: "ToutiaoSplashArticleSideSlide",
  TOUTIAO_SPLASH_ARTICLE_STATIC_TWIST: "ToutiaoSplashArticleStaticTwist",
  TOUTIAO_SPLASH_ARTICLE_UP_SIDE: "ToutiaoSplashArticleUpSide",
  TOUTIAO_SPLASH_ARTICLE_UP_SIDE_CARD: "ToutiaoSplashArticleUpSideCard",
  TOUTIAO_SPLASH_ARTICLE_VIDEO_TWIST: "ToutiaoSplashArticleVideoTwist",
  TOUTIAO_SPLASH_EXTERNAL_NORMAL: "ToutiaoSplashExternalNormal",
  TOUTIAO_SPLASH_EXTERNAL_SIDE_SLIDE: "ToutiaoSplashExternalSideSlide",
  TOUTIAO_SPLASH_EXTERNAL_STATIC_TWIST: "ToutiaoSplashExternalStaticTwist",
  TOUTIAO_SPLASH_EXTERNAL_UP_SIDE: "ToutiaoSplashExternalUpSide",
  TOUTIAO_SPLASH_EXTERNAL_UP_SIDE_CARD: "ToutiaoSplashExternalUpSideCard",
  TOUTIAO_SPLASH_EXTERNAL_VIDEO_TWIST: "ToutiaoSplashExternalVideoTwist",
  TOUTIAO_SPLASH_SHOW: "ToutiaoSplashShow",
  XIGUA_FEED_APP_DOWNLOAD_HORIZONTAL_VIDEO_NORMAL: "XiguaFeedAppDownloadHorizontalVideoNormal",
  XIGUA_FEED_APP_DOWNLOAD_NORMAL: "XiguaFeedAppDownloadNormal",
  XIGUA_FEED_EXTERNAL_HORIZONTAL_VIDEO_NORMAL: "XiguaFeedExternalHorizontalVideoNormal",
  XIGUA_FEED_EXTERNAL_NORMAL: "XiguaFeedExternalNormal",
  XIGUA_SPLASH_ARTICLE_NORMAL: "XiguaSplashArticleNormal",
  XIGUA_SPLASH_ARTICLE_SIDE_SLIDE: "XiguaSplashArticleSideSlide",
  XIGUA_SPLASH_ARTICLE_STATIC_TWIST: "XiguaSplashArticleStaticTwist",
  XIGUA_SPLASH_ARTICLE_UP_SIDE: "XiguaSplashArticleUpSide",
  XIGUA_SPLASH_ARTICLE_UP_SIDE_CARD: "XiguaSplashArticleUpSideCard",
  XIGUA_SPLASH_ARTICLE_VIDEO_TWIST: "XiguaSplashArticleVideoTwist",
  XIGUA_SPLASH_EXTERNAL_NORMAL: "XiguaSplashExternalNormal",
  XIGUA_SPLASH_EXTERNAL_SIDE_SLIDE: "XiguaSplashExternalSideSlide",
  XIGUA_SPLASH_EXTERNAL_STATIC_TWIST: "XiguaSplashExternalStaticTwist",
  XIGUA_SPLASH_EXTERNAL_UP_SIDE: "XiguaSplashExternalUpSide",
  XIGUA_SPLASH_EXTERNAL_UP_SIDE_CARD: "XiguaSplashExternalUpSideCard",
  XIGUA_SPLASH_EXTERNAL_VIDEO_TWIST: "XiguaSplashExternalVideoTwist",
  XIGUA_SPLASH_SHOW: "XiguaSplashShow",
} as const;

export type BrandMaterialListV30DataMaterialsCreativeTemplate = typeof BrandMaterialListV30DataMaterialsCreativeTemplate[keyof typeof BrandMaterialListV30DataMaterialsCreativeTemplate];

