// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

import type { BrandMaterialCreateV30MaterialListMaterialComponentCommonExternalMicroAppOpenUrlType, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternalMicroAppInfo, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternalWechatMicroAppInfo } from "../models";

export interface BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternal {
  external_url?: string;
  external_url_is_download?: number;
  micro_app_info?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternalMicroAppInfo;
  micro_app_open_url_type?: BrandMaterialCreateV30MaterialListMaterialComponentCommonExternalMicroAppOpenUrlType;
  open_url?: string;
  wechat_micro_app_info?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternalWechatMicroAppInfo;
}

