// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAvatarIcon, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAwemeAnchor, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAwemeShopHomePage, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAwemeVideo, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentBusinessUrl, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternal, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentDeliveryTimeList, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentExploreOneTime, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentExternalTitle, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentFeedButtonText, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentIesCoreUser, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentImageCard, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentLbsExternal, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentMallActivityPage, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentMusicText, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentProductDetailPage, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentSearch, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentVideoComment, BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentVideoDownload } from "../models";

export interface BrandMaterialCreateV30RequestMaterialListInnerMaterialComponent {
  avatar_icon?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAvatarIcon;
  aweme_anchor?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAwemeAnchor;
  aweme_shop_home_page?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAwemeShopHomePage;
  aweme_video?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentAwemeVideo;
  business_url?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentBusinessUrl;
  common_external?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentCommonExternal;
  delivery_time_list?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentDeliveryTimeList;
  explore_one_time?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentExploreOneTime;
  external_title?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentExternalTitle;
  feed_button_text?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentFeedButtonText;
  ies_core_user?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentIesCoreUser;
  image_card?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentImageCard;
  lbs_external?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentLbsExternal;
  mall_activity_page?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentMallActivityPage;
  music_text?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentMusicText;
  product_detail_page?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentProductDetailPage;
  search?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentSearch;
  video_comment?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentVideoComment;
  video_download?: BrandMaterialCreateV30RequestMaterialListInnerMaterialComponentVideoDownload;
}

