// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const BrandOrderListV30FilterAdForm = {
  AWEME_LBS: "AWEME_LBS",
  CONTENTRECOMMEND: "CONTENTRECOMMEND",
  CONTENTRECOMMEND_NO_GRASS: "CONTENTRECOMMEND_NO_GRASS",
  CONTENTSERVICE: "CONTENTSERVICE",
  CONTENTSERVICE_NO_GRASS: "CONTENTSERVICE_NO_GRASS",
  FEED: "FEED",
  FEEDSLIVE: "FEEDSLIVE",
  FEEDSLIVE_AD: "FEEDSLIVE_AD",
  FEEDSLIVE_SERVICE: "FEEDSLIVE_SERVICE",
  LITE_FEED: "LITE_FEED",
  NEW_PLANT_GRASS: "NEW_PLANT_GRASS",
  SEARCH: "SEARCH",
  SPLASH: "SPLASH",
  VIDEOLIVE_AD: "VIDEOLIVE_AD",
  VIDEOLIVE_SERVICE: "VIDEOLIVE_SERVICE",
} as const;

export type BrandOrderListV30FilterAdForm = typeof BrandOrderListV30FilterAdForm[keyof typeof BrandOrderListV30FilterAdForm];

