// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

import type { BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAdvancedCardImage, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAdvancedCardMainTitle, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAdvancedCardSubTitle, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAppDownload, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAvatarIcon, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAwemeShopHomePage, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAwemeVideo, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentBusinessUrl, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentCommonExternal, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentCoupon, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDeliveryTimeList, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicFullScreen, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicNoneFullScreen, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentExternalTitle, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentFeedButtonText, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentIesCoreUser, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentImageCard, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentLbsExternal, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentMallActivityPage, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentMusicText, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentProductDetailPage, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSearch, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSemicCircleButton, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSideSlide, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSplashButtonColor, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSplashButtonText, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticFullScreen, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticNoneFullScreen, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEgg, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentUpSlide, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoComment, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoDownload, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoFullScreen, BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoTwistEgg } from "../models";

export interface BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponent {
  advanced_card_image?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAdvancedCardImage;
  advanced_card_main_title?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAdvancedCardMainTitle;
  advanced_card_sub_title?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAdvancedCardSubTitle;
  app_download?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAppDownload;
  avatar_icon?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAvatarIcon;
  aweme_shop_home_page?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAwemeShopHomePage;
  aweme_video?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentAwemeVideo;
  business_url?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentBusinessUrl;
  common_external?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentCommonExternal;
  coupon?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentCoupon;
  delivery_time_list?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDeliveryTimeList;
  dynamic_full_screen?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicFullScreen;
  dynamic_none_full_screen?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentDynamicNoneFullScreen;
  external_title?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentExternalTitle;
  feed_button_text?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentFeedButtonText;
  ies_core_user?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentIesCoreUser;
  image_card?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentImageCard;
  lbs_external?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentLbsExternal;
  mall_activity_page?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentMallActivityPage;
  music_text?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentMusicText;
  product_detail_page?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentProductDetailPage;
  search?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSearch;
  semic_circle_button?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSemicCircleButton;
  side_slide?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSideSlide;
  splash_button_color?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSplashButtonColor;
  splash_button_text?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentSplashButtonText;
  static_full_screen?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticFullScreen;
  static_none_full_screen?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticNoneFullScreen;
  static_twist_egg?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticTwistEgg;
  up_slide?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentUpSlide;
  video_comment?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoComment;
  video_download?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoDownload;
  video_full_screen?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoFullScreen;
  video_twist_egg?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentVideoTwistEgg;
}

