// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const CgTransferQueryCanTransferBalanceV30DataCanTransferDetailListCapitalDetailListCapitalSubDetailsCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferQueryCanTransferBalanceV30DataCanTransferDetailListCapitalDetailListCapitalSubDetailsCapitalSubType = typeof CgTransferQueryCanTransferBalanceV30DataCanTransferDetailListCapitalDetailListCapitalSubDetailsCapitalSubType[keyof typeof CgTransferQueryCanTransferBalanceV30DataCanTransferDetailListCapitalDetailListCapitalSubDetailsCapitalSubType];

