// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = typeof CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType[keyof typeof CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType];

