// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListRemitterCapitalDetailListCapitalSubDetailsCapitalSubType } from "../models";

export interface CgTransferWalletTransferCanTransferBalanceV30ResponseDataCanTransferDetailListInnerRemitterCapitalDetailListInnerCapitalSubDetailsInner {
  capital_sub_type?: CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListRemitterCapitalDetailListCapitalSubDetailsCapitalSubType;
  transfer_amount?: number;
}

