// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

import type { CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType, CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus } from "../models";

export interface CgTransferWalletTransferListV30ResponseDataRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner {
  capital_sub_type?: CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType;
  transfer_amount?: number;
  transfer_status?: CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus;
}

