// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = typeof CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType[keyof typeof CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType];

