// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerStructAbstractInfo, CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfo } from "../models";

export interface CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInner {
  struct_abstract_info?: CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerStructAbstractInfo;
  text_abstract_info?: CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfo;
}

