// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { CreativeProceduralCreativeCreateV2CreativeImageMaterialsImageMode, CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInnerImageInfoInner, CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInnerTemplateImage } from "../models";

export interface CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInner {
  image_info?: CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInnerImageInfoInner[];
  image_mode?: CreativeProceduralCreativeCreateV2CreativeImageMaterialsImageMode;
  material_id?: number;
  template_image?: CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInnerTemplateImage;
}

