// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const CreativeGetV2DataListStatus = {
  ADVERTISER_BUDGET_EXCEED: "CREATIVE_STATUS_ADVERTISER_BUDGET_EXCEED",
  ADVERTISER_PRE_OFFLINE_BUDGET: "CREATIVE_STATUS_ADVERTISER_PRE_OFFLINE_BUDGET",
  AD_AUDIT: "CREATIVE_STATUS_AD_AUDIT",
  AD_AUDIT_DENY: "CREATIVE_STATUS_AD_AUDIT_DENY",
  AD_DISABLE: "CREATIVE_STATUS_AD_DISABLE",
  AD_EXTERNAL_URL_DISABLE: "CREATIVE_STATUS_AD_EXTERNAL_URL_DISABLE",
  AD_PRE_OFFLINE_BUDGET: "CREATIVE_STATUS_AD_PRE_OFFLINE_BUDGET",
  AD_REAUDIT: "CREATIVE_STATUS_AD_REAUDIT",
  ALL: "CREATIVE_STATUS_ALL",
  AUDIT: "CREATIVE_STATUS_AUDIT",
  AUDIT_DENY: "CREATIVE_STATUS_AUDIT_DENY",
  AUTHORIZE_CANCEL: "CREATIVE_STATUS_AUTHORIZE_CANCEL",
  AWEME_ACCOUNT_DISABLED: "CREATIVE_STATUS_AWEME_ACCOUNT_DISABLED",
  AWEME_ANCHOR_DISABLED: "CREATIVE_STATUS_AWEME_ANCHOR_DISABLED",
  AWEME_ITEM_DISABLED: "CREATIVE_STATUS_AWEME_ITEM_DISABLED",
  BALANCE_EXCEED: "CREATIVE_STATUS_BALANCE_EXCEED",
  BUDGET_EXCEED: "CREATIVE_STATUS_BUDGET_EXCEED",
  CAMPAIGN_DISABLE: "CREATIVE_STATUS_CAMPAIGN_DISABLE",
  CAMPAIGN_EXCEED: "CREATIVE_STATUS_CAMPAIGN_EXCEED",
  CAN_NOT_EDIT: "CREATIVE_STATUS_CAN_NOT_EDIT",
  CAN_NOT_LAUNCH: "CREATIVE_STATUS_CAN_NOT_LAUNCH",
  CREATE: "CREATIVE_STATUS_CREATE",
  DATA_ERROR: "CREATIVE_STATUS_DATA_ERROR",
  DELETE: "CREATIVE_STATUS_DELETE",
  DELIVERY_OK: "CREATIVE_STATUS_DELIVERY_OK",
  DISABLE: "CREATIVE_STATUS_DISABLE",
  DONE: "CREATIVE_STATUS_DONE",
  FROZEN: "CREATIVE_STATUS_FROZEN",
  LIVE_ROOM_OFF: "CREATIVE_STATUS_LIVE_ROOM_OFF",
  NOT_START: "CREATIVE_STATUS_NOT_START",
  NO_DELIVERY: "CREATIVE_STATUS_NO_DELIVERY",
  NO_SCHEDULE: "CREATIVE_STATUS_NO_SCHEDULE",
  PRODUCT_OFFLINE: "CREATIVE_STATUS_PRODUCT_OFFLINE",
  REAUDIT: "CREATIVE_STATUS_REAUDIT",
} as const;

export type CreativeGetV2DataListStatus = typeof CreativeGetV2DataListStatus[keyof typeof CreativeGetV2DataListStatus];

