// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { CreativeCustomCreativeUpdateV2CreativeListImageMaterialsImageMode, CreativeCustomCreativeUpdateV2RequestCreativeListInnerImageMaterialsInnerImageInfo, CreativeCustomCreativeUpdateV2RequestCreativeListInnerImageMaterialsInnerTemplateImage } from "../models";

export interface CreativeCustomCreativeUpdateV2RequestCreativeListInnerImageMaterialsInner {
  image_info?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerImageMaterialsInnerImageInfo;
  image_mode?: CreativeCustomCreativeUpdateV2CreativeListImageMaterialsImageMode;
  template_image?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerImageMaterialsInnerTemplateImage;
}

