// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { CreativeCustomCreativeCreateV2CreativeListDerivePosterCid, CreativeCustomCreativeCreateV2CreativeListImageMode, CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInner, CreativeCustomCreativeCreateV2RequestCreativeListInnerComponentMaterialsInner, CreativeCustomCreativeCreateV2RequestCreativeListInnerDecorationMaterial, CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInner, CreativeCustomCreativeCreateV2RequestCreativeListInnerInteractiveMaterial, CreativeCustomCreativeCreateV2RequestCreativeListInnerPlayableMaterial, CreativeCustomCreativeCreateV2RequestCreativeListInnerSubTitleMaterial, CreativeCustomCreativeCreateV2RequestCreativeListInnerTitleMaterial, CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterial } from "../models";

export interface CreativeCustomCreativeCreateV2RequestCreativeListInner {
  abstract_materials?: CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInner[];
  component_materials?: CreativeCustomCreativeCreateV2RequestCreativeListInnerComponentMaterialsInner[];
  creative_id?: number | string;
  decoration_material?: CreativeCustomCreativeCreateV2RequestCreativeListInnerDecorationMaterial;
  derive_poster_cid?: CreativeCustomCreativeCreateV2CreativeListDerivePosterCid;
  image_materials?: CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInner[];
  image_mode: CreativeCustomCreativeCreateV2CreativeListImageMode;
  interactive_material?: CreativeCustomCreativeCreateV2RequestCreativeListInnerInteractiveMaterial;
  playable_material?: CreativeCustomCreativeCreateV2RequestCreativeListInnerPlayableMaterial;
  sub_title_material?: CreativeCustomCreativeCreateV2RequestCreativeListInnerSubTitleMaterial;
  third_party_id?: string;
  title_material?: CreativeCustomCreativeCreateV2RequestCreativeListInnerTitleMaterial;
  video_material?: CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterial;
}

