// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInner, CreativeDetailGetV30ResponseDataCreativeComponentMaterialsInner, CreativeDetailGetV30ResponseDataCreativeDecorationMaterial, CreativeDetailGetV30ResponseDataCreativeImageMaterialsInner, CreativeDetailGetV30ResponseDataCreativeSubTitleMaterial, CreativeDetailGetV30ResponseDataCreativeTitleMaterialsInner, CreativeDetailGetV30ResponseDataCreativeVideoMaterialsInner } from "../models";

export interface CreativeDetailGetV30ResponseDataCreative {
  abstract_materials?: CreativeDetailGetV30ResponseDataCreativeAbstractMaterialsInner[];
  component_materials?: CreativeDetailGetV30ResponseDataCreativeComponentMaterialsInner[];
  decoration_material?: CreativeDetailGetV30ResponseDataCreativeDecorationMaterial;
  image_materials?: CreativeDetailGetV30ResponseDataCreativeImageMaterialsInner[];
  sub_title_material?: CreativeDetailGetV30ResponseDataCreativeSubTitleMaterial;
  title_materials?: CreativeDetailGetV30ResponseDataCreativeTitleMaterialsInner[];
  video_materials?: CreativeDetailGetV30ResponseDataCreativeVideoMaterialsInner[];
}

