// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const DiagnosisTaskAdvListV2Results = {
  AD_HIGH_QUALITY_MATERIAL: "AD_HIGH_QUALITY_MATERIAL",
  ECP_HIGH_QUALITY_MATERIAL: "ECP_HIGH_QUALITY_MATERIAL",
  FIRST_PUBLISH_MATERIAL: "FIRST_PUBLISH_MATERIAL",
  INEFFICIENT_MATERIAL: "INEFFICIENT_MATERIAL",
  NON_AD_HIGH_QUALITY_MATERIAL: "NON_AD_HIGH_QUALITY_MATERIAL",
  NON_ECP_HIGH_QUALITY_MATERIAL: "NON_ECP_HIGH_QUALITY_MATERIAL",
  NON_FIRST_PUBLISH_MATERIAL: "NON_FIRST_PUBLISH_MATERIAL",
  NON_INEFFICIENT_MATERIAL: "NON_INEFFICIENT_MATERIAL",
} as const;

export type DiagnosisTaskAdvListV2Results = typeof DiagnosisTaskAdvListV2Results[keyof typeof DiagnosisTaskAdvListV2Results];

