// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const DmpCustomAudienceReadV2DataCustomAudienceListSource = {
  CUSTOM_AUDIENCE_TYPE_BRAND: "CUSTOM_AUDIENCE_TYPE_BRAND",
  CUSTOM_AUDIENCE_TYPE_DATA_SOURCE: "CUSTOM_AUDIENCE_TYPE_DATA_SOURCE",
  CUSTOM_AUDIENCE_TYPE_DOU_PLUS: "CUSTOM_AUDIENCE_TYPE_DOU_PLUS",
  CUSTOM_AUDIENCE_TYPE_EXTEND: "CUSTOM_AUDIENCE_TYPE_EXTEND",
  CUSTOM_AUDIENCE_TYPE_FINANCE: "CUSTOM_AUDIENCE_TYPE_FINANCE",
  CUSTOM_AUDIENCE_TYPE_FRIEND: "CUSTOM_AUDIENCE_TYPE_FRIEND",
  CUSTOM_AUDIENCE_TYPE_ONE_KEY: "CUSTOM_AUDIENCE_TYPE_ONE_KEY",
  CUSTOM_AUDIENCE_TYPE_OPERATE: "CUSTOM_AUDIENCE_TYPE_OPERATE",
  CUSTOM_AUDIENCE_TYPE_PACK_RULE: "CUSTOM_AUDIENCE_TYPE_PACK_RULE",
  CUSTOM_AUDIENCE_TYPE_RULE: "CUSTOM_AUDIENCE_TYPE_RULE",
  CUSTOM_AUDIENCE_TYPE_THEME: "CUSTOM_AUDIENCE_TYPE_THEME",
  CUSTOM_AUDIENCE_TYPE_THIRD_PARTY: "CUSTOM_AUDIENCE_TYPE_THIRD_PARTY",
  CUSTOM_AUDIENCE_TYPE_UPLOAD: "CUSTOM_AUDIENCE_TYPE_UPLOAD",
} as const;

export type DmpCustomAudienceReadV2DataCustomAudienceListSource = typeof DmpCustomAudienceReadV2DataCustomAudienceListSource[keyof typeof DmpCustomAudienceReadV2DataCustomAudienceListSource];

