// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus = {
  CUSTOM_AUDIENCE_DELIVERY_STATUS_AVAILABLE: "CUSTOM_AUDIENCE_DELIVERY_STATUS_AVAILABLE",
  CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUSH: "CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUSH",
  CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUBLISH: "CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUBLISH",
  CUSTOM_AUDIENCE_DELIVERY_STATUS_UNAVAILABLE: "CUSTOM_AUDIENCE_DELIVERY_STATUS_UNAVAILABLE",
} as const;

export type DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus = typeof DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus[keyof typeof DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus];

