// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const DouplusOrderCreateV30ExternalAction = {
  LIKE_COMMENT_AMOUNT: "LIKE_COMMENT_AMOUNT",
  FOLLOWER_COUNT: "FOLLOWER_COUNT",
  VIDEO_PLAYBACK_VOLUME: "VIDEO_PLAYBACK_VOLUME",
  DY_PRIVATE_MESSAGES: "DY_PRIVATE_MESSAGES",
  HIGH_INTERACTION_QUALITY: "HIGH_INTERACTION_QUALITY",
  HIGH_INTERACTION_FREQUENCY: "HIGH_INTERACTION_FREQUENCY",
  ONLY_FOR_ACTIVATION: "ONLY_FOR_ACTIVATION",
  COMMENT_LINK_CLICK: "COMMENT_LINK_CLICK",
  LIVE_ROOM_POPULARITY: "LIVE_ROOM_POPULARITY",
  LIVE_ROOM_FOLLOWER_INCREASE: "LIVE_ROOM_FOLLOWER_INCREASE",
  VIEWER_DONATION: "VIEWER_DONATION",
  VIEWER_INTERACTION: "VIEWER_INTERACTION",
} as const;

export type DouplusOrderCreateV30ExternalAction = typeof DouplusOrderCreateV30ExternalAction[keyof typeof DouplusOrderCreateV30ExternalAction];

