// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const DpaTemplateGetV2DataListTemplateMode = {
  CREATIVE_IMAGE_MODE_SMALL: "CREATIVE_IMAGE_MODE_SMALL",
  CREATIVE_IMAGE_MODE_LARGE: "CREATIVE_IMAGE_MODE_LARGE",
  CREATIVE_IMAGE_MODE_GROUP: "CREATIVE_IMAGE_MODE_GROUP",
  CREATIVE_IMAGE_MODE_VIDEO: "CREATIVE_IMAGE_MODE_VIDEO",
  CREATIVE_IMAGE_MODE_GIF: "CREATIVE_IMAGE_MODE_GIF",
  CREATIVE_IMAGE_MODE_LARGE_VERTICAL: "CREATIVE_IMAGE_MODE_LARGE_VERTICAL",
  CREATIVE_IMAGE_MODE_VIDEO_VERTICAL: "CREATIVE_IMAGE_MODE_VIDEO_VERTICAL",
  TOUTIAO_SEARCH_AD_IMAGE: "TOUTIAO_SEARCH_AD_IMAGE",
  SEARCH_AD_SMALL_IMAGE: "SEARCH_AD_SMALL_IMAGE",
  CREATIVE_IMAGE_MODE_UNION_SPLASH: "CREATIVE_IMAGE_MODE_UNION_SPLASH",
  CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO: "CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO",
  CREATIVE_IMAGE_MODE_AWEME_LIVE: "CREATIVE_IMAGE_MODE_AWEME_LIVE",
  CREATIVE_IMAGE_MODE_DISPLAY_WINDOW: "CREATIVE_IMAGE_MODE_DISPLAY_WINDOW",
  CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL: "CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL",
  CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL: "CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL",
  ALL: "ALL",
  NOT_ALL: "NOT_ALL",
} as const;

export type DpaTemplateGetV2DataListTemplateMode = typeof DpaTemplateGetV2DataListTemplateMode[keyof typeof DpaTemplateGetV2DataListTemplateMode];

