// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const LocalProjectListV30DataProjectListDeepExternalAction = {
  CLUE_ACQUISITION: "CLUE_ACQUISITION",
  CLUE_CONFIRM: "CLUE_CONFIRM",
  CLUE_HIGH_INTENTION: "CLUE_HIGH_INTENTION",
  FOLLOW_ACTION: "FOLLOW_ACTION",
  INTENTION_CLUE_ACQUISITION: "INTENTION_CLUE_ACQUISITION",
  LIVE_ENGAGEMENT: "LIVE_ENGAGEMENT",
  LIVE_ENTER_ACTION: "LIVE_ENTER_ACTION",
  LIVE_OTO_CLICK: "LIVE_OTO_CLICK",
  LIVE_OTO_GROUP_BUYING: "LIVE_OTO_GROUP_BUYING",
  LIVE_STAY_TIME: "LIVE_STAY_TIME",
  MESSAGE_INTENTION_CLUE: "MESSAGE_INTENTION_CLUE",
  NATIVE_ACTION: "NATIVE_ACTION",
  OTO_PAY: "OTO_PAY",
  POI_RECOMMEND: "POI_RECOMMEND",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
  SHOW: "SHOW",
} as const;

export type LocalProjectListV30DataProjectListDeepExternalAction = typeof LocalProjectListV30DataProjectListDeepExternalAction[keyof typeof LocalProjectListV30DataProjectListDeepExternalAction];

