// Generated from oceanengine/ad_open_sdk_go models/model_tools_advertiser_diagnosis_suggestion_get_v3_0_filtering_suggestion_type.go
// Do not edit manually.

export const ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType = {
  SEVEN_DAYS_ROI_SUGGESTION: "SEVEN_DAYS_ROI_SUGGESTION",
} as const;

export type ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType = typeof ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType[keyof typeof ToolsAdvertiserDiagnosisSuggestionGetV30FilteringSuggestionType];

