// Generated from oceanengine/ad_open_sdk_go models/model_promotion_aid_get_v3_0_response_data_promotion_map_data_inner_ads_inner_creatives_inner.go
// Do not edit manually.

import type { PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInnerImageMaterials, PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInnerTitleMaterial, PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInnerVideoMaterial } from "../models/index";

export interface PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInner {
  creative_id?: number | string;
  image_materials?: PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInnerImageMaterials;
  title_material?: PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInnerTitleMaterial;
  video_material?: PromotionAidGetV30ResponseDataPromotionMapDataInnerAdsInnerCreativesInnerVideoMaterial;
}

