// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_can_transfer_balance_v3_0_data_can_transfer_detail_list_remitter_capital_detail_list_capital_sub_details_capital_sub_type.go
// Do not edit manually.

export const CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListRemitterCapitalDetailListCapitalSubDetailsCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListRemitterCapitalDetailListCapitalSubDetailsCapitalSubType = typeof CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListRemitterCapitalDetailListCapitalSubDetailsCapitalSubType[keyof typeof CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListRemitterCapitalDetailListCapitalSubDetailsCapitalSubType];

