// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_create_v3_0_target_wallet_detail_list_transfer_capital_detail_list_capital_sub_type.go
// Do not edit manually.

export const CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalSubType = typeof CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalSubType[keyof typeof CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalSubType];

