// 由 oceanengine/ad_open_sdk_go models/model_shared_wallet_main_wallet_get_v3_0_response_data_main_wallet_info_allocated_balance_ad_shared_allocated_balance.go 生成
// 不要手动编辑。

import type { SharedWalletMainWalletGetV30ResponseDataMainWalletInfoAllocatedBalanceAdSharedAllocatedBalanceAvailableBalance, SharedWalletMainWalletGetV30ResponseDataMainWalletInfoAllocatedBalanceAdSharedAllocatedBalanceUnavailableBalance } from "../models/index";

export interface SharedWalletMainWalletGetV30ResponseDataMainWalletInfoAllocatedBalanceAdSharedAllocatedBalance {
  available_balance?: SharedWalletMainWalletGetV30ResponseDataMainWalletInfoAllocatedBalanceAdSharedAllocatedBalanceAvailableBalance;
  unavailable_balance?: SharedWalletMainWalletGetV30ResponseDataMainWalletInfoAllocatedBalanceAdSharedAllocatedBalanceUnavailableBalance;
}

