// 由 oceanengine/ad_open_sdk_go models/model_local_audience_package_get_v3_0_data_audience_packages_filter_aweme_fans_count.go 生成
// 不要手动编辑。

export const LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeFansCount = {
  FILTER_AWEME_FANS_COUNT_TYPE_OFF: "FILTER_AWEME_FANS_COUNT_TYPE_OFF",
  FILTER_AWEME_FANS_COUNT_TYPE_OVER1000: "FILTER_AWEME_FANS_COUNT_TYPE_OVER1000",
  FILTER_AWEME_FANS_COUNT_TYPE_OVER200: "FILTER_AWEME_FANS_COUNT_TYPE_OVER200",
  FILTER_AWEME_FANS_COUNT_TYPE_OVER500: "FILTER_AWEME_FANS_COUNT_TYPE_OVER500",
} as const;

export type LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeFansCount = typeof LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeFansCount[keyof typeof LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeFansCount];

