// Generated from oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_response_data_list_inner_promotion_materials.go
// Do not edit manually.

import type { PromotionListV30DataListPromotionMaterialsAdvancedDcSettings, PromotionListV30DataListPromotionMaterialsBlueFlowMaterialRecommend, PromotionListV30DataListPromotionMaterialsDynamicCreativeSwitch, PromotionListV30DataListPromotionMaterialsIntelligentGeneration, PromotionListV30DataListPromotionMaterialsOpenUrlType, PromotionListV30DataListPromotionMaterialsOriginalVideoTitle, PromotionListV30DataListPromotionMaterialsParamsType, PromotionListV30DataListPromotionMaterialsUlinkType, PromotionListV30ResponseDataListInnerPromotionMaterialsAnchorMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsCarouselMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsComponentMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsDecorationMaterial, PromotionListV30ResponseDataListInnerPromotionMaterialsImageMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsInstantPlayMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsMiniProgramInfo, PromotionListV30ResponseDataListInnerPromotionMaterialsProductInfo, PromotionListV30ResponseDataListInnerPromotionMaterialsTextAbstractListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsTitleMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner, PromotionListV30ResponseDataListInnerPromotionMaterialsVideoMaterialListInner } from "../models/index";

export interface PromotionListV30ResponseDataListInnerPromotionMaterials {
  advanced_dc_settings?: PromotionListV30DataListPromotionMaterialsAdvancedDcSettings[];
  anchor_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsAnchorMaterialListInner[];
  blue_flow_material_recommend?: PromotionListV30DataListPromotionMaterialsBlueFlowMaterialRecommend;
  call_to_action_buttons?: string[];
  carousel_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsCarouselMaterialListInner[];
  component_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsComponentMaterialListInner[];
  decoration_material?: PromotionListV30ResponseDataListInnerPromotionMaterialsDecorationMaterial;
  dynamic_creative_switch?: PromotionListV30DataListPromotionMaterialsDynamicCreativeSwitch;
  external_url_field?: string;
  external_url_material_list?: string[];
  external_url_params?: string;
  image_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsImageMaterialListInner[];
  instant_play_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsInstantPlayMaterialListInner[];
  intelligent_generation?: PromotionListV30DataListPromotionMaterialsIntelligentGeneration;
  mini_program_info?: PromotionListV30ResponseDataListInnerPromotionMaterialsMiniProgramInfo;
  open_url?: string;
  open_url_field?: string;
  open_url_params?: string;
  open_url_type?: PromotionListV30DataListPromotionMaterialsOpenUrlType;
  open_urls?: string[];
  original_video_title?: PromotionListV30DataListPromotionMaterialsOriginalVideoTitle;
  params_type?: PromotionListV30DataListPromotionMaterialsParamsType;
  playable_url_material_list?: string[];
  playlet_series_url_list?: string[];
  product_info?: PromotionListV30ResponseDataListInnerPromotionMaterialsProductInfo;
  text_abstract_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsTextAbstractListInner[];
  title_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsTitleMaterialListInner[];
  trial_play_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsTrialPlayMaterialListInner[];
  ulink?: string;
  ulink_type?: PromotionListV30DataListPromotionMaterialsUlinkType;
  ulink_url?: string;
  video_material_list?: PromotionListV30ResponseDataListInnerPromotionMaterialsVideoMaterialListInner[];
  web_url_material_list?: string[];
}

