// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_update_v1_0_programmatic_creative_media_list_video_material_star_traffic.go
// Do not edit manually.

export const QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic = {
  Enum_1: 1,
} as const;

export type QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic = typeof QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic[keyof typeof QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic];

