// Generated from oceanengine/ad_open_sdk_go models/model_promotion_update_v3_0_promotion_materials_carousel_material_list_video_hp_visibility.go
// Do not edit manually.

export const PromotionUpdateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility = {
  ALWAYS_VISIBLE: "ALWAYS_VISIBLE",
  HIDE_VIDEO_ON_HP: "HIDE_VIDEO_ON_HP",
} as const;

export type PromotionUpdateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility = typeof PromotionUpdateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility[keyof typeof PromotionUpdateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility];

