// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_detail_get_v1_0_data_delivery_setting_deep_external_action.go
// Do not edit manually.

export const QianchuanAdDetailGetV10DataDeliverySettingDeepExternalAction = {
  AD_CONVERT_TYPE_CARD_ACTIVE: "AD_CONVERT_TYPE_CARD_ACTIVE",
  AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  AD_CONVERT_TYPE_LIVE_COMMENT_ACTION: "AD_CONVERT_TYPE_LIVE_COMMENT_ACTION",
  AD_CONVERT_TYPE_LIVE_ENTER_ACTION: "AD_CONVERT_TYPE_LIVE_ENTER_ACTION",
  AD_CONVERT_TYPE_LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY_7_DAYS: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY_7DAYS",
  AD_CONVERT_TYPE_NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  AD_CONVERT_TYPE_SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
} as const;

export type QianchuanAdDetailGetV10DataDeliverySettingDeepExternalAction = typeof QianchuanAdDetailGetV10DataDeliverySettingDeepExternalAction[keyof typeof QianchuanAdDetailGetV10DataDeliverySettingDeepExternalAction];

