// 由 oceanengine/ad_open_sdk_go models/model_agent_query_risk_promotion_list_v2_data_data_promotion_status_new.go 生成
// 不要手动编辑。

export const AgentQueryRiskPromotionListV2DataDataPromotionStatusNew = {
  ADV_OFFLINE_BUDGET: "ADV_OFFLINE_BUDGET",
  AUDIT: "AUDIT",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  DELETE: "DELETE",
  DELIVERY_OK: "DELIVERY_OK",
  DISABLE_BY_R3: "DISABLE_BY_R3",
  FROZEN: "FROZEN",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NO_SCHEDULE: "NO_SCHEDULE",
  OFFLINE_AUDIT: "OFFLINE_AUDIT",
  PRODUCT_OFFLINE: "PRODUCT_OFFLINE",
  PROJECT_DISABLE: "PROJECT_DISABLE",
  PROJECT_OFFLINE_BUDGET: "PROJECT_OFFLINE_BUDGET",
  PROJECT_REACH_DAILY_DELIVERY: "PROJECT_REACH_DAILY_DELIVERY",
  PROMOTION_DISABLE: "PROMOTION_DISABLE",
  PROMOTION_OFFLINE_BALANCE: "PROMOTION_OFFLINE_BALANCE",
  PROMOTION_OFFLINE_BUDGET: "PROMOTION_OFFLINE_BUDGET",
  PROMOTION_QUOTA_LIMIT: "PROMOTION_QUOTA_LIMIT",
  RE_AUDIT: "RE_AUDIT",
  SHARED_WALLET_OFFLINE_BUDGET: "SHARED_WALLET_OFFLINE_BUDGET",
  STAR_TASK_UN_OPEN: "STAR_TASK_UN_OPEN",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type AgentQueryRiskPromotionListV2DataDataPromotionStatusNew = typeof AgentQueryRiskPromotionListV2DataDataPromotionStatusNew[keyof typeof AgentQueryRiskPromotionListV2DataDataPromotionStatusNew];

