// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_creative_video_materials_dpa_video_template_type.go
// Do not edit manually.

export const CreativeProceduralCreativeUpdateV2CreativeVideoMaterialsDpaVideoTemplateType = {
  DPA_VIDEO_TEMPLATE_DEPRECATED: "DPA_VIDEO_TEMPLATE_DEPRECATED",
  DPA_VIDEO_TEMPLATE_SMART: "DPA_VIDEO_TEMPLATE_SMART",
  DPA_VIDEO_TEMPLATE_CUSTOM: "DPA_VIDEO_TEMPLATE_CUSTOM",
} as const;

export type CreativeProceduralCreativeUpdateV2CreativeVideoMaterialsDpaVideoTemplateType = typeof CreativeProceduralCreativeUpdateV2CreativeVideoMaterialsDpaVideoTemplateType[keyof typeof CreativeProceduralCreativeUpdateV2CreativeVideoMaterialsDpaVideoTemplateType];

