// 由 oceanengine/ad_open_sdk_go models/model_creative_custom_creative_create_v2_request_creative_list_inner_image_materials_inner.go 生成
// 不要手动编辑。

import type { CreativeCustomCreativeCreateV2CreativeListImageMaterialsImageMode, CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInnerImageInfo, CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInnerTemplateImage } from "../models/index";

export interface CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInner {
  image_info?: CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInnerImageInfo;
  image_mode?: CreativeCustomCreativeCreateV2CreativeListImageMaterialsImageMode;
  template_image?: CreativeCustomCreativeCreateV2RequestCreativeListInnerImageMaterialsInnerTemplateImage;
}

