// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_create_v3_0_procedural_material_video_material_list_image_mode.go 生成
// 不要手动编辑。

export const LocalPromotionCreateV30ProceduralMaterialVideoMaterialListImageMode = {
  IMAGE_MODE_VIDEO: "IMAGE_MODE_VIDEO",
  IMAGE_MODE_VIDEO_VERTICAL: "IMAGE_MODE_VIDEO_VERTICAL",
} as const;

export type LocalPromotionCreateV30ProceduralMaterialVideoMaterialListImageMode = typeof LocalPromotionCreateV30ProceduralMaterialVideoMaterialListImageMode[keyof typeof LocalPromotionCreateV30ProceduralMaterialVideoMaterialListImageMode];

