// 由 oceanengine/ad_open_sdk_go models/model_stardelivery_task_author_video_detail_v3_0_data_valid_author_submitted_videos_star_material_purchase_method.go 生成
// 不要手动编辑。

export const StardeliveryTaskAuthorVideoDetailV30DataValidAuthorSubmittedVideosStarMaterialPurchaseMethod = {
  FIXED_PRICE: "FIXED_PRICE",
  PERFORMANCE_BASED: "PERFORMANCE_BASED",
} as const;

export type StardeliveryTaskAuthorVideoDetailV30DataValidAuthorSubmittedVideosStarMaterialPurchaseMethod = typeof StardeliveryTaskAuthorVideoDetailV30DataValidAuthorSubmittedVideosStarMaterialPurchaseMethod[keyof typeof StardeliveryTaskAuthorVideoDetailV30DataValidAuthorSubmittedVideosStarMaterialPurchaseMethod];

