// Generated from oceanengine/ad_open_sdk_go models/model_creative_custom_creative_update_v2_request_creative_list_inner_abstract_materials_inner.go
// Do not edit manually.

import type { CreativeCustomCreativeUpdateV2RequestCreativeListInnerAbstractMaterialsInnerStructAbstractInfo, CreativeCustomCreativeUpdateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfo } from "../models/index";

export interface CreativeCustomCreativeUpdateV2RequestCreativeListInnerAbstractMaterialsInner {
  struct_abstract_info?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerAbstractMaterialsInnerStructAbstractInfo;
  text_abstract_info?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfo;
}

