// 由 oceanengine/ad_open_sdk_go models/model_promotion_update_v3_0_request_promotion_related_product_inner_image_material_list_inner.go 生成
// 不要手动编辑。

import type { PromotionUpdateV30PromotionRelatedProductImageMaterialListImageMode, PromotionUpdateV30RequestPromotionRelatedProductInnerImageMaterialListInnerImagesInner } from "../models/index";

export interface PromotionUpdateV30RequestPromotionRelatedProductInnerImageMaterialListInner {
  image_mode: PromotionUpdateV30PromotionRelatedProductImageMaterialListImageMode;
  images: PromotionUpdateV30RequestPromotionRelatedProductInnerImageMaterialListInnerImagesInner[];
}

