// Generated from oceanengine/ad_open_sdk_go models/model_star_order_get_info_v2_response_data_order_list_inner_demand_info_ad_sync_conf.go
// Do not edit manually.

import type { StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfContentMarketing, StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfDouPlus, StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfEcomShop, StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfLocalPromotion, StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfOceanEngine, StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfQianchuan } from "../models/index";

export interface StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConf {
  content_marketing?: StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfContentMarketing;
  dou_plus?: StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfDouPlus;
  ecom_shop?: StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfEcomShop;
  local_promotion?: StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfLocalPromotion;
  ocean_engine?: StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfOceanEngine;
  qianchuan?: StarOrderGetInfoV2ResponseDataOrderListInnerDemandInfoAdSyncConfQianchuan;
}

