// Generated from oceanengine/ad_open_sdk_go models/model_creative_custom_creative_create_v2_request_creative_list_inner_video_material.go
// Do not edit manually.

import type { CreativeCustomCreativeCreateV2CreativeListVideoMaterialDpaVideoTemplateType, CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterialImageInfo, CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterialVideoInfo } from "../models/index";

export interface CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterial {
  aweme_item_id?: number | string;
  dpa_video_task_ids?: string[];
  dpa_video_template_type?: CreativeCustomCreativeCreateV2CreativeListVideoMaterialDpaVideoTemplateType;
  image_info?: CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterialImageInfo;
  video_info?: CreativeCustomCreativeCreateV2RequestCreativeListInnerVideoMaterialVideoInfo;
}

