// Generated from oceanengine/ad_open_sdk_go models/model_brand_creative_update_v3_0_request_advanced_creative_info_explore_one_time_component.go
// Do not edit manually.

import type { BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponentWipeAfterImage, BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponentWipeBeforeImage, BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponentWipeImage } from "../models/index";

export interface BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponent {
  advanced_duration?: number;
  wipe_after_image?: BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponentWipeAfterImage;
  wipe_before_image?: BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponentWipeBeforeImage;
  wipe_image?: BrandCreativeUpdateV30RequestAdvancedCreativeInfoExploreOneTimeComponentWipeImage;
  wipe_text?: string;
}

