// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_can_transfer_balance_get_v3_0_response_data_can_transfer_detail_list_inner.go
// Do not edit manually.

import type { CgTransferCanTransferBalanceGetV30ResponseDataCanTransferDetailListInnerCapitalDetailListInner, CgTransferCanTransferBalanceGetV30ResponseDataCanTransferDetailListInnerPayeeTransferAmountDetailListInner } from "../models/index";

export interface CgTransferCanTransferBalanceGetV30ResponseDataCanTransferDetailListInner {
  capital_detail_list?: CgTransferCanTransferBalanceGetV30ResponseDataCanTransferDetailListInnerCapitalDetailListInner[];
  payee_transfer_amount_detail_list?: CgTransferCanTransferBalanceGetV30ResponseDataCanTransferDetailListInnerPayeeTransferAmountDetailListInner[];
  remitter_target_id?: number | string;
}

