// 由 oceanengine/ad_open_sdk_go models/model_shared_wallet_wallet_info_get_v3_0_response_data_wallet_info_inner_main_wallet_info_main_shared_range.go 生成
// 不要手动编辑。

import type { SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerMainWalletInfoMainSharedRangeItemsInner } from "../models/index";

export interface SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerMainWalletInfoMainSharedRange {
  items?: SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerMainWalletInfoMainSharedRangeItemsInner[];
}

