// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_can_transfer_balance_v3_0_response_data_can_transfer_detail_list_inner.go
// Do not edit manually.

import type { CgTransferWalletTransferCanTransferBalanceV30ResponseDataCanTransferDetailListInnerPayeeTransferAmountDetailListInner, CgTransferWalletTransferCanTransferBalanceV30ResponseDataCanTransferDetailListInnerRemitterCapitalDetailListInner } from "../models/index";

export interface CgTransferWalletTransferCanTransferBalanceV30ResponseDataCanTransferDetailListInner {
  non_brand_max_transfer_balance?: number;
  payee_transfer_amount_detail_list?: CgTransferWalletTransferCanTransferBalanceV30ResponseDataCanTransferDetailListInnerPayeeTransferAmountDetailListInner[];
  remitter_capital_detail_list?: CgTransferWalletTransferCanTransferBalanceV30ResponseDataCanTransferDetailListInnerRemitterCapitalDetailListInner[];
  remitter_wallet_id?: number | string;
}

