// Generated from oceanengine/ad_open_sdk_go models/model_tools_bp_asset_management_share_v3_0_data_error_list_all_accounts_by_company_account_type.go
// Do not edit manually.

export const ToolsBpAssetManagementShareV30DataErrorListAllAccountsByCompanyAccountType = {
  AD: "AD",
} as const;

export type ToolsBpAssetManagementShareV30DataErrorListAllAccountsByCompanyAccountType = typeof ToolsBpAssetManagementShareV30DataErrorListAllAccountsByCompanyAccountType[keyof typeof ToolsBpAssetManagementShareV30DataErrorListAllAccountsByCompanyAccountType];

