// 由 oceanengine/ad_open_sdk_go models/model_local_audience_package_get_v3_0_data_audience_packages_filter_aweme_abnormal_active.go 生成
// 不要手动编辑。

export const LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeAbnormalActive = {
  FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_OFF: "FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_OFF",
  FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_ON: "FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_ON",
} as const;

export type LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeAbnormalActive = typeof LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeAbnormalActive[keyof typeof LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeAbnormalActive];

