// 由 oceanengine/ad_open_sdk_go models/model_brand_creative_get_v3_0_response_data_creatives_inner_creative_splash_creative.go 生成
// 不要手动编辑。

import type { BrandCreativeGetV30DataCreativesCreativeSplashCreativeSplashType, BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImage, BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashFullVideo, BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashStaticImage } from "../models/index";

export interface BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreative {
  splash_dynamic_image?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashDynamicImage;
  splash_full_video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashFullVideo;
  splash_static_image?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeSplashCreativeSplashStaticImage;
  splash_type?: BrandCreativeGetV30DataCreativesCreativeSplashCreativeSplashType;
}

