// Generated from oceanengine/ad_open_sdk_go models/model_tools_advertiser_diagnosis_suggestion_accept_update_v3_0_project_adjust_list_delivery_optimization_type.go
// Do not edit manually.

export const ToolsAdvertiserDiagnosisSuggestionAcceptUpdateV30ProjectAdjustListDeliveryOptimizationType = {
  OPTIMIZE_COST_EFFECT_UP_COST: "OPTIMIZE_COST_EFFECT_UP_COST",
  OPTIMIZE_COST_EFFECT_UP_ROI: "OPTIMIZE_COST_EFFECT_UP_ROI",
  OPTIMIZE_COST_EFFECT_UP_ROI_STABLE_COST: "OPTIMIZE_COST_EFFECT_UP_ROI_STABLE_COST",
  OPTIMIZE_COST_EFFECT_DOWN_COST: "OPTIMIZE_COST_EFFECT_DOWN_COST",
} as const;

export type ToolsAdvertiserDiagnosisSuggestionAcceptUpdateV30ProjectAdjustListDeliveryOptimizationType = typeof ToolsAdvertiserDiagnosisSuggestionAcceptUpdateV30ProjectAdjustListDeliveryOptimizationType[keyof typeof ToolsAdvertiserDiagnosisSuggestionAcceptUpdateV30ProjectAdjustListDeliveryOptimizationType];

