// Generated from oceanengine/ad_open_sdk_go models/model_local_promotion_update_v3_0_request_procedural_material.go
// Do not edit manually.

import type { LocalPromotionUpdateV30RequestProceduralMaterialCarouselMaterialListInner, LocalPromotionUpdateV30RequestProceduralMaterialTitleMaterialListInner, LocalPromotionUpdateV30RequestProceduralMaterialVideoMaterialListInner } from "../models/index";

export interface LocalPromotionUpdateV30RequestProceduralMaterial {
  carousel_material_list?: LocalPromotionUpdateV30RequestProceduralMaterialCarouselMaterialListInner[];
  title_material_list: LocalPromotionUpdateV30RequestProceduralMaterialTitleMaterialListInner[];
  video_material_list?: LocalPromotionUpdateV30RequestProceduralMaterialVideoMaterialListInner[];
}

