// Generated from oceanengine/ad_open_sdk_go models/model_creative_custom_creative_update_v2_request_creative_list_inner_abstract_materials_inner_text_abstract_info_word_list_inner.go
// Do not edit manually.

export interface CreativeCustomCreativeUpdateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfoWordListInner {
  word_id: number | string;
}

