// 由 oceanengine/ad_open_sdk_go models/model_cg_transfer_transfer_detail_get_v3_0_data_transfer_target_record_list_transfer_capital_record_list_capital_sub_detail_list_capital_sub_type.go 生成
// 不要手动编辑。

export const CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = typeof CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType[keyof typeof CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType];

