// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_control_task_smart_control_status_update_v1_0_opt_type.go
// Do not edit manually.

export const QianchuanUniPromotionAdControlTaskSmartControlStatusUpdateV10OptType = {
  DISABLE: "DISABLE",
} as const;

export type QianchuanUniPromotionAdControlTaskSmartControlStatusUpdateV10OptType = typeof QianchuanUniPromotionAdControlTaskSmartControlStatusUpdateV10OptType[keyof typeof QianchuanUniPromotionAdControlTaskSmartControlStatusUpdateV10OptType];

