// Generated from oceanengine/ad_open_sdk_go models/model_promotion_newcustomer_create_v3_0_promotion_materials_video_material_list_image_mode.go
// Do not edit manually.

export const PromotionNewcustomerCreateV30PromotionMaterialsVideoMaterialListImageMode = {
  CREATIVE_IMAGE_MODE_VIDEO: "CREATIVE_IMAGE_MODE_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO_VERTICAL: "CREATIVE_IMAGE_MODE_VIDEO_VERTICAL",
} as const;

export type PromotionNewcustomerCreateV30PromotionMaterialsVideoMaterialListImageMode = typeof PromotionNewcustomerCreateV30PromotionMaterialsVideoMaterialListImageMode[keyof typeof PromotionNewcustomerCreateV30PromotionMaterialsVideoMaterialListImageMode];

