// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_multi_product_creative_list_creative_card_promotion_card_action_button.go
// Do not edit manually.

export const QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeCardPromotionCardActionButton = {

} as const;

export type QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeCardPromotionCardActionButton = typeof QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeCardPromotionCardActionButton[keyof typeof QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeCardPromotionCardActionButton];

