// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_material_add_v1_0_multi_product_creative_list_video_material_image_mode.go
// Do not edit manually.

export const QianchuanUniPromotionAdMaterialAddV10MultiProductCreativeListVideoMaterialImageMode = {
  VIDEO_LARGE: "VIDEO_LARGE",
  VIDEO_VERTICAL: "VIDEO_VERTICAL",
} as const;

export type QianchuanUniPromotionAdMaterialAddV10MultiProductCreativeListVideoMaterialImageMode = typeof QianchuanUniPromotionAdMaterialAddV10MultiProductCreativeListVideoMaterialImageMode[keyof typeof QianchuanUniPromotionAdMaterialAddV10MultiProductCreativeListVideoMaterialImageMode];

