// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_dmp_audiences_get_v1_0_data_retargeting_tags_source.go
// Do not edit manually.

export const QianchuanDmpAudiencesGetV10DataRetargetingTagsSource = {
  CUSTOM_AUDIENCE_TYPE_BRAND: "CUSTOM_AUDIENCE_TYPE_BRAND",
  CUSTOM_AUDIENCE_TYPE_DATA_SOURCE: "CUSTOM_AUDIENCE_TYPE_DATA_SOURCE",
  CUSTOM_AUDIENCE_TYPE_DOU_PLUS: "CUSTOM_AUDIENCE_TYPE_DOU_PLUS",
  CUSTOM_AUDIENCE_TYPE_EXTEND: "CUSTOM_AUDIENCE_TYPE_EXTEND",
  CUSTOM_AUDIENCE_TYPE_FRIEND: "CUSTOM_AUDIENCE_TYPE_FRIEND",
  CUSTOM_AUDIENCE_TYPE_ONE_KEY: "CUSTOM_AUDIENCE_TYPE_ONE_KEY",
  CUSTOM_AUDIENCE_TYPE_OPERATE: "CUSTOM_AUDIENCE_TYPE_OPERATE",
  CUSTOM_AUDIENCE_TYPE_PACK_RULE: "CUSTOM_AUDIENCE_TYPE_PACK_RULE",
  CUSTOM_AUDIENCE_TYPE_RULE: "CUSTOM_AUDIENCE_TYPE_RULE",
  CUSTOM_AUDIENCE_TYPE_THEME: "CUSTOM_AUDIENCE_TYPE_THEME",
  CUSTOM_AUDIENCE_TYPE_THIRD_PARTY: "CUSTOM_AUDIENCE_TYPE_THIRD_PARTY",
  CUSTOM_AUDIENCE_TYPE_UPLOAD: "CUSTOM_AUDIENCE_TYPE_UPLOAD",
  FINANCECUSTOM_AUDIENCE_TYPE_FINANCE: "FINANCECUSTOM_AUDIENCE_TYPE_FINANCE",
} as const;

export type QianchuanDmpAudiencesGetV10DataRetargetingTagsSource = typeof QianchuanDmpAudiencesGetV10DataRetargetingTagsSource[keyof typeof QianchuanDmpAudiencesGetV10DataRetargetingTagsSource];

