// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_can_transfer_balance_v3_0_data_can_transfer_detail_list_payee_transfer_amount_detail_list_capital_detail_list_platform.go
// Do not edit manually.

export const CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListPlatform = {
  AD: "AD",
  AD_ALL: "AD_ALL",
  BENDITUI: "BENDITUI",
  QIANCHUAN: "QIANCHUAN",
  STAR: "STAR",
} as const;

export type CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListPlatform = typeof CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListPlatform[keyof typeof CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListPlatform];

