// Generated from oceanengine/ad_open_sdk_go models/model_report_creative_get_v2_filtering_inventory_types.go
// Do not edit manually.

export const ReportCreativeGetV2FilteringInventoryTypes = {
  INVENTORY_AUTOMOBILE: "INVENTORY_AUTOMOBILE",
  INVENTORY_FURNISH: "INVENTORY_FURNISH",
  INVENTORY_STUDY: "INVENTORY_STUDY",
  INVENTORY_BEAUTY: "INVENTORY_BEAUTY",
  INVENTORY_UNIVERSAL: "INVENTORY_UNIVERSAL",
  UNION_BOUTIQUE_GAME: "UNION_BOUTIQUE_GAME",
  INVENTORY_PIPIXIA: "INVENTORY_PIPIXIA",
  INVENTORY_FACE_U: "INVENTORY_FACE_U",
  INVENTORY_HOTSOON_FEED: "INVENTORY_HOTSOON_FEED",
  INVENTORY_TOMATO_NOVEL: "INVENTORY_TOMATO_NOVEL",
  INVENTORY_VIDEO_FEED: "INVENTORY_VIDEO_FEED",
  INVENTORY_FEED: "INVENTORY_FEED",
  INVENTORY_SEARCH: "INVENTORY_SEARCH",
  INVENTORY_AWEME_FEED: "INVENTORY_AWEME_FEED",
  INVENTORY_UNION_SLOT: "INVENTORY_UNION_SLOT",
} as const;

export type ReportCreativeGetV2FilteringInventoryTypes = typeof ReportCreativeGetV2FilteringInventoryTypes[keyof typeof ReportCreativeGetV2FilteringInventoryTypes];

