// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_request_multi_product_creative_list_inner_programmatic_creative.go
// Do not edit manually.

import type { QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeCard, QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeMediaListInner, QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeTitleListInner } from "../models/index";

export interface QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreative {
  programmatic_creative_card?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeCard;
  programmatic_creative_media_list?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeMediaListInner[];
  programmatic_creative_title_list?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeTitleListInner[];
}

