// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_aweme_report_order_get_v1_0_filtering_external_action.go
// Do not edit manually.

export const QianchuanAwemeReportOrderGetV10FilteringExternalAction = {
  AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  AD_CONVERT_TYPE_LIVE_ROI: "AD_CONVERT_TYPE_LIVE_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  AD_CONVERT_TYPE_NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  AD_CONVERT_TYPE_SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
  AD_CONVERT_TYPE_VIDEO_ROI: "AD_CONVERT_TYPE_VIDEO_ROI",
  AD_CONVERT_TYPE_LIVE_HEAT: "AD_CONVERT_TYPE_LIVE_HEAT",
} as const;

export type QianchuanAwemeReportOrderGetV10FilteringExternalAction = typeof QianchuanAwemeReportOrderGetV10FilteringExternalAction[keyof typeof QianchuanAwemeReportOrderGetV10FilteringExternalAction];

