// 由 oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_response_data_list_inner_promotion_materials_video_material_list_inner.go 生成
// 不要手动编辑。

import type { PromotionListV30DataListPromotionMaterialsVideoMaterialListAutoMaterialSource, PromotionListV30DataListPromotionMaterialsVideoMaterialListImageMode, PromotionListV30DataListPromotionMaterialsVideoMaterialListIsCarryMaterial, PromotionListV30DataListPromotionMaterialsVideoMaterialListIsHiddenWatermark, PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialOptStatus, PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialStatus, PromotionListV30DataListPromotionMaterialsVideoMaterialListVideoHpVisibility, PromotionListV30DataListPromotionMaterialsVideoMaterialListVideoTemplateType } from "../models/index";

export interface PromotionListV30ResponseDataListInnerPromotionMaterialsVideoMaterialListInner {
  auto_material_source?: PromotionListV30DataListPromotionMaterialsVideoMaterialListAutoMaterialSource;
  create_time?: string;
  guide_video_id?: string;
  image_mode?: PromotionListV30DataListPromotionMaterialsVideoMaterialListImageMode;
  is_carry_material?: PromotionListV30DataListPromotionMaterialsVideoMaterialListIsCarryMaterial;
  is_hidden_watermark?: PromotionListV30DataListPromotionMaterialsVideoMaterialListIsHiddenWatermark;
  item_id?: number | string;
  material_id?: number | string;
  material_opt_status?: PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialOptStatus;
  material_status?: PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialStatus;
  video_cover_id?: string;
  video_hp_visibility?: PromotionListV30DataListPromotionMaterialsVideoMaterialListVideoHpVisibility;
  video_id?: string;
  video_task_ids?: string[];
  video_template_type?: PromotionListV30DataListPromotionMaterialsVideoMaterialListVideoTemplateType;
  visible_end_date?: string;
}

