// 由 oceanengine/ad_open_sdk_go models/model_tools_site_template_create_v2_response_data_bricks_inner_button_download_event.go 生成
// 不要手动编辑。

import type { ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventAndroidLink, ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventIosLink } from "../models/index";

export interface ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEvent {
  android_link?: ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventAndroidLink;
  ios_link?: ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventIosLink;
}

