// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_control_task_create_v1_0_deep_external_action.go 生成
// 不要手动编辑。

export const QianchuanUniPromotionAdControlTaskCreateV10DeepExternalAction = {
  AD_CONVERT_TYPE_LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI",
} as const;

export type QianchuanUniPromotionAdControlTaskCreateV10DeepExternalAction = typeof QianchuanUniPromotionAdControlTaskCreateV10DeepExternalAction[keyof typeof QianchuanUniPromotionAdControlTaskCreateV10DeepExternalAction];

