// 由 oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_request_creative_image_materials_inner_template_image_template_data_list_inner.go 生成
// 不要手动编辑。

export interface CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInnerTemplateImageTemplateDataListInner {
  background_image_id?: string;
}

