// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_detail_v3_0_response_data_procedural_material.go 生成
// 不要手动编辑。

import type { LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInner, LocalPromotionDetailV30ResponseDataProceduralMaterialTitleMaterialListInner, LocalPromotionDetailV30ResponseDataProceduralMaterialVideoMaterialListInner } from "../models/index";

export interface LocalPromotionDetailV30ResponseDataProceduralMaterial {
  carousel_material_list?: LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInner[];
  title_material_list: LocalPromotionDetailV30ResponseDataProceduralMaterialTitleMaterialListInner[];
  video_material_list?: LocalPromotionDetailV30ResponseDataProceduralMaterialVideoMaterialListInner[];
}

