// Generated from oceanengine/ad_open_sdk_go models/model_promotion_create_v3_0_promotion_related_product_video_material_list_image_mode.go
// Do not edit manually.

export const PromotionCreateV30PromotionRelatedProductVideoMaterialListImageMode = {
  CREATIVE_IMAGE_MODE_CALIBRATION_FREE_VIDEO: "CREATIVE_IMAGE_MODE_CALIBRATION_FREE_VIDEO",
  CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO: "CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO: "CREATIVE_IMAGE_MODE_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO_VERTICAL: "CREATIVE_IMAGE_MODE_VIDEO_VERTICAL",
} as const;

export type PromotionCreateV30PromotionRelatedProductVideoMaterialListImageMode = typeof PromotionCreateV30PromotionRelatedProductVideoMaterialListImageMode[keyof typeof PromotionCreateV30PromotionRelatedProductVideoMaterialListImageMode];

