// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_multi_product_creative_list_creative_type.go
// Do not edit manually.

export const QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeType = {
  PROGRAMMATIC_CREATIVE: "PROGRAMMATIC_CREATIVE",
} as const;

export type QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeType = typeof QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeType[keyof typeof QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeType];

