// 由 oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_create_v2_creative_video_materials_dpa_video_template_type.go 生成
// 不要手动编辑。

export const CreativeProceduralCreativeCreateV2CreativeVideoMaterialsDpaVideoTemplateType = {
  DPA_VIDEO_TEMPLATE_SMART: "DPA_VIDEO_TEMPLATE_SMART",
  DPA_VIDEO_TEMPLATE_CUSTOM: "DPA_VIDEO_TEMPLATE_CUSTOM",
  DPA_VIDEO_TEMPLATE_DEPRECATED: "DPA_VIDEO_TEMPLATE_DEPRECATED",
} as const;

export type CreativeProceduralCreativeCreateV2CreativeVideoMaterialsDpaVideoTemplateType = typeof CreativeProceduralCreativeCreateV2CreativeVideoMaterialsDpaVideoTemplateType[keyof typeof CreativeProceduralCreativeCreateV2CreativeVideoMaterialsDpaVideoTemplateType];

