// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_detail_v3_0_response_data_procedural_material_carousel_material_list_inner.go 生成
// 不要手动编辑。

import type { LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInnerImageListInner, LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInnerMusic } from "../models/index";

export interface LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInner {
  carousel_id: number | string;
  image_list?: LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInnerImageListInner[];
  music?: LocalPromotionDetailV30ResponseDataProceduralMaterialCarouselMaterialListInnerMusic;
}

