// Generated from oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_data_list_promotion_materials_video_material_list_material_status.go
// Do not edit manually.

export const PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialStatus = {
  MATERIAL_STATUS_ADV_OFFLINE_BUDGET: "MATERIAL_STATUS_ADV_OFFLINE_BUDGET",
  MATERIAL_STATUS_ADV_PRE_OFFLINE_BUDGET: "MATERIAL_STATUS_ADV_PRE_OFFLINE_BUDGET",
  MATERIAL_STATUS_AUDIT: "MATERIAL_STATUS_AUDIT",
  MATERIAL_STATUS_AVATAR_DISABLED: "MATERIAL_STATUS_AVATAR_DISABLED",
  MATERIAL_STATUS_AWEME_AC_DISABLED: "MATERIAL_STATUS_AWEME_AC_DISABLED",
  MATERIAL_STATUS_AWEME_ANCHOR_DISABLED: "MATERIAL_STATUS_AWEME_ANCHOR_DISABLED",
  MATERIAL_STATUS_AWEME_VIDEO_DISABLED: "MATERIAL_STATUS_AWEME_VIDEO_DISABLED",
  MATERIAL_STATUS_BUDGET_GROUP_OFFLINE_BUDGET: "MATERIAL_STATUS_BUDGET_GROUP_OFFLINE_BUDGET",
  MATERIAL_STATUS_DELETE: "MATERIAL_STATUS_DELETE",
  MATERIAL_STATUS_DISABLE: "MATERIAL_STATUS_DISABLE",
  MATERIAL_STATUS_ERROR_DEFAULT: "MATERIAL_STATUS_ERROR_DEFAULT",
  MATERIAL_STATUS_FROZEN: "MATERIAL_STATUS_FROZEN",
  MATERIAL_STATUS_GUIDE_VIDEO_NOT_EXIST: "MATERIAL_STATUS_GUIDE_VIDEO_NOT_EXIST",
  MATERIAL_STATUS_LIVE_ROOM_OFF: "MATERIAL_STATUS_LIVE_ROOM_OFF",
  MATERIAL_STATUS_MATERIAL_DELETE: "MATERIAL_STATUS_MATERIAL_DELETE",
  MATERIAL_STATUS_NO_SCHEDULE: "MATERIAL_STATUS_NO_SCHEDULE",
  MATERIAL_STATUS_OFFLINE_AUDIT: "MATERIAL_STATUS_OFFLINE_AUDIT",
  MATERIAL_STATUS_OFFLINE_BALANCE: "MATERIAL_STATUS_OFFLINE_BALANCE",
  MATERIAL_STATUS_OFFLINE_BUDGET: "MATERIAL_STATUS_OFFLINE_BUDGET",
  MATERIAL_STATUS_OK: "MATERIAL_STATUS_OK",
  MATERIAL_STATUS_PREOFFLINE_BUGDET: "MATERIAL_STATUS_PREOFFLINE_BUGDET",
  MATERIAL_STATUS_PREONLINE: "MATERIAL_STATUS_PREONLINE",
  MATERIAL_STATUS_PRODUCT_OFFLINE: "MATERIAL_STATUS_PRODUCT_OFFLINE",
  MATERIAL_STATUS_PROJECT_DISABLE: "MATERIAL_STATUS_PROJECT_DISABLE",
  MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET: "MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET",
  MATERIAL_STATUS_PROJECT_PREOFFLINE_BUDGET: "MATERIAL_STATUS_PROJECT_PREOFFLINE_BUDGET",
  MATERIAL_STATUS_PROMOTION_DISABLE: "MATERIAL_STATUS_PROMOTION_DISABLE",
  MATERIAL_STATUS_PROMOTION_QUOTA_LIMIT: "MATERIAL_STATUS_PROMOTION_QUOTA_LIMIT",
  MATERIAL_STATUS_REAUDIT: "MATERIAL_STATUS_REAUDIT",
  MATERIAL_STATUS_STAR_TASK_NOT_STARTED: "MATERIAL_STATUS_STAR_TASK_NOT_STARTED",
  MATERIAL_STATUS_SYSTEM_DISABLE_QUOTA_LIMIT: "MATERIAL_STATUS_SYSTEM_DISABLE_QUOTA_LIMIT",
  MATERIAL_STATUS_TIME_DONE: "MATERIAL_STATUS_TIME_DONE",
  MATERIAL_STATUS_TIME_NO_REACH: "MATERIAL_STATUS_TIME_NO_REACH",
  MATERIAL_STATUS_VIDEO_NO_ADS: "MATERIAL_STATUS_VIDEO_NO_ADS",
} as const;

export type PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialStatus = typeof PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialStatus[keyof typeof PromotionListV30DataListPromotionMaterialsVideoMaterialListMaterialStatus];

