// Generated from oceanengine/ad_open_sdk_go models/model_tools_hot_material_derive_list_v3_0_response_data_data_inner_derive_materials_inner_strategy_detail.go
// Do not edit manually.

import type { ToolsHotMaterialDeriveListV30DataDataDeriveMaterialsStrategyDetailStrategy, ToolsHotMaterialDeriveListV30ResponseDataDataInnerDeriveMaterialsInnerStrategyDetailApplyTimesInner } from "../models/index";

export interface ToolsHotMaterialDeriveListV30ResponseDataDataInnerDeriveMaterialsInnerStrategyDetail {
  apply_times?: ToolsHotMaterialDeriveListV30ResponseDataDataInnerDeriveMaterialsInnerStrategyDetailApplyTimesInner[];
  strategy?: ToolsHotMaterialDeriveListV30DataDataDeriveMaterialsStrategyDetailStrategy;
  strategy_description?: string;
  strategy_name?: string;
}

