// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_create_v2_request_creative.go
// Do not edit manually.

import type { CreativeProceduralCreativeCreateV2RequestCreativeAbstractMaterialsInner, CreativeProceduralCreativeCreateV2RequestCreativeComponentMaterialsInner, CreativeProceduralCreativeCreateV2RequestCreativeDecorationMaterial, CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInner, CreativeProceduralCreativeCreateV2RequestCreativeSubTitleMaterial, CreativeProceduralCreativeCreateV2RequestCreativeTitleMaterialsInner, CreativeProceduralCreativeCreateV2RequestCreativeVideoMaterialsInner } from "../models/index";

export interface CreativeProceduralCreativeCreateV2RequestCreative {
  abstract_materials?: CreativeProceduralCreativeCreateV2RequestCreativeAbstractMaterialsInner[];
  component_materials?: CreativeProceduralCreativeCreateV2RequestCreativeComponentMaterialsInner[];
  decoration_material?: CreativeProceduralCreativeCreateV2RequestCreativeDecorationMaterial;
  image_materials?: CreativeProceduralCreativeCreateV2RequestCreativeImageMaterialsInner[];
  sub_title_material?: CreativeProceduralCreativeCreateV2RequestCreativeSubTitleMaterial;
  title_materials?: CreativeProceduralCreativeCreateV2RequestCreativeTitleMaterialsInner[];
  video_materials?: CreativeProceduralCreativeCreateV2RequestCreativeVideoMaterialsInner[];
}

