// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_cost_protect_status_get_v3_0_response_data_compensate_status_info_list_inner.go 生成
// 不要手动编辑。

import type { LocalPromotionCostProtectStatusGetV30DataCompensateStatusInfoListCompensateEndReasons, LocalPromotionCostProtectStatusGetV30DataCompensateStatusInfoListCompensateInvalidReasons, LocalPromotionCostProtectStatusGetV30DataCompensateStatusInfoListCompensateStatus } from "../models/index";

export interface LocalPromotionCostProtectStatusGetV30ResponseDataCompensateStatusInfoListInner {
  compensate_amount?: number;
  compensate_end_reasons?: LocalPromotionCostProtectStatusGetV30DataCompensateStatusInfoListCompensateEndReasons[];
  compensate_invalid_reasons?: LocalPromotionCostProtectStatusGetV30DataCompensateStatusInfoListCompensateInvalidReasons[];
  compensate_status?: LocalPromotionCostProtectStatusGetV30DataCompensateStatusInfoListCompensateStatus;
  compensate_url?: string;
  promotion?: number;
}

