// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_material_add_v1_0_request_programmatic_creative_media_list.go
// Do not edit manually.

import type { QianchuanUniPromotionAdMaterialAddV10RequestProgrammaticCreativeMediaListTitleMaterialInner, QianchuanUniPromotionAdMaterialAddV10RequestProgrammaticCreativeMediaListVideoMaterialInner } from "../models/index";

export interface QianchuanUniPromotionAdMaterialAddV10RequestProgrammaticCreativeMediaList {
  title_material?: QianchuanUniPromotionAdMaterialAddV10RequestProgrammaticCreativeMediaListTitleMaterialInner[];
  video_material?: QianchuanUniPromotionAdMaterialAddV10RequestProgrammaticCreativeMediaListVideoMaterialInner[];
}

