// 由 oceanengine/ad_open_sdk_go models/model_oc_project_tools_material_raise_get_v3_0_data_list_material_adjust_status_second.go 生成
// 不要手动编辑。

export const OcProjectToolsMaterialRaiseGetV30DataListMaterialAdjustStatusSecond = {
  ACCOUNT_AVATAR_NOT_AVAILABLE_FOR_DELIVERY: "ACCOUNT_AVATAR_NOT_AVAILABLE_FOR_DELIVERY",
  ACCOUNT_EXCEEDS_BUDGET: "ACCOUNT_EXCEEDS_BUDGET",
  ADJUST_DELETED: "ADJUST_DELETED",
  ADJUST_TERMINATED: "ADJUST_TERMINATED",
  ALL_KEYWORDS_DELETED: "ALL_KEYWORDS_DELETED",
  ALL_MATERIALS_DELETED: "ALL_MATERIALS_DELETED",
  APP_NOT_AVAILABLE_FOR_DELIVERY: "APP_NOT_AVAILABLE_FOR_DELIVERY",
  DOUYIN_ACCOUNT_NOT_AVAILABLE_FOR_DELIVERY: "DOUYIN_ACCOUNT_NOT_AVAILABLE_FOR_DELIVERY",
  GOODS_NOT_AVAILABLE_FOR_DELIVERY: "GOODS_NOT_AVAILABLE_FOR_DELIVERY",
  LIVE_ROOM_NOT_AVAILABLE_FOR_DELIVERY: "LIVE_ROOM_NOT_AVAILABLE_FOR_DELIVERY",
  LIVE_ROOM_NOT_STARTED: "LIVE_ROOM_NOT_STARTED",
  MODIFY_AUDITING: "MODIFY_AUDITING",
  NEW_CREATED_AUDITING: "NEW_CREATED_AUDITING",
  PAUSED: "PAUSED",
  PROJECT_AUDIENCE_SETTING_CONFLICT: "PROJECT_AUDIENCE_SETTING_CONFLICT",
  PROJECT_AUDIT_REJECTED: "PROJECT_AUDIT_REJECTED",
  PROJECT_BALANCE_INSUFFICIENT: "PROJECT_BALANCE_INSUFFICIENT",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  PROJECT_DELETED: "PROJECT_DELETED",
  PROJECT_EXCEEDS_BUDGET: "PROJECT_EXCEEDS_BUDGET",
  PROJECT_MODIFY_AUDITING: "PROJECT_MODIFY_AUDITING",
  PROJECT_NEW_CREATED_AUDITING: "PROJECT_NEW_CREATED_AUDITING",
  PROJECT_NOT_IN_DELIVERY_PERIOD: "PROJECT_NOT_IN_DELIVERY_PERIOD",
  PROJECT_NOT_REACH_DELIVERY_TIME: "PROJECT_NOT_REACH_DELIVERY_TIME",
  PROJECT_PAUSED: "PROJECT_PAUSED",
  PROJECT_REACHED_DELIVERY_DURATION: "PROJECT_REACHED_DELIVERY_DURATION",
  PROJECT_TERMINATED: "PROJECT_TERMINATED",
  REACHED_REGULATION_BUDGET_UPPER_LIMIT: "REACHED_REGULATION_BUDGET_UPPER_LIMIT",
  REVIEW_REJECTED: "REVIEW_REJECTED",
  SHARED_WALLET_EXCEEDS_BUDGET: "SHARED_WALLET_EXCEEDS_BUDGET",
  TASK_BID_EXCEEDS_PROJECT_BUDGET: "TASK_BID_EXCEEDS_PROJECT_BUDGET",
  TASK_REACHED_REGULATION_DURATION: "TASK_REACHED_REGULATION_DURATION",
} as const;

export type OcProjectToolsMaterialRaiseGetV30DataListMaterialAdjustStatusSecond = typeof OcProjectToolsMaterialRaiseGetV30DataListMaterialAdjustStatusSecond[keyof typeof OcProjectToolsMaterialRaiseGetV30DataListMaterialAdjustStatusSecond];

