// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_control_task_list_v1_0_filtering_external_action.go
// Do not edit manually.

export const QianchuanUniPromotionAdControlTaskListV10FilteringExternalAction = {
  AD_CONVERT_TYPE_LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
} as const;

export type QianchuanUniPromotionAdControlTaskListV10FilteringExternalAction = typeof QianchuanUniPromotionAdControlTaskListV10FilteringExternalAction[keyof typeof QianchuanUniPromotionAdControlTaskListV10FilteringExternalAction];

