// Generated from oceanengine/ad_open_sdk_go models/model_creative_custom_creative_create_v2_request_creative_list_inner_abstract_materials_inner_text_abstract_info_bidword_list_inner.go
// Do not edit manually.

export interface CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfoBidwordListInner {
  default_word: string;
}

