// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_detail_v1_0_response_data_programmatic_creative_media_list_block_video_material_inner.go 生成
// 不要手动编辑。

export interface QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListBlockVideoMaterialInner {
  aweme_item_id: number | string;
}

