// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_transfer_balance_get_v3_0_response_data_target_amount_detail_list_inner_capital_detail_list_inner.go
// Do not edit manually.

import type { CgTransferTransferBalanceGetV30DataTargetAmountDetailListCapitalDetailListCapitalType } from "../models/index";

export interface CgTransferTransferBalanceGetV30ResponseDataTargetAmountDetailListInnerCapitalDetailListInner {
  capital_type: CgTransferTransferBalanceGetV30DataTargetAmountDetailListCapitalDetailListCapitalType;
  transfer_balance: number;
}

