// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_request_creative.go
// Do not edit manually.

import type { CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInner, CreativeProceduralCreativeUpdateV2RequestCreativeComponentMaterialsInner, CreativeProceduralCreativeUpdateV2RequestCreativeDecorationMaterial, CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInner, CreativeProceduralCreativeUpdateV2RequestCreativeSubTitleMaterial, CreativeProceduralCreativeUpdateV2RequestCreativeTitleMaterialsInner, CreativeProceduralCreativeUpdateV2RequestCreativeVideoMaterialsInner } from "../models/index";

export interface CreativeProceduralCreativeUpdateV2RequestCreative {
  abstract_materials?: CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInner[];
  component_materials?: CreativeProceduralCreativeUpdateV2RequestCreativeComponentMaterialsInner[];
  decoration_material?: CreativeProceduralCreativeUpdateV2RequestCreativeDecorationMaterial;
  image_materials?: CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInner[];
  sub_title_material?: CreativeProceduralCreativeUpdateV2RequestCreativeSubTitleMaterial;
  title_materials?: CreativeProceduralCreativeUpdateV2RequestCreativeTitleMaterialsInner[];
  video_materials?: CreativeProceduralCreativeUpdateV2RequestCreativeVideoMaterialsInner[];
}

