// Generated from oceanengine/ad_open_sdk_go models/model_stardelivery_task_detail_v3_0_data_star_task_materials_requirements_video_reviewer.go
// Do not edit manually.

export const StardeliveryTaskDetailV30DataStarTaskMaterialsRequirementsVideoReviewer = {
  CONFIRM_BY_ISV_ONLY: "CONFIRM_BY_ISV_ONLY",
  NEED_RE_CONFIRM: "NEED_RE_CONFIRM",
} as const;

export type StardeliveryTaskDetailV30DataStarTaskMaterialsRequirementsVideoReviewer = typeof StardeliveryTaskDetailV30DataStarTaskMaterialsRequirementsVideoReviewer[keyof typeof StardeliveryTaskDetailV30DataStarTaskMaterialsRequirementsVideoReviewer];

