// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_detail_v3_0_data_procedural_material_video_material_list_image_mode.go 生成
// 不要手动编辑。

export const LocalPromotionDetailV30DataProceduralMaterialVideoMaterialListImageMode = {
  IMAGE_MODE_VIDEO: "IMAGE_MODE_VIDEO",
  IMAGE_MODE_VIDEO_VERTICAL: "IMAGE_MODE_VIDEO_VERTICAL",
} as const;

export type LocalPromotionDetailV30DataProceduralMaterialVideoMaterialListImageMode = typeof LocalPromotionDetailV30DataProceduralMaterialVideoMaterialListImageMode[keyof typeof LocalPromotionDetailV30DataProceduralMaterialVideoMaterialListImageMode];

