// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_update_v1_0_multi_product_creative_list_programmatic_creative_programmatic_creative_card_promotion_card_button_smart_optimization.go
// Do not edit manually.

export const QianchuanAdUpdateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdUpdateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization = typeof QianchuanAdUpdateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization[keyof typeof QianchuanAdUpdateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization];

