// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_query_transfer_detail_v3_0_response_data_transfer_target_record_list_inner_transfer_capital_record_list_inner_capital_sub_detail_list_inner.go
// Do not edit manually.

import type { CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType, CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus } from "../models/index";

export interface CgTransferQueryTransferDetailV30ResponseDataTransferTargetRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner {
  capital_sub_type?: CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType;
  transfer_amount?: number;
  transfer_status?: CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus;
}

