// 由 oceanengine/ad_open_sdk_go models/model_creative_custom_creative_update_v2_request_creative_list_inner_title_material.go 生成
// 不要手动编辑。

import type { CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterialBidwordListInner, CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterialDpaWordListInner, CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterialWordListInner } from "../models/index";

export interface CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterial {
  bidword_list?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterialBidwordListInner[];
  dpa_word_list?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterialDpaWordListInner[];
  title: string;
  word_list?: CreativeCustomCreativeUpdateV2RequestCreativeListInnerTitleMaterialWordListInner[];
}

