// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_detail_get_v1_0_data_multi_product_creative_list_programmatic_creative_programmatic_creative_title_list_title_type.go
// Do not edit manually.

export const QianchuanAdDetailGetV10DataMultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType = {
  AWEME_CAROUSEL: "AWEME_CAROUSEL",
  COMMODITY_CARD: "COMMODITY_CARD",
  CUSTOM: "CUSTOM",
} as const;

export type QianchuanAdDetailGetV10DataMultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType = typeof QianchuanAdDetailGetV10DataMultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType[keyof typeof QianchuanAdDetailGetV10DataMultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType];

