// Generated from oceanengine/ad_open_sdk_go models/model_star_mcn_provider_get_task_item_list_v2_response_data_items_inner_item_info_data.go
// Do not edit manually.

import type { StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeAdConvertData, StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeEffectData, StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeNaturalConvertData } from "../models/index";

export interface StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoData {
  real_time_ad_convert_data?: StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeAdConvertData;
  real_time_effect_data?: StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeEffectData;
  real_time_natural_convert_data?: StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeNaturalConvertData;
}

