// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_report_uni_promotion_dimension_data_author_get_v1_0_filtering.go 生成
// 不要手动编辑。

import type { QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringOrderPlatform, QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringSmartBidType } from "../models/index";

export interface QianchuanReportUniPromotionDimensionDataAuthorGetV10Filtering {
  order_platform?: QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringOrderPlatform;
  smart_bid_type?: QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringSmartBidType;
}

