// Generated from oceanengine/ad_open_sdk_go models/model_star_report_order_overview_v2_response_data_base_stats_inner_seed_stat_hot_keywords_inner.go
// Do not edit manually.

import type { StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerAllInner, StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerBrandInner, StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerCharacterInner, StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerPainInner, StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerProductInner, StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerSceneInner } from "../models/index";

export interface StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInner {
  all?: StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerAllInner[];
  brand?: StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerBrandInner[];
  character?: StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerCharacterInner[];
  pain?: StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerPainInner[];
  product?: StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerProductInner[];
  scene?: StarReportOrderOverviewV2ResponseDataBaseStatsInnerSeedStatHotKeywordsInnerSceneInner[];
}

