// Generated from oceanengine/ad_open_sdk_go models/model_agent_adv_brand_list_query_v2_data_data_account_status.go
// Do not edit manually.

export const AgentAdvBrandListQueryV2DataDataAccountStatus = {
  STATUS_DISABLE: "STATUS_DISABLE",
  STATUS_PENDING_CONFIRM: "STATUS_PENDING_CONFIRM",
  STATUS_PENDING_VERIFIED: "STATUS_PENDING_VERIFIED",
  STATUS_CONFIRM_FAIL: "STATUS_CONFIRM_FAIL",
  STATUS_ENABLE: "STATUS_ENABLE",
  STATUS_CONFIRM_FAIL_END: "STATUS_CONFIRM_FAIL_END",
  STATUS_PENDING_CONFIRM_MODIFY: "STATUS_PENDING_CONFIRM_MODIFY",
  STATUS_CONFIRM_MODIFY_FAIL: "STATUS_CONFIRM_MODIFY_FAIL",
  STATUS_PUNISH: "STATUS_PUNISH",
  STATUS_WAIT_FOR_BPM_AUDIT: "STATUS_WAIT_FOR_BPM_AUDIT",
  STATUS_SELF_SERVICE_UNAUDITED: "STATUS_SELF_SERVICE_UNAUDITED",
  STATUS_ENABLE_AND_AVATAR_AUDITING: "STATUS_ENABLE_AND_AVATAR_AUDITING",
  STATUS_WAIT_FOR_BPM_FILE_CONTACT: "STATUS_WAIT_FOR_BPM_FILE_CONTACT",
  STATUS_WAIT_FOR_ACCOUNT_FEE: "STATUS_WAIT_FOR_ACCOUNT_FEE",
  STATUS_WAIT_FOR_PUBLIC_AUTH: "STATUS_WAIT_FOR_PUBLIC_AUTH",
} as const;

export type AgentAdvBrandListQueryV2DataDataAccountStatus = typeof AgentAdvBrandListQueryV2DataDataAccountStatus[keyof typeof AgentAdvBrandListQueryV2DataDataAccountStatus];

