// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_query_transfer_balance_v3_0_response_data_accont_amount_detail_list_inner_capital_detail_list_inner_capital_sub_details_inner.go
// Do not edit manually.

import type { CgTransferQueryTransferBalanceV30DataAccontAmountDetailListCapitalDetailListCapitalSubDetailsCapitalSubType } from "../models/index";

export interface CgTransferQueryTransferBalanceV30ResponseDataAccontAmountDetailListInnerCapitalDetailListInnerCapitalSubDetailsInner {
  capital_sub_type?: CgTransferQueryTransferBalanceV30DataAccontAmountDetailListCapitalDetailListCapitalSubDetailsCapitalSubType;
  transfer_amount?: number;
}

