// Generated from oceanengine/ad_open_sdk_go models/model_promotion_auto_generate_config_get_v3_0_data_templates_template_type.go
// Do not edit manually.

export const PromotionAutoGenerateConfigGetV30DataTemplatesTemplateType = {
  HORIZONTAL_TO_VERTICAL_DYNAMIC_BACK_VIDEO: "HORIZONTAL_TO_VERTICAL_DYNAMIC_BACK_VIDEO",
  VERTICAL_TO_HORIZONTAL_DYNAMIC_BACK_VIDEO: "VERTICAL_TO_HORIZONTAL_DYNAMIC_BACK_VIDEO",
  VERTICAL_TO_HORIZONTAL_STATIC_BACK_VIDEO: "VERTICAL_TO_HORIZONTAL_STATIC_BACK_VIDEO",
} as const;

export type PromotionAutoGenerateConfigGetV30DataTemplatesTemplateType = typeof PromotionAutoGenerateConfigGetV30DataTemplatesTemplateType[keyof typeof PromotionAutoGenerateConfigGetV30DataTemplatesTemplateType];

