// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_detail_v3_0_data_transfer_wallet_record_list_transfer_capital_record_list_capital_sub_detail_list_transfer_status.go
// Do not edit manually.

export const CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus = {
  NO_TRANSFER: "NO_TRANSFER",
  TRANSFER_FAILED: "TRANSFER_FAILED",
  TRANSFER_ING: "TRANSFER_ING",
  TRANSFER_PART: "TRANSFER_PART",
  TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
} as const;

export type CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus = typeof CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus[keyof typeof CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus];

