// Generated from oceanengine/ad_open_sdk_go models/model_brand_material_list_v3_0_response_data_materials_inner_material_component_static_none_full_screen.go
// Do not edit manually.

import type { BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticNoneFullScreenImageInfoBkListInner } from "../models/index";

export interface BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticNoneFullScreen {
  image_info_bk_list?: BrandMaterialListV30ResponseDataMaterialsInnerMaterialComponentStaticNoneFullScreenImageInfoBkListInner[];
}

