// Generated from oceanengine/ad_open_sdk_go models/model_shared_wallet_wallet_balance_get_v3_0_wallet_balance_filters.go
// Do not edit manually.

import type { SharedWalletWalletBalanceGetV30WalletBalanceFiltersAccountPlatformType, SharedWalletWalletBalanceGetV30WalletBalanceFiltersCapitalType, SharedWalletWalletBalanceGetV30WalletBalanceFiltersDeliveryType } from "../models/index";

export interface SharedWalletWalletBalanceGetV30WalletBalanceFilters {
  account_platform_type?: SharedWalletWalletBalanceGetV30WalletBalanceFiltersAccountPlatformType;
  capital_type?: SharedWalletWalletBalanceGetV30WalletBalanceFiltersCapitalType;
  delivery_type?: SharedWalletWalletBalanceGetV30WalletBalanceFiltersDeliveryType;
}

