// 由 oceanengine/ad_open_sdk_go models/model_report_agent_get_v2_v2_filtering_account_status.go 生成
// 不要手动编辑。

export const ReportAgentGetV2V2FilteringAccountStatus = {
  STATUS_PENDING_CONFIRM: "STATUS_PENDING_CONFIRM",
  STATUS_DISABLE: "STATUS_DISABLE",
  STATUS_CONFIRM_FAIL: "STATUS_CONFIRM_FAIL",
  STATUS_CONFIRM_FAIL_END: "STATUS_CONFIRM_FAIL_END",
  STATUS_PENDING_VERIFIED: "STATUS_PENDING_VERIFIED",
  STATUS_SELF_SERVICE_UNAUDITED: "STATUS_SELF_SERVICE_UNAUDITED",
  STATUS_WAIT_FOR_PUBLIC_AUTH: "STATUS_WAIT_FOR_PUBLIC_AUTH",
  STATUS_CONFIRM_MODIFY_FAIL: "STATUS_CONFIRM_MODIFY_FAIL",
  STATUS_ENABLE_AND_AVATAR_AUDITING: "STATUS_ENABLE_AND_AVATAR_AUDITING",
  STATUS_WAIT_FOR_ACCOUNT_FEE: "STATUS_WAIT_FOR_ACCOUNT_FEE",
  STATUS_PUNISH: "STATUS_PUNISH",
  STATUS_WAIT_FOR_BPM_FILE_CONTACT: "STATUS_WAIT_FOR_BPM_FILE_CONTACT",
  STATUS_WAIT_FOR_BPM_AUDIT: "STATUS_WAIT_FOR_BPM_AUDIT",
  STATUS_ENABLE: "STATUS_ENABLE",
  STATUS_PENDING_CONFIRM_MODIFY: "STATUS_PENDING_CONFIRM_MODIFY",
} as const;

export type ReportAgentGetV2V2FilteringAccountStatus = typeof ReportAgentGetV2V2FilteringAccountStatus[keyof typeof ReportAgentGetV2V2FilteringAccountStatus];

