// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_transfer_detail_get_v3_0_response_data_transfer_target_record_list_inner_transfer_capital_record_list_inner_capital_sub_detail_list_inner.go
// Do not edit manually.

import type { CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType, CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus } from "../models/index";

export interface CgTransferTransferDetailGetV30ResponseDataTransferTargetRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner {
  capital_sub_type?: CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType;
  transfer_amount?: number;
  transfer_status?: CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus;
}

