// Generated from oceanengine/ad_open_sdk_go models/model_tools_aweme_auth_list_v2_data_list_video_info_image_mode.go
// Do not edit manually.

export const ToolsAwemeAuthListV2DataListVideoInfoImageMode = {
  AWEME_PHOTO: "AWEME_PHOTO",
  CREATIVE_IMAGE_MODE_AWEME_LIVE: "CREATIVE_IMAGE_MODE_AWEME_LIVE",
  CREATIVE_IMAGE_MODE_DISPLAY_WINDOW: "CREATIVE_IMAGE_MODE_DISPLAY_WINDOW",
  CREATIVE_IMAGE_MODE_GIF: "CREATIVE_IMAGE_MODE_GIF",
  CREATIVE_IMAGE_MODE_GROUP: "CREATIVE_IMAGE_MODE_GROUP",
  CREATIVE_IMAGE_MODE_LARGE: "CREATIVE_IMAGE_MODE_LARGE",
  CREATIVE_IMAGE_MODE_LARGE_VERTICAL: "CREATIVE_IMAGE_MODE_LARGE_VERTICAL",
  CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL: "CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL",
  CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL: "CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL",
  CREATIVE_IMAGE_MODE_SMALL: "CREATIVE_IMAGE_MODE_SMALL",
  CREATIVE_IMAGE_MODE_UNION_SPLASH: "CREATIVE_IMAGE_MODE_UNION_SPLASH",
  CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO: "CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO: "CREATIVE_IMAGE_MODE_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO_VERTICAL: "CREATIVE_IMAGE_MODE_VIDEO_VERTICAL",
  SEARCH_AD_SMALL_IMAGE: "SEARCH_AD_SMALL_IMAGE",
  TOUTIAO_SEARCH_AD_IMAGE: "TOUTIAO_SEARCH_AD_IMAGE",
} as const;

export type ToolsAwemeAuthListV2DataListVideoInfoImageMode = typeof ToolsAwemeAuthListV2DataListVideoInfoImageMode[keyof typeof ToolsAwemeAuthListV2DataListVideoInfoImageMode];

