// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_request_creative_image_materials_inner.go
// Do not edit manually.

import type { CreativeProceduralCreativeUpdateV2CreativeImageMaterialsImageMode, CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInnerImageInfoInner, CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInnerTemplateImage } from "../models/index";

export interface CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInner {
  image_info?: CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInnerImageInfoInner[];
  image_mode?: CreativeProceduralCreativeUpdateV2CreativeImageMaterialsImageMode;
  material_id?: number | string;
  template_image?: CreativeProceduralCreativeUpdateV2RequestCreativeImageMaterialsInnerTemplateImage;
}

