// Generated from oceanengine/ad_open_sdk_go models/model_tools_promotion_card_recommend_get_v2_advanced_creative_type.go
// Do not edit manually.

export const ToolsPromotionCardRecommendGetV2AdvancedCreativeType = {
  ATTACHED_CREATIVE_APP: "ATTACHED_CREATIVE_APP",
  ATTACHED_CREATIVE_LIVE_CARD: "ATTACHED_CREATIVE_LIVE_CARD",
  ATTACHED_CREATIVE_PHONE: "ATTACHED_CREATIVE_PHONE",
  ATTACHED_CREATIVE_VOTE_INTERACT: "ATTACHED_CREATIVE_VOTE_INTERACT",
  ATTACHED_CREATIVE_SMART_PHONE: "ATTACHED_CREATIVE_SMART_PHONE",
  ATTACHED_CREATIVE_GAME_SUBSCRIBE: "ATTACHED_CREATIVE_GAME_SUBSCRIBE",
  ATTACHED_CREATIVE_CARD: "ATTACHED_CREATIVE_CARD",
  ATTACHED_CREATIVE_INTERACT: "ATTACHED_CREATIVE_INTERACT",
  ATTACHED_CREATIVE_CONSULTANT: "ATTACHED_CREATIVE_CONSULTANT",
  ATTACHED_CREATIVE_NONE: "ATTACHED_CREATIVE_NONE",
  ATTACHED_CREATIVE_COUPON: "ATTACHED_CREATIVE_COUPON",
  ATTACHED_CREATIVE_GAME_PACKAGE: "ATTACHED_CREATIVE_GAME_PACKAGE",
  ATTACHED_CREATIVE_COUPON_INTERACT: "ATTACHED_CREATIVE_COUPON_INTERACT",
  ATTACHED_CREATIVE_DOWNLOAD_CARD: "ATTACHED_CREATIVE_DOWNLOAD_CARD",
  ATTACHED_CREATIVE_COMMERCE_CARD: "ATTACHED_CREATIVE_COMMERCE_CARD",
  ATTACHED_CREATIVE_GAME_FORM: "ATTACHED_CREATIVE_GAME_FORM",
  ATTACHED_CREATIVE_FORM: "ATTACHED_CREATIVE_FORM",
} as const;

export type ToolsPromotionCardRecommendGetV2AdvancedCreativeType = typeof ToolsPromotionCardRecommendGetV2AdvancedCreativeType[keyof typeof ToolsPromotionCardRecommendGetV2AdvancedCreativeType];

