// Generated from oceanengine/ad_open_sdk_go models/model_promotion_update_v3_0_request_promotion_materials_image_material_list_inner.go
// Do not edit manually.

import type { PromotionUpdateV30PromotionMaterialsImageMaterialListImageMode, PromotionUpdateV30RequestPromotionMaterialsImageMaterialListInnerImagesInner } from "../models/index";

export interface PromotionUpdateV30RequestPromotionMaterialsImageMaterialListInner {
  image_mode: PromotionUpdateV30PromotionMaterialsImageMaterialListImageMode;
  images: PromotionUpdateV30RequestPromotionMaterialsImageMaterialListInnerImagesInner[];
}

