// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_multi_product_creative_list_creative_setting_is_homepage_hide.go 生成
// 不要手动编辑。

export const QianchuanAdCreateV10MultiProductCreativeListCreativeSettingIsHomepageHide = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdCreateV10MultiProductCreativeListCreativeSettingIsHomepageHide = typeof QianchuanAdCreateV10MultiProductCreativeListCreativeSettingIsHomepageHide[keyof typeof QianchuanAdCreateV10MultiProductCreativeListCreativeSettingIsHomepageHide];

