// 由 oceanengine/ad_open_sdk_go models/model_std_project_list_v3_0_data_list_status_second.go 生成
// 不要手动编辑。

export const StdProjectListV30DataListStatusSecond = {
  ADV_OFFLINE_BUDGET: "ADV_OFFLINE_BUDGET",
  ADV_PRE_OFFLINE_BUDGET: "ADV_PRE_OFFLINE_BUDGET",
  AUDIT_STATUS: "AUDIT_STATUS",
  AVATAR_DISABLED: "AVATAR_DISABLED",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  AWEME_ANCHOR_DISABLED: "AWEME_ANCHOR_DISABLED",
  BUDGET_GROUP_OFFLINE_BUDGET: "BUDGET_GROUP_OFFLINE_BUDGET",
  DISABLE: "DISABLE",
  DISABLE_BYR3: "DISABLE_BYR3",
  LACK_BASIC_MATERIAL_STATUS: "LACK_BASIC_MATERIAL_STATUS",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NO_SCHEDUAL: "NO_SCHEDUAL",
  OFFLINE_AUDIT_STATUS: "OFFLINE_AUDIT_STATUS",
  PRODUCT_OFFLINE: "PRODUCT_OFFLINE",
  PROJECT_OFFLINE_BUDGET: "PROJECT_OFFLINE_BUDGET",
  PROJECT_PRE_OFFLINE_BUDGET: "PROJECT_PRE_OFFLINE_BUDGET",
  PROJECT_REACH_DAILY_DELIVERY_STATUS: "PROJECT_REACH_DAILY_DELIVERY_STATUS",
  PROMOTION_APP_UNAVAILABLE: "PROMOTION_APP_UNAVAILABLE",
  PROMOTION_OFFLINE_BALANCE: "PROMOTION_OFFLINE_BALANCE",
  PROMOTION_OFFLINE_BUDGET: "PROMOTION_OFFLINE_BUDGET",
  PROMOTION_QUOTA_LIMIT: "PROMOTION_QUOTA_LIMIT",
  REAUDIT_STATUS: "REAUDIT_STATUS",
  SHARED_WALLET_OFFLINE_BUDGET: "SHARED_WALLET_OFFLINE_BUDGET",
  STAR_TASK_UNOPEN: "STAR_TASK_UNOPEN",
  SYSTEM_DISABLE_STATUS: "SYSTEM_DISABLE_STATUS",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type StdProjectListV30DataListStatusSecond = typeof StdProjectListV30DataListStatusSecond[keyof typeof StdProjectListV30DataListStatusSecond];

