// 由 oceanengine/ad_open_sdk_go models/model_promotion_create_v3_0_promotion_materials_carousel_material_list_video_hp_visibility.go 生成
// 不要手动编辑。

export const PromotionCreateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility = {
  ALWAYS_VISIBLE: "ALWAYS_VISIBLE",
  HIDE_VIDEO_ON_HP: "HIDE_VIDEO_ON_HP",
} as const;

export type PromotionCreateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility = typeof PromotionCreateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility[keyof typeof PromotionCreateV30PromotionMaterialsCarouselMaterialListVideoHpVisibility];

