// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_material_get_v1_0_response_data_ad_material_infos_inner.go
// Do not edit manually.

import type { QianchuanUniPromotionAdMaterialGetV10DataAdMaterialInfosAuditStatus, QianchuanUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialSelectType, QianchuanUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus, QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfo, QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerProductInfoInner, QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerStatsInfo } from "../models/index";

export interface QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInner {
  audit_status?: QianchuanUniPromotionAdMaterialGetV10DataAdMaterialInfosAuditStatus;
  delivery_not_reason?: string[];
  is_delete?: boolean;
  material_info?: QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfo;
  material_select_type?: QianchuanUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialSelectType;
  material_status?: QianchuanUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus;
  product_info?: QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerProductInfoInner[];
  stats_info?: QianchuanUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerStatsInfo;
}

