// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_update_v1_0_multi_product_creative_list_video_material_image_mode.go
// Do not edit manually.

export const QianchuanUniAwemeAdUpdateV10MultiProductCreativeListVideoMaterialImageMode = {
  VIDEO_LARGE: "VIDEO_LARGE",
  VIDEO_VERTICAL: "VIDEO_VERTICAL",
} as const;

export type QianchuanUniAwemeAdUpdateV10MultiProductCreativeListVideoMaterialImageMode = typeof QianchuanUniAwemeAdUpdateV10MultiProductCreativeListVideoMaterialImageMode[keyof typeof QianchuanUniAwemeAdUpdateV10MultiProductCreativeListVideoMaterialImageMode];

