// Generated from oceanengine/ad_open_sdk_go models/model_creative_detail_get_v3_0_response_data_creative_list_inner_title_material.go
// Do not edit manually.

import type { CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterialBidwordListInner, CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterialDpaWordListInner, CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterialWordListInner } from "../models/index";

export interface CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterial {
  bidword_list?: CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterialBidwordListInner[];
  dpa_word_list?: CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterialDpaWordListInner[];
  title?: string;
  word_list?: CreativeDetailGetV30ResponseDataCreativeListInnerTitleMaterialWordListInner[];
}

