// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_create_v3_0_request_target_wallet_detail_list_inner_transfer_capital_detail_list_inner.go
// Do not edit manually.

import type { CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalSubType, CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalType, CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListPlatform } from "../models/index";

export interface CgTransferWalletTransferCreateV30RequestTargetWalletDetailListInnerTransferCapitalDetailListInner {
  capital_sub_type?: CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalSubType;
  capital_type: CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListCapitalType;
  platform: CgTransferWalletTransferCreateV30TargetWalletDetailListTransferCapitalDetailListPlatform;
  transfer_amount: number;
}

