// 由 oceanengine/ad_open_sdk_go models/model_creative_custom_creative_create_v2_request_creative_list_inner_abstract_materials_inner_text_abstract_info.go 生成
// 不要手动编辑。

import type { CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfoBidwordListInner, CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfoWordListInner } from "../models/index";

export interface CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfo {
  abstract_text: string;
  bidword_list?: CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfoBidwordListInner[];
  word_list?: CreativeCustomCreativeCreateV2RequestCreativeListInnerAbstractMaterialsInnerTextAbstractInfoWordListInner[];
}

