// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_report_uni_promotion_dimension_data_author_get_v1_0_filtering_smart_bid_type.go
// Do not edit manually.

export const QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringSmartBidType = {
  SMART_BID_CONSERVATIVE: "SMART_BID_CONSERVATIVE",
  SMART_BID_CUSTOM: "SMART_BID_CUSTOM",
} as const;

export type QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringSmartBidType = typeof QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringSmartBidType[keyof typeof QianchuanReportUniPromotionDimensionDataAuthorGetV10FilteringSmartBidType];

