// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_report_today_live_room_config_get_v1_0_response_data_custom_config_datas_inner.go
// Do not edit manually.

import type { QianchuanReportTodayLiveRoomConfigGetV10ResponseDataCustomConfigDatasInnerDimensionsInner, QianchuanReportTodayLiveRoomConfigGetV10ResponseDataCustomConfigDatasInnerMetricsInner } from "../models/index";

export interface QianchuanReportTodayLiveRoomConfigGetV10ResponseDataCustomConfigDatasInner {
  data_topic?: string;
  dimensions?: QianchuanReportTodayLiveRoomConfigGetV10ResponseDataCustomConfigDatasInnerDimensionsInner[];
  metrics?: QianchuanReportTodayLiveRoomConfigGetV10ResponseDataCustomConfigDatasInnerMetricsInner[];
}

