// Generated from oceanengine/ad_open_sdk_go models/model_tools_advertiser_diagnosis_suggestion_get_v3_0_data_suggestion_info_list_suggestion_type.go
// Do not edit manually.

export const ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSuggestionType = {
  SEVEN_DAYS_ROI_SUGGESTION: "SEVEN_DAYS_ROI_SUGGESTION",
} as const;

export type ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSuggestionType = typeof ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSuggestionType[keyof typeof ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSuggestionType];

