// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_update_v1_0_multi_product_creative_list_creative_setting_creative_auto_generate.go
// Do not edit manually.

export const QianchuanAdUpdateV10MultiProductCreativeListCreativeSettingCreativeAutoGenerate = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdUpdateV10MultiProductCreativeListCreativeSettingCreativeAutoGenerate = typeof QianchuanAdUpdateV10MultiProductCreativeListCreativeSettingCreativeAutoGenerate[keyof typeof QianchuanAdUpdateV10MultiProductCreativeListCreativeSettingCreativeAutoGenerate];

