// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_update_v3_0_procedural_material_video_material_list_image_mode.go 生成
// 不要手动编辑。

export const LocalPromotionUpdateV30ProceduralMaterialVideoMaterialListImageMode = {
  IMAGE_MODE_VIDEO: "IMAGE_MODE_VIDEO",
  IMAGE_MODE_VIDEO_VERTICAL: "IMAGE_MODE_VIDEO_VERTICAL",
} as const;

export type LocalPromotionUpdateV30ProceduralMaterialVideoMaterialListImageMode = typeof LocalPromotionUpdateV30ProceduralMaterialVideoMaterialListImageMode[keyof typeof LocalPromotionUpdateV30ProceduralMaterialVideoMaterialListImageMode];

