// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_multi_product_creative_list_video_material_image_mode.go
// Do not edit manually.

export const QianchuanUniAwemeAdCreateV10MultiProductCreativeListVideoMaterialImageMode = {
  VIDEO_LARGE: "VIDEO_LARGE",
  VIDEO_VERTICAL: "VIDEO_VERTICAL",
} as const;

export type QianchuanUniAwemeAdCreateV10MultiProductCreativeListVideoMaterialImageMode = typeof QianchuanUniAwemeAdCreateV10MultiProductCreativeListVideoMaterialImageMode[keyof typeof QianchuanUniAwemeAdCreateV10MultiProductCreativeListVideoMaterialImageMode];

