// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_report_custom_get_v1_0_data_topic.go
// Do not edit manually.

export const QianchuanReportCustomGetV10DataTopic = {
  ECP_BASIC_DATA: "ECP_BASIC_DATA",
  SITE_PROMOTION_POST_DATA_LIVE: "SITE_PROMOTION_POST_DATA_LIVE",
  SITE_PROMOTION_POST_DATA_OTHER: "SITE_PROMOTION_POST_DATA_OTHER",
  SITE_PROMOTION_POST_DATA_TITLE: "SITE_PROMOTION_POST_DATA_TITLE",
  SITE_PROMOTION_POST_DATA_VIDEO: "SITE_PROMOTION_POST_DATA_VIDEO",
  SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE: "SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE",
  SITE_PROMOTION_PRODUCT_POST_DATA_OTHER: "SITE_PROMOTION_PRODUCT_POST_DATA_OTHER",
  SITE_PROMOTION_PRODUCT_POST_DATA_TITLE: "SITE_PROMOTION_PRODUCT_POST_DATA_TITLE",
  SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO: "SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO",
} as const;

export type QianchuanReportCustomGetV10DataTopic = typeof QianchuanReportCustomGetV10DataTopic[keyof typeof QianchuanReportCustomGetV10DataTopic];

