// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_update_v1_0_delivery_setting_deep_external_action.go
// Do not edit manually.

export const QianchuanUniAwemeAdUpdateV10DeliverySettingDeepExternalAction = {
  AD_CONVERT_TYPE_LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI",
} as const;

export type QianchuanUniAwemeAdUpdateV10DeliverySettingDeepExternalAction = typeof QianchuanUniAwemeAdUpdateV10DeliverySettingDeepExternalAction[keyof typeof QianchuanUniAwemeAdUpdateV10DeliverySettingDeepExternalAction];

