// Generated from oceanengine/ad_open_sdk_go models/model_creative_get_v2_data_list_status.go
// Do not edit manually.

export const CreativeGetV2DataListStatus = {
  CREATIVE_STATUS_ADVERTISER_BUDGET_EXCEED: "CREATIVE_STATUS_ADVERTISER_BUDGET_EXCEED",
  CREATIVE_STATUS_ADVERTISER_PRE_OFFLINE_BUDGET: "CREATIVE_STATUS_ADVERTISER_PRE_OFFLINE_BUDGET",
  CREATIVE_STATUS_AD_AUDIT: "CREATIVE_STATUS_AD_AUDIT",
  CREATIVE_STATUS_AD_AUDIT_DENY: "CREATIVE_STATUS_AD_AUDIT_DENY",
  CREATIVE_STATUS_AD_DISABLE: "CREATIVE_STATUS_AD_DISABLE",
  CREATIVE_STATUS_AD_EXTERNAL_URL_DISABLE: "CREATIVE_STATUS_AD_EXTERNAL_URL_DISABLE",
  CREATIVE_STATUS_AD_PRE_OFFLINE_BUDGET: "CREATIVE_STATUS_AD_PRE_OFFLINE_BUDGET",
  CREATIVE_STATUS_AD_REAUDIT: "CREATIVE_STATUS_AD_REAUDIT",
  CREATIVE_STATUS_ALL: "CREATIVE_STATUS_ALL",
  CREATIVE_STATUS_AUDIT: "CREATIVE_STATUS_AUDIT",
  CREATIVE_STATUS_AUDIT_DENY: "CREATIVE_STATUS_AUDIT_DENY",
  CREATIVE_STATUS_AUTHORIZE_CANCEL: "CREATIVE_STATUS_AUTHORIZE_CANCEL",
  CREATIVE_STATUS_AWEME_ACCOUNT_DISABLED: "CREATIVE_STATUS_AWEME_ACCOUNT_DISABLED",
  CREATIVE_STATUS_AWEME_ANCHOR_DISABLED: "CREATIVE_STATUS_AWEME_ANCHOR_DISABLED",
  CREATIVE_STATUS_AWEME_ITEM_DISABLED: "CREATIVE_STATUS_AWEME_ITEM_DISABLED",
  CREATIVE_STATUS_BALANCE_EXCEED: "CREATIVE_STATUS_BALANCE_EXCEED",
  CREATIVE_STATUS_BUDGET_EXCEED: "CREATIVE_STATUS_BUDGET_EXCEED",
  CREATIVE_STATUS_CAMPAIGN_DISABLE: "CREATIVE_STATUS_CAMPAIGN_DISABLE",
  CREATIVE_STATUS_CAMPAIGN_EXCEED: "CREATIVE_STATUS_CAMPAIGN_EXCEED",
  CREATIVE_STATUS_CAN_NOT_EDIT: "CREATIVE_STATUS_CAN_NOT_EDIT",
  CREATIVE_STATUS_CAN_NOT_LAUNCH: "CREATIVE_STATUS_CAN_NOT_LAUNCH",
  CREATIVE_STATUS_CREATE: "CREATIVE_STATUS_CREATE",
  CREATIVE_STATUS_DATA_ERROR: "CREATIVE_STATUS_DATA_ERROR",
  CREATIVE_STATUS_DELETE: "CREATIVE_STATUS_DELETE",
  CREATIVE_STATUS_DELIVERY_OK: "CREATIVE_STATUS_DELIVERY_OK",
  CREATIVE_STATUS_DISABLE: "CREATIVE_STATUS_DISABLE",
  CREATIVE_STATUS_DONE: "CREATIVE_STATUS_DONE",
  CREATIVE_STATUS_FROZEN: "CREATIVE_STATUS_FROZEN",
  CREATIVE_STATUS_LIVE_ROOM_OFF: "CREATIVE_STATUS_LIVE_ROOM_OFF",
  CREATIVE_STATUS_NOT_START: "CREATIVE_STATUS_NOT_START",
  CREATIVE_STATUS_NO_DELIVERY: "CREATIVE_STATUS_NO_DELIVERY",
  CREATIVE_STATUS_NO_SCHEDULE: "CREATIVE_STATUS_NO_SCHEDULE",
  CREATIVE_STATUS_PRODUCT_OFFLINE: "CREATIVE_STATUS_PRODUCT_OFFLINE",
  CREATIVE_STATUS_REAUDIT: "CREATIVE_STATUS_REAUDIT",
} as const;

export type CreativeGetV2DataListStatus = typeof CreativeGetV2DataListStatus[keyof typeof CreativeGetV2DataListStatus];

