// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_report_uni_promotion_config_get_v1_0_response_data_custom_config_datas_inner.go
// Do not edit manually.

import type { QianchuanReportUniPromotionConfigGetV10DataCustomConfigDatasDataTopic, QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInnerDimensionsInner, QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInnerMetricsInner, QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInnerQueryLimit } from "../models/index";

export interface QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInner {
  data_topic?: QianchuanReportUniPromotionConfigGetV10DataCustomConfigDatasDataTopic;
  dimensions?: QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInnerDimensionsInner[];
  metrics?: QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInnerMetricsInner[];
  query_limit?: QianchuanReportUniPromotionConfigGetV10ResponseDataCustomConfigDatasInnerQueryLimit;
}

