// 由 oceanengine/ad_open_sdk_go models/model_dmp_data_source_read_v2_data_data_list_default_audience_delivery_status.go 生成
// 不要手动编辑。

export const DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus = {
  CUSTOM_AUDIENCE_DELIVERY_STATUS_AVAILABLE: "CUSTOM_AUDIENCE_DELIVERY_STATUS_AVAILABLE",
  CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUBLISH: "CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUBLISH",
  CUSTOM_AUDIENCE_DELIVERY_STATUS_UNAVAILABLE: "CUSTOM_AUDIENCE_DELIVERY_STATUS_UNAVAILABLE",
  CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUSH: "CUSTOM_AUDIENCE_DELIVERY_STATUS_NEED_PUSH",
} as const;

export type DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus = typeof DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus[keyof typeof DmpDataSourceReadV2DataDataListDefaultAudienceDeliveryStatus];

