// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_detail_v3_0_response_data_transfer_wallet_record_list_inner_transfer_capital_record_list_inner_capital_sub_detail_list_inner.go
// Do not edit manually.

import type { CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType, CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus } from "../models/index";

export interface CgTransferWalletTransferDetailV30ResponseDataTransferWalletRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner {
  capital_sub_type?: CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType;
  transfer_amount?: number;
  transfer_status?: CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus;
}

