// Generated from oceanengine/ad_open_sdk_go models/model_creative_get_v2_filtering_image_mode.go
// Do not edit manually.

export const CreativeGetV2FilteringImageMode = {
  CREATIVE_IMAGE_MODE_AWEME_LIVE: "CREATIVE_IMAGE_MODE_AWEME_LIVE",
  CREATIVE_IMAGE_MODE_CALIBRATION_FREE_SINGLE_IMAGE: "CREATIVE_IMAGE_MODE_CALIBRATION_FREE_SINGLE_IMAGE",
  CREATIVE_IMAGE_MODE_CALIBRATION_FREE_VIDEO: "CREATIVE_IMAGE_MODE_CALIBRATION_FREE_VIDEO",
  CREATIVE_IMAGE_MODE_DECORATION_COUPON: "CREATIVE_IMAGE_MODE_DECORATION_COUPON",
  CREATIVE_IMAGE_MODE_DIRECT_PLAYABLE: "CREATIVE_IMAGE_MODE_DIRECT_PLAYABLE",
  CREATIVE_IMAGE_MODE_DISPLAY_WINDOW: "CREATIVE_IMAGE_MODE_DISPLAY_WINDOW",
  CREATIVE_IMAGE_MODE_GIF: "CREATIVE_IMAGE_MODE_GIF",
  CREATIVE_IMAGE_MODE_GROUP: "CREATIVE_IMAGE_MODE_GROUP",
  CREATIVE_IMAGE_MODE_LARGE: "CREATIVE_IMAGE_MODE_LARGE",
  CREATIVE_IMAGE_MODE_LARGE_VERTICAL: "CREATIVE_IMAGE_MODE_LARGE_VERTICAL",
  CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL: "CREATIVE_IMAGE_MODE_PLAYABLE_HORIZONTAL",
  CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL: "CREATIVE_IMAGE_MODE_PLAYABLE_VERTICAL",
  CREATIVE_IMAGE_MODE_SMALL: "CREATIVE_IMAGE_MODE_SMALL",
  CREATIVE_IMAGE_MODE_UNION_SPLASH: "CREATIVE_IMAGE_MODE_UNION_SPLASH",
  CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO: "CREATIVE_IMAGE_MODE_UNION_SPLASH_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO: "CREATIVE_IMAGE_MODE_VIDEO",
  CREATIVE_IMAGE_MODE_VIDEO_VERTICAL: "CREATIVE_IMAGE_MODE_VIDEO_VERTICAL",
  INVALID_DATA: "INVALID_DATA",
  SEARCH_AD_SMALL_IMAGE: "SEARCH_AD_SMALL_IMAGE",
  TOUTIAO_SEARCH_AD_IMAGE: "TOUTIAO_SEARCH_AD_IMAGE",
} as const;

export type CreativeGetV2FilteringImageMode = typeof CreativeGetV2FilteringImageMode[keyof typeof CreativeGetV2FilteringImageMode];

