// Generated from oceanengine/ad_open_sdk_go models/model_creative_detail_get_v3_0_data_creative_list_video_material_dpa_video_template_type.go
// Do not edit manually.

export const CreativeDetailGetV30DataCreativeListVideoMaterialDpaVideoTemplateType = {
  DPA_VIDEO_TEMPLATE_CUSTOM: "DPA_VIDEO_TEMPLATE_CUSTOM",
  DPA_VIDEO_TEMPLATE_DEPRECATED: "DPA_VIDEO_TEMPLATE_DEPRECATED",
  DPA_VIDEO_TEMPLATE_SMART: "DPA_VIDEO_TEMPLATE_SMART",
} as const;

export type CreativeDetailGetV30DataCreativeListVideoMaterialDpaVideoTemplateType = typeof CreativeDetailGetV30DataCreativeListVideoMaterialDpaVideoTemplateType[keyof typeof CreativeDetailGetV30DataCreativeListVideoMaterialDpaVideoTemplateType];

