// Generated from oceanengine/ad_open_sdk_go models/model_report_creative_get_v2_filtering_status.go
// Do not edit manually.

export const ReportCreativeGetV2FilteringStatus = {
  CREATIVE_STATUS_ALL: "CREATIVE_STATUS_ALL",
  CREATIVE_STATUS_DELIVERY_OK: "CREATIVE_STATUS_DELIVERY_OK",
  CREATIVE_STATUS_AD_DISABLE: "CREATIVE_STATUS_AD_DISABLE",
  CREATIVE_STATUS_BALANCE_EXCEED: "CREATIVE_STATUS_BALANCE_EXCEED",
  CREATIVE_STATUS_AUDIT_DENY: "CREATIVE_STATUS_AUDIT_DENY",
  CREATIVE_STATUS_AD_AUDIT: "CREATIVE_STATUS_AD_AUDIT",
  CREATIVE_STATUS_AD_REAUDIT: "CREATIVE_STATUS_AD_REAUDIT",
  CREATIVE_STATUS_NO_SCHEDULE: "CREATIVE_STATUS_NO_SCHEDULE",
  CREATIVE_STATUS_AUDIT: "CREATIVE_STATUS_AUDIT",
  CREATIVE_STATUS_CAMPAIGN_EXCEED: "CREATIVE_STATUS_CAMPAIGN_EXCEED",
  CREATIVE_STATUS_REAUDIT: "CREATIVE_STATUS_REAUDIT",
  CREATIVE_STATUS_DONE: "CREATIVE_STATUS_DONE",
  CREATIVE_STATUS_AD_AUDIT_DENY: "CREATIVE_STATUS_AD_AUDIT_DENY",
  CREATIVE_STATUS_DISABLE: "CREATIVE_STATUS_DISABLE",
  CREATIVE_STATUS_NOT_START: "CREATIVE_STATUS_NOT_START",
  CREATIVE_STATUS_CAMPAIGN_DISABLE: "CREATIVE_STATUS_CAMPAIGN_DISABLE",
  CREATIVE_STATUS_NOT_DELETE: "CREATIVE_STATUS_NOT_DELETE",
  CREATIVE_STATUS_BUDGET_EXCEED: "CREATIVE_STATUS_BUDGET_EXCEED",
  CREATIVE_STATUS_DELETE: "CREATIVE_STATUS_DELETE",
} as const;

export type ReportCreativeGetV2FilteringStatus = typeof ReportCreativeGetV2FilteringStatus[keyof typeof ReportCreativeGetV2FilteringStatus];

