// Generated from oceanengine/ad_open_sdk_go models/model_tools_promotion_diagnosis_suggestion_get_v3_0_data_suggestion_list_scene_list_suggestions_tool_type.go
// Do not edit manually.

export const ToolsPromotionDiagnosisSuggestionGetV30DataSuggestionListSceneListSuggestionsToolType = {
  ACTION: "ACTION",
  TEXT: "TEXT",
} as const;

export type ToolsPromotionDiagnosisSuggestionGetV30DataSuggestionListSceneListSuggestionsToolType = typeof ToolsPromotionDiagnosisSuggestionGetV30DataSuggestionListSceneListSuggestionsToolType[keyof typeof ToolsPromotionDiagnosisSuggestionGetV30DataSuggestionListSceneListSuggestionsToolType];

