// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_update_v1_0_programmatic_creative_card_promotion_card_button_smart_optimization.go
// Do not edit manually.

export const QianchuanAdUpdateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdUpdateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization = typeof QianchuanAdUpdateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization[keyof typeof QianchuanAdUpdateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization];

