// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_material_get_v1_0_response_data_ad_material_infos_inner_material_info.go
// Do not edit manually.

import type { QianchuanMaterialGetV10DataAdMaterialInfosMaterialInfoMaterialType, QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoImageMaterial, QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoRoomMaterial, QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoTitleMaterial, QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoVideoMaterial } from "../models/index";

export interface QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfo {
  image_material?: QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoImageMaterial;
  material_type: QianchuanMaterialGetV10DataAdMaterialInfosMaterialInfoMaterialType;
  room_material?: QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoRoomMaterial;
  title_material?: QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoTitleMaterial;
  video_material?: QianchuanMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoVideoMaterial;
}

