// 由 oceanengine/ad_open_sdk_go models/model_shared_wallet_wallet_balance_get_v3_0_response_data_shared_wallet_balance_info_value.go 生成
// 不要手动编辑。

import type { SharedWalletWalletBalanceGetV30ResponseDataSharedWalletBalanceInfoValueBasicBalanceInfo, SharedWalletWalletBalanceGetV30ResponseDataSharedWalletBalanceInfoValueGeneralBalanceInfo } from "../models/index";

export interface SharedWalletWalletBalanceGetV30ResponseDataSharedWalletBalanceInfoValue {
  basic_balance_info?: SharedWalletWalletBalanceGetV30ResponseDataSharedWalletBalanceInfoValueBasicBalanceInfo;
  general_balance_info?: SharedWalletWalletBalanceGetV30ResponseDataSharedWalletBalanceInfoValueGeneralBalanceInfo;
  wallet_id?: number | string;
}

