// Generated from oceanengine/ad_open_sdk_go models/model_promotion_create_v3_0_promotion_related_product_video_material_list_video_hp_visibility.go
// Do not edit manually.

export const PromotionCreateV30PromotionRelatedProductVideoMaterialListVideoHpVisibility = {
  ALWAYS_VISIBLE: "ALWAYS_VISIBLE",
  HIDE_VIDEO_ON_HP: "HIDE_VIDEO_ON_HP",
} as const;

export type PromotionCreateV30PromotionRelatedProductVideoMaterialListVideoHpVisibility = typeof PromotionCreateV30PromotionRelatedProductVideoMaterialListVideoHpVisibility[keyof typeof PromotionCreateV30PromotionRelatedProductVideoMaterialListVideoHpVisibility];

