// 由 oceanengine/ad_open_sdk_go models/model_oc_project_std_project_tools_get_v3_0_data_project_adjust_info_material_adjust_info_material_adjust_type.go 生成
// 不要手动编辑。

export const OcProjectStdProjectToolsGetV30DataProjectAdjustInfoMaterialAdjustInfoMaterialAdjustType = {
  LIVE_MATERIALS: "LIVE_MATERIALS",
  PROJECT_MATERIALS: "PROJECT_MATERIALS",
  SPECIFY_MATERIALS: "SPECIFY_MATERIALS",
} as const;

export type OcProjectStdProjectToolsGetV30DataProjectAdjustInfoMaterialAdjustInfoMaterialAdjustType = typeof OcProjectStdProjectToolsGetV30DataProjectAdjustInfoMaterialAdjustInfoMaterialAdjustType[keyof typeof OcProjectStdProjectToolsGetV30DataProjectAdjustInfoMaterialAdjustInfoMaterialAdjustType];

