// Generated from oceanengine/ad_open_sdk_go models/model_agent_query_risk_promotion_list_v2_data_data_promotion_status.go
// Do not edit manually.

export const AgentQueryRiskPromotionListV2DataDataPromotionStatus = {
  ADV_OFFLINE_BUDGET: "ADV_OFFLINE_BUDGET",
  ADV_PRE_OFFLINE_BUDGET: "ADV_PRE_OFFLINE_BUDGET",
  AUDIT: "AUDIT",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  AWEME_ANCHOR_DISABLED: "AWEME_ANCHOR_DISABLED",
  CREATE: "CREATE",
  DELETE: "DELETE",
  DELIVERY_OK: "DELIVERY_OK",
  ERROR_DEFAULT: "ERROR_DEFAULT",
  FROZEN: "FROZEN",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NO_SCHEDULE: "NO_SCHEDULE",
  OFFLINE_AUDIT: "OFFLINE_AUDIT",
  PRE_ONLINE: "PRE_ONLINE",
  PRODUCT_OFFLINE: "PRODUCT_OFFLINE",
  PROJECT_DISABLE: "PROJECT_DISABLE",
  PROJECT_OFFLINE_BUDGET: "PROJECT_OFFLINE_BUDGET",
  PROJECT_PRE_OFFLINE_BUDGET: "PROJECT_PRE_OFFLINE_BUDGET",
  PROMOTION_DISABLE: "PROMOTION_DISABLE",
  PROMOTION_OFFLINE_BALANCE: "PROMOTION_OFFLINE_BALANCE",
  PROMOTION_OFFLINE_BUDGET: "PROMOTION_OFFLINE_BUDGET",
  PROMOTION_PRE_OFFLINE_BUDGET: "PROMOTION_PRE_OFFLINE_BUDGET",
  PROMOTION_QUOTA_LIMIT: "PROMOTION_QUOTA_LIMIT",
  RE_AUDIT: "RE_AUDIT",
  TIME_DONE: "TIME_DONE",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type AgentQueryRiskPromotionListV2DataDataPromotionStatus = typeof AgentQueryRiskPromotionListV2DataDataPromotionStatus[keyof typeof AgentQueryRiskPromotionListV2DataDataPromotionStatus];

