// 由 oceanengine/ad_open_sdk_go models/model_cg_transfer_query_transfer_detail_v3_0_data_transfer_target_record_list_transfer_capital_record_list_capital_sub_detail_list_capital_sub_type.go 生成
// 不要手动编辑。

export const CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = {
  NORMAL: "NORMAL",
  PRELOAN: "PRELOAN",
} as const;

export type CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType = typeof CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType[keyof typeof CgTransferQueryTransferDetailV30DataTransferTargetRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType];

