// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_material_get_v1_0_response_data_ad_material_infos_inner_material_info.go
// Do not edit manually.

import type { QianchuanAdMaterialGetV10DataAdMaterialInfosMaterialInfoMaterialType, QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoImageMaterial, QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoRoomMaterial, QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoTitleMaterial, QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoVideoMaterial } from "../models/index";

export interface QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfo {
  image_material?: QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoImageMaterial;
  material_type: QianchuanAdMaterialGetV10DataAdMaterialInfosMaterialInfoMaterialType;
  room_material?: QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoRoomMaterial;
  title_material?: QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoTitleMaterial;
  video_material?: QianchuanAdMaterialGetV10ResponseDataAdMaterialInfosInnerMaterialInfoVideoMaterial;
}

