// Generated from oceanengine/ad_open_sdk_go models/model_brand_material_update_v3_0_request_material_list_inner_material_component.go
// Do not edit manually.

import type { BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAvatarIcon, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeAnchor, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeShopHomePage, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeVideo, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentBusinessUrl, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternal, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentDeliveryTimeList, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTime, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExternalTitle, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentFeedButtonText, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentIesCoreUser, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentImageCard, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentLbsExternal, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentMallActivityPage, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentMusicText, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentProductDetailPage, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentSearch, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentVideoComment, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentVideoDownload } from "../models/index";

export interface BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponent {
  avatar_icon?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAvatarIcon;
  aweme_anchor?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeAnchor;
  aweme_shop_home_page?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeShopHomePage;
  aweme_video?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentAwemeVideo;
  business_url?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentBusinessUrl;
  common_external?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternal;
  delivery_time_list?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentDeliveryTimeList;
  explore_one_time?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExploreOneTime;
  external_title?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentExternalTitle;
  feed_button_text?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentFeedButtonText;
  ies_core_user?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentIesCoreUser;
  image_card?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentImageCard;
  lbs_external?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentLbsExternal;
  mall_activity_page?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentMallActivityPage;
  music_text?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentMusicText;
  product_detail_page?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentProductDetailPage;
  search?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentSearch;
  video_comment?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentVideoComment;
  video_download?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentVideoDownload;
}

