// 由 oceanengine/ad_open_sdk_go models/model_promotion_create_v3_0_request_promotion_materials_image_material_list_inner.go 生成
// 不要手动编辑。

import type { PromotionCreateV30PromotionMaterialsImageMaterialListImageMode, PromotionCreateV30RequestPromotionMaterialsImageMaterialListInnerImagesInner } from "../models/index";

export interface PromotionCreateV30RequestPromotionMaterialsImageMaterialListInner {
  image_mode: PromotionCreateV30PromotionMaterialsImageMaterialListImageMode;
  images: PromotionCreateV30RequestPromotionMaterialsImageMaterialListInnerImagesInner[];
}

