// Generated from oceanengine/ad_open_sdk_go models/model_local_promotion_reject_reason_get_v3_0_response_data_list_inner_material_reject_inner.go
// Do not edit manually.

import type { LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform, LocalPromotionRejectReasonGetV30DataListMaterialRejectType, LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner, LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial } from "../models/index";

export interface LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInner {
  audit_platform?: LocalPromotionRejectReasonGetV30DataListMaterialRejectAuditPlatform;
  content?: string;
  image_material?: LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerImageMaterialInner[];
  reject_reason?: string[];
  suggestion?: string[];
  type?: LocalPromotionRejectReasonGetV30DataListMaterialRejectType;
  video_material?: LocalPromotionRejectReasonGetV30ResponseDataListInnerMaterialRejectInnerVideoMaterial;
}

