// Generated from oceanengine/ad_open_sdk_go models/model_tools_site_template_create_v2_response_data_bricks_inner_button_download_event.go
// Do not edit manually.

import type { ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventAndroidLink, ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventIosLink } from "../models/index";

export interface ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEvent {
  android_link?: ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventAndroidLink;
  ios_link?: ToolsSiteTemplateCreateV2ResponseDataBricksInnerButtonDownloadEventIosLink;
}

