// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_list_v1_0_data_ad_list_ad_info_status.go
// Do not edit manually.

export const QianchuanUniPromotionListV10DataAdListAdInfoStatus = {
  ADVERTISER_OFFLINE_BUDGET: "ADVERTISER_OFFLINE_BUDGET",
  ADVERTISER_PRE_OFFLINE_BUDGET: "ADVERTISER_PRE_OFFLINE_BUDGET",
  AUDIT: "AUDIT",
  AUDIT_STATUS_ERROR: "AUDIT_STATUS_ERROR",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  CAMPAIGN_DISABLE: "CAMPAIGN_DISABLE",
  CAMPAIGN_OFFLINE_BUDGET: "CAMPAIGN_OFFLINE_BUDGET",
  CAMPAIGN_PRE_OFFLINE_BUDGET: "CAMPAIGN_PRE_OFFLINE_BUDGET",
  CREATE: "CREATE",
  DAILY_DELIVERY_SECONDS_DONE: "DAILY_DELIVERY_SECONDS_DONE",
  DELETE: "DELETE",
  DELIVERY_OK: "DELIVERY_OK",
  DISABLE: "DISABLE",
  DRAFT: "DRAFT",
  ERROR: "ERROR",
  EXTERNAL_URL_DISABLE: "EXTERNAL_URL_DISABLE",
  FROZEN: "FROZEN",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NO_SCHEDULE: "NO_SCHEDULE",
  OFFLINE_AUDIT: "OFFLINE_AUDIT",
  OFFLINE_BALANCE: "OFFLINE_BALANCE",
  OFFLINE_BUDGET: "OFFLINE_BUDGET",
  OFFLINE_SHARED_WALLET_BALANCE: "OFFLINE_SHARED_WALLET_BALANCE",
  PRE_OFFLINE_BUDGET: "PRE_OFFLINE_BUDGET",
  PRE_ONLINE: "PRE_ONLINE",
  QUOTA_DISABLE: "QUOTA_DISABLE",
  REAUDIT: "REAUDIT",
  ROI2_DISABLE: "ROI2_DISABLE",
  SYSTEM_DISABLE: "SYSTEM_DISABLE",
  TIME_DONE: "TIME_DONE",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type QianchuanUniPromotionListV10DataAdListAdInfoStatus = typeof QianchuanUniPromotionListV10DataAdListAdInfoStatus[keyof typeof QianchuanUniPromotionListV10DataAdListAdInfoStatus];

