// 由 oceanengine/ad_open_sdk_go models/model_advertiser_info_v2_data_role.go 生成
// 不要手动编辑。

export const AdvertiserInfoV2DataRole = {
  ROLE_CHILD_ADVERTISER: "ROLE_CHILD_ADVERTISER",
  ROLE_LOCAL_LIFE_ADVERTISER: "ROLE_LOCAL_LIFE_ADVERTISER",
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_AGENT_SYSTEM_ACCOUNT: "ROLE_AGENT_SYSTEM_ACCOUNT",
  ROLE_PGC_ADVERTISER: "ROLE_PGC_ADVERTISER",
  ROLE_ADVERTISER_SYSTEM_ACCOUNT: "ROLE_ADVERTISER_SYSTEM_ACCOUNT",
  ROLE_DOUDIAN_ADVERTISER: "ROLE_DOUDIAN_ADVERTISER",
  ROLE_AGENT: "ROLE_AGENT",
  ROLE_ADVERTISER_ABSTRACT: "ROLE_ADVERTISER_ABSTRACT",
  ROLE_CHILD_AGENT: "ROLE_CHILD_AGENT",
  ROLE_ECP_CHILD_ADVERTISER: "ROLE_ECP_CHILD_ADVERTISER",
  ROLE_INTERNAL_ADV: "ROLE_INTERNAL_ADV",
  ROLE_AGENT_ABSTRACT: "ROLE_AGENT_ABSTRACT",
  ROLE_LOCAL_LIFE_INTERNAL_ADVERTISER: "ROLE_LOCAL_LIFE_INTERNAL_ADVERTISER",
  ROLE_DSP_ADVERTISER: "ROLE_DSP_ADVERTISER",
  ROLE_LITE_ADVERTISER: "ROLE_LITE_ADVERTISER",
  ROLE_MAJORDOMO: "ROLE_MAJORDOMO",
  ROLE_ECP_INTERNAL_ADVERTISER: "ROLE_ECP_INTERNAL_ADVERTISER",
  ROLE_LOCAL_LIFE_VIRTUAL_ADVERTISER: "ROLE_LOCAL_LIFE_VIRTUAL_ADVERTISER",
  ROLE_AWEME_PROMOTION_ADVERTISER: "ROLE_AWEME_PROMOTION_ADVERTISER",
  ROLE_ADVERTISER: "ROLE_ADVERTISER",
  ROLE_HOTSOON_ADVERTISER: "ROLE_HOTSOON_ADVERTISER",
  ROLE_HOTSOON_PROMOTION_ADVERTISER: "ROLE_HOTSOON_PROMOTION_ADVERTISER",
  ROLE_ECP_ADVERTISER: "ROLE_ECP_ADVERTISER",
} as const;

export type AdvertiserInfoV2DataRole = typeof AdvertiserInfoV2DataRole[keyof typeof AdvertiserInfoV2DataRole];

