// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_delivery_setting_deep_external_action.go 生成
// 不要手动编辑。

export const QianchuanUniAwemeAdCreateV10DeliverySettingDeepExternalAction = {
  AD_CONVERT_TYPE_LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PURE_PAY_ROI",
} as const;

export type QianchuanUniAwemeAdCreateV10DeliverySettingDeepExternalAction = typeof QianchuanUniAwemeAdCreateV10DeliverySettingDeepExternalAction[keyof typeof QianchuanUniAwemeAdCreateV10DeliverySettingDeepExternalAction];

