// Generated from oceanengine/ad_open_sdk_go models/model_creative_detail_get_v3_0_response_data_creative_image_materials_inner.go
// Do not edit manually.

import type { CreativeDetailGetV30DataCreativeImageMaterialsImageMode, CreativeDetailGetV30ResponseDataCreativeImageMaterialsInnerImageInfoInner, CreativeDetailGetV30ResponseDataCreativeImageMaterialsInnerTemplateImage } from "../models/index";

export interface CreativeDetailGetV30ResponseDataCreativeImageMaterialsInner {
  image_info?: CreativeDetailGetV30ResponseDataCreativeImageMaterialsInnerImageInfoInner[];
  image_mode?: CreativeDetailGetV30DataCreativeImageMaterialsImageMode;
  template_image?: CreativeDetailGetV30ResponseDataCreativeImageMaterialsInnerTemplateImage;
}

