// 由 oceanengine/ad_open_sdk_go models/model_tools_site_create_v2_request_bricks_inner_events_inner_behavior.go 生成
// 不要手动编辑。

import type { ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorAndroidLink, ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorIosLink, ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorLink, ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorSmartPhone } from "../models/index";

export interface ToolsSiteCreateV2RequestBricksInnerEventsInnerBehavior {
  android_link?: ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorAndroidLink;
  ios_link?: ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorIosLink;
  link?: ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorLink;
  name?: string;
  smart_phone?: ToolsSiteCreateV2RequestBricksInnerEventsInnerBehaviorSmartPhone;
}

