// Generated from oceanengine/ad_open_sdk_go models/model_brand_creative_get_v3_0_response_data_creatives_inner_creative_creative_info.go
// Do not edit manually.

import type { BrandCreativeGetV30DataCreativesCreativeCreativeInfoCreativeType, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoGroupImage, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoHorizontalImageVideo, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoHorizontalVideo, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoLargeImage, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoSmallImage, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVariableImageVideo, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideo, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalVideo, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVideoCreative } from "../models/index";

export interface BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfo {
  creative_type?: BrandCreativeGetV30DataCreativesCreativeCreativeInfoCreativeType;
  group_image?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoGroupImage;
  horizontal_image_video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoHorizontalImageVideo;
  horizontal_video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoHorizontalVideo;
  large_image?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoLargeImage;
  small_image?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoSmallImage;
  variable_image_video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVariableImageVideo;
  vertical_image_video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideo;
  vertical_video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalVideo;
  video_creative?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVideoCreative;
}

