// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_request_multi_product_creative_list_inner_title_material_inner.go 生成
// 不要手动编辑。

import type { QianchuanUniAwemeAdCreateV10MultiProductCreativeListTitleMaterialTitleType, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerTitleMaterialInnerDynamicWordsInner } from "../models/index";

export interface QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerTitleMaterialInner {
  dynamic_words?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerTitleMaterialInnerDynamicWordsInner[];
  title: string;
  title_type?: QianchuanUniAwemeAdCreateV10MultiProductCreativeListTitleMaterialTitleType;
}

