// 由 oceanengine/ad_open_sdk_go models/model_shared_wallet_wallet_info_get_v3_0_data_wallet_info_main_wallet_info_main_shared_range_items_account_platform.go 生成
// 不要手动编辑。

export const SharedWalletWalletInfoGetV30DataWalletInfoMainWalletInfoMainSharedRangeItemsAccountPlatform = {
  AD: "AD",
  ECP: "ECP",
  LOCAL_ADS: "LOCAL_ADS",
} as const;

export type SharedWalletWalletInfoGetV30DataWalletInfoMainWalletInfoMainSharedRangeItemsAccountPlatform = typeof SharedWalletWalletInfoGetV30DataWalletInfoMainWalletInfoMainSharedRangeItemsAccountPlatform[keyof typeof SharedWalletWalletInfoGetV30DataWalletInfoMainWalletInfoMainSharedRangeItemsAccountPlatform];

