// Generated from oceanengine/ad_open_sdk_go models/model_brand_creative_get_v3_0_response_data_creatives_inner_creative_creative_info_vertical_image_video.go
// Do not edit manually.

import type { BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideoImage, BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideoVideo } from "../models/index";

export interface BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideo {
  image?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideoImage;
  title?: string;
  video?: BrandCreativeGetV30ResponseDataCreativesInnerCreativeCreativeInfoVerticalImageVideoVideo;
}

