// Generated from oceanengine/ad_open_sdk_go models/model_tools_app_management_bp_share_v2_response_data_error_list_inner.go
// Do not edit manually.

import type { ToolsAppManagementBpShareV2DataErrorListShareMode, ToolsAppManagementBpShareV2ResponseDataErrorListInnerAccountInfo, ToolsAppManagementBpShareV2ResponseDataErrorListInnerAllAccount, ToolsAppManagementBpShareV2ResponseDataErrorListInnerAllAccountByCompany } from "../models/index";

export interface ToolsAppManagementBpShareV2ResponseDataErrorListInner {
  account_info?: ToolsAppManagementBpShareV2ResponseDataErrorListInnerAccountInfo;
  all_account?: ToolsAppManagementBpShareV2ResponseDataErrorListInnerAllAccount;
  all_account_by_company?: ToolsAppManagementBpShareV2ResponseDataErrorListInnerAllAccountByCompany;
  error_message?: string;
  share_mode?: ToolsAppManagementBpShareV2DataErrorListShareMode;
}

