// Generated from oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_data_list_promotion_related_product_image_material_list_images_material_opt_status.go
// Do not edit manually.

export const PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialOptStatus = {
  DISABLE: "DISABLE",
  ENABLE: "ENABLE",
  MATERIAL_STATUS_QUEUING: "MATERIAL_STATUS_QUEUING",
} as const;

export type PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialOptStatus = typeof PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialOptStatus[keyof typeof PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialOptStatus];

