// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_material_add_v1_0_request_programmatic_creative_media_list_title_material_inner.go 生成
// 不要手动编辑。

export interface QianchuanUniPromotionAdMaterialAddV10RequestProgrammaticCreativeMediaListTitleMaterialInner {
  title: string;
}

