// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_request_multi_product_creative_list_inner.go
// Do not edit manually.

import type { QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeType, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerBlockVideoMaterialInner, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerCarouselMaterialInner, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerCreativeCard, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerImageMaterialInner, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerTitleMaterialInner, QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerVideoMaterialInner } from "../models/index";

export interface QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInner {
  block_video_material?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerBlockVideoMaterialInner[];
  carousel_material?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerCarouselMaterialInner[];
  creative_card?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerCreativeCard;
  creative_type?: QianchuanUniAwemeAdCreateV10MultiProductCreativeListCreativeType;
  hide_in_aweme?: boolean;
  image_material?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerImageMaterialInner[];
  product_id?: number | string;
  title_material?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerTitleMaterialInner[];
  video_material?: QianchuanUniAwemeAdCreateV10RequestMultiProductCreativeListInnerVideoMaterialInner[];
}

