// 由 oceanengine/ad_open_sdk_go models/model_creative_custom_creative_update_v2_request_creative_list_inner_image_materials_inner_template_image_template_data_list_inner.go 生成
// 不要手动编辑。

export interface CreativeCustomCreativeUpdateV2RequestCreativeListInnerImageMaterialsInnerTemplateImageTemplateDataListInner {
  background_image_id?: string;
}

