// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_transfer_detail_get_v3_0_data_transfer_target_record_list_transfer_capital_record_list_transfer_status.go
// Do not edit manually.

export const CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListTransferStatus = {
  NO_TRANSFER: "NO_TRANSFER",
  TRANSFER_FAILED: "TRANSFER_FAILED",
  TRANSFER_ING: "TRANSFER_ING",
  TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
} as const;

export type CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListTransferStatus = typeof CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListTransferStatus[keyof typeof CgTransferTransferDetailGetV30DataTransferTargetRecordListTransferCapitalRecordListTransferStatus];

