// Generated from oceanengine/ad_open_sdk_go models/model_brand_material_update_v3_0_request_material_list_inner_material_component_common_external.go
// Do not edit manually.

import type { BrandMaterialUpdateV30MaterialListMaterialComponentCommonExternalMicroAppOpenUrlType, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternalMicroAppInfo, BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternalWechatMicroAppInfo } from "../models/index";

export interface BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternal {
  external_url?: string;
  external_url_is_download?: number;
  micro_app_info?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternalMicroAppInfo;
  micro_app_open_url_type?: BrandMaterialUpdateV30MaterialListMaterialComponentCommonExternalMicroAppOpenUrlType;
  open_url?: string;
  wechat_micro_app_info?: BrandMaterialUpdateV30RequestMaterialListInnerMaterialComponentCommonExternalWechatMicroAppInfo;
}

