// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_detail_v1_0_response_data_multi_product_creative_list_inner.go
// Do not edit manually.

import type { QianchuanUniPromotionAdDetailV10DataMultiProductCreativeListCreativeType, QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerBlockMaterialInner, QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerCarouselMaterialInner, QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerCreativeCard, QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerImageMaterialInner, QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerTitleMaterialInner, QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerVideoMaterialInner } from "../models/index";

export interface QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInner {
  block_material?: QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerBlockMaterialInner[];
  carousel_material?: QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerCarouselMaterialInner[];
  creative_card?: QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerCreativeCard;
  creative_type?: QianchuanUniPromotionAdDetailV10DataMultiProductCreativeListCreativeType;
  hide_in_aweme?: boolean;
  image_material?: QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerImageMaterialInner[];
  product_id?: number | string;
  title_material?: QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerTitleMaterialInner[];
  video_material?: QianchuanUniPromotionAdDetailV10ResponseDataMultiProductCreativeListInnerVideoMaterialInner[];
}

