// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_aweme_order_detail_get_v1_0_data_delivery_setting_external_action.go
// Do not edit manually.

export const QianchuanAwemeOrderDetailGetV10DataDeliverySettingExternalAction = {
  AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  AD_CONVERT_TYPE_LIVE_COMMENT_ACTION: "AD_CONVERT_TYPE_LIVE_COMMENT_ACTION",
  AD_CONVERT_TYPE_LIVE_EFFECTIVE_EFFECTIVE_VIEW: "AD_CONVERT_TYPE_LIVE_EFFECTIVE_EFFECTIVE_VIEW",
  AD_CONVERT_TYPE_LIVE_ENTER_ACTION: "AD_CONVERT_TYPE_LIVE_ENTER_ACTION",
  AD_CONVERT_TYPE_LIVE_HEAT: "AD_CONVERT_TYPE_LIVE_HEAT",
  AD_CONVERT_TYPE_LIVE_ROI: "AD_CONVERT_TYPE_LIVE_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  AD_CONVERT_TYPE_NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  AD_CONVERT_TYPE_SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
} as const;

export type QianchuanAwemeOrderDetailGetV10DataDeliverySettingExternalAction = typeof QianchuanAwemeOrderDetailGetV10DataDeliverySettingExternalAction[keyof typeof QianchuanAwemeOrderDetailGetV10DataDeliverySettingExternalAction];

