// 由 oceanengine/ad_open_sdk_go models/model_local_audience_package_get_v3_0_response_data_audience_packages_inner.go 生成
// 不要手动编辑。

import type { LocalAudiencePackageGetV30DataAudiencePackagesAge, LocalAudiencePackageGetV30DataAudiencePackagesConvertedTimeDuration, LocalAudiencePackageGetV30DataAudiencePackagesCustomizedInterestAction, LocalAudiencePackageGetV30DataAudiencePackagesDistrict, LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeAbnormalActive, LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeFansCount, LocalAudiencePackageGetV30DataAudiencePackagesGender, LocalAudiencePackageGetV30DataAudiencePackagesHideIfConverted, LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerActionConfig, LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerCustomArea, LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerInterestConfig, LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerPoiAround, LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerRegion } from "../models/index";

export interface LocalAudiencePackageGetV30ResponseDataAudiencePackagesInner {
  action_config?: LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerActionConfig;
  age?: LocalAudiencePackageGetV30DataAudiencePackagesAge[];
  audience_package_id?: number | string;
  converted_time_duration?: LocalAudiencePackageGetV30DataAudiencePackagesConvertedTimeDuration;
  custom_area?: LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerCustomArea;
  customized_interest_action?: LocalAudiencePackageGetV30DataAudiencePackagesCustomizedInterestAction;
  description?: string;
  district?: LocalAudiencePackageGetV30DataAudiencePackagesDistrict;
  filter_aweme_abnormal_active?: LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeAbnormalActive;
  filter_aweme_fans_count?: LocalAudiencePackageGetV30DataAudiencePackagesFilterAwemeFansCount;
  gender?: LocalAudiencePackageGetV30DataAudiencePackagesGender;
  hide_if_converted?: LocalAudiencePackageGetV30DataAudiencePackagesHideIfConverted;
  interest_config?: LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerInterestConfig;
  name?: string;
  poi_around?: LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerPoiAround;
  region?: LocalAudiencePackageGetV30ResponseDataAudiencePackagesInnerRegion;
  retargeting_tags?: number[];
  retargeting_tags_exclude?: number[];
}

