// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_request_multi_product_creative_list_inner_programmatic_creative_programmatic_creative_title_list_inner.go
// Do not edit manually.

import type { QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType, QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeTitleListInnerDynamicWordsInner } from "../models/index";

export interface QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeTitleListInner {
  aweme_carousel_id?: number | string;
  dynamic_words?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeTitleListInnerDynamicWordsInner[];
  title: string;
  title_type?: QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType;
}

