// 由 oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_response_data_list_inner_promotion_materials_text_abstract_list_inner_bidword_list_inner.go 生成
// 不要手动编辑。

export interface PromotionListV30ResponseDataListInnerPromotionMaterialsTextAbstractListInnerBidwordListInner {
  default_word?: string;
}

