// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_detail_v3_0_response_data_transfer_wallet_record_list_inner_transfer_capital_record_list_inner.go
// Do not edit manually.

import type { CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalType, CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListPlatform, CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListTransferStatus, CgTransferWalletTransferDetailV30ResponseDataTransferWalletRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner } from "../models/index";

export interface CgTransferWalletTransferDetailV30ResponseDataTransferWalletRecordListInnerTransferCapitalRecordListInner {
  capital_sub_detail_list?: CgTransferWalletTransferDetailV30ResponseDataTransferWalletRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner[];
  capital_type?: CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListCapitalType;
  fail_reason?: string;
  platform?: CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListPlatform;
  transfer_amount?: number;
  transfer_status?: CgTransferWalletTransferDetailV30DataTransferWalletRecordListTransferCapitalRecordListTransferStatus;
}

