// Generated from oceanengine/ad_open_sdk_go models/model_dmp_custom_audience_select_v2_data_custom_audience_list_source.go
// Do not edit manually.

export const DmpCustomAudienceSelectV2DataCustomAudienceListSource = {
  CUSTOM_AUDIENCE_TYPE_BRAND: "CUSTOM_AUDIENCE_TYPE_BRAND",
  CUSTOM_AUDIENCE_TYPE_DATA_SOURCE: "CUSTOM_AUDIENCE_TYPE_DATA_SOURCE",
  CUSTOM_AUDIENCE_TYPE_DOU_PLUS: "CUSTOM_AUDIENCE_TYPE_DOU_PLUS",
  CUSTOM_AUDIENCE_TYPE_EXTEND: "CUSTOM_AUDIENCE_TYPE_EXTEND",
  CUSTOM_AUDIENCE_TYPE_FINANCE: "CUSTOM_AUDIENCE_TYPE_FINANCE",
  CUSTOM_AUDIENCE_TYPE_FRIEND: "CUSTOM_AUDIENCE_TYPE_FRIEND",
  CUSTOM_AUDIENCE_TYPE_ONE_KEY: "CUSTOM_AUDIENCE_TYPE_ONE_KEY",
  CUSTOM_AUDIENCE_TYPE_OPERATE: "CUSTOM_AUDIENCE_TYPE_OPERATE",
  CUSTOM_AUDIENCE_TYPE_PACK_RULE: "CUSTOM_AUDIENCE_TYPE_PACK_RULE",
  CUSTOM_AUDIENCE_TYPE_RULE: "CUSTOM_AUDIENCE_TYPE_RULE",
  CUSTOM_AUDIENCE_TYPE_THEME: "CUSTOM_AUDIENCE_TYPE_THEME",
  CUSTOM_AUDIENCE_TYPE_THIRD_PARTY: "CUSTOM_AUDIENCE_TYPE_THIRD_PARTY",
  CUSTOM_AUDIENCE_TYPE_UPLOAD: "CUSTOM_AUDIENCE_TYPE_UPLOAD",
} as const;

export type DmpCustomAudienceSelectV2DataCustomAudienceListSource = typeof DmpCustomAudienceSelectV2DataCustomAudienceListSource[keyof typeof DmpCustomAudienceSelectV2DataCustomAudienceListSource];

