// Generated from oceanengine/ad_open_sdk_go models/model_tools_advertiser_diagnosis_suggestion_get_v3_0_data_suggestion_info_list_seven_days_roi_suggestion_package_suggestion_adjust_info_delivery_optimization_type.go
// Do not edit manually.

export const ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType = {
  OPTIMIZE_COST_EFFECT_UP_COST: "OPTIMIZE_COST_EFFECT_UP_COST",
  OPTIMIZE_COST_EFFECT_UP_ROI: "OPTIMIZE_COST_EFFECT_UP_ROI",
  OPTIMIZE_COST_EFFECT_UP_ROI_STABLE_COST: "OPTIMIZE_COST_EFFECT_UP_ROI_STABLE_COST",
  OPTIMIZE_COST_EFFECT_DOWN_COST: "OPTIMIZE_COST_EFFECT_DOWN_COST",
} as const;

export type ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType = typeof ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType[keyof typeof ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType];

