// 由 oceanengine/ad_open_sdk_go models/model_advertiser_delivery_pkg_submit_v3_0_request_delivery_pkg_unnecessary_combines_inner_delivery_rules_inner.go 生成
// 不要手动编辑。

import type { AdvertiserDeliveryPkgSubmitV30RequestDeliveryPkgUnnecessaryCombinesInnerDeliveryRulesInnerDeliveriesInner } from "../models/index";

export interface AdvertiserDeliveryPkgSubmitV30RequestDeliveryPkgUnnecessaryCombinesInnerDeliveryRulesInner {
  deliveries: AdvertiserDeliveryPkgSubmitV30RequestDeliveryPkgUnnecessaryCombinesInnerDeliveryRulesInnerDeliveriesInner[];
  rule_id: number | string;
}

