// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_update_v1_0_multi_product_creative_list_creative_type.go
// Do not edit manually.

export const QianchuanUniAwemeAdUpdateV10MultiProductCreativeListCreativeType = {
  PROGRAMMATIC_CREATIVE: "PROGRAMMATIC_CREATIVE",
} as const;

export type QianchuanUniAwemeAdUpdateV10MultiProductCreativeListCreativeType = typeof QianchuanUniAwemeAdUpdateV10MultiProductCreativeListCreativeType[keyof typeof QianchuanUniAwemeAdUpdateV10MultiProductCreativeListCreativeType];

