// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_request_creative_abstract_materials_inner.go
// Do not edit manually.

import type { CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerStructAbstractInfo, CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfo } from "../models/index";

export interface CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInner {
  material_id?: number | string;
  struct_abstract_info?: CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerStructAbstractInfo;
  text_abstract_info?: CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfo;
}

