// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_report_uni_promotion_config_get_v1_0_data_topics.go
// Do not edit manually.

export const QianchuanReportUniPromotionConfigGetV10DataTopics = {
  OVERALL_ROI_LIVE_AWEME: "OVERALL_ROI_LIVE_AWEME",
  OVERALL_ROI_LIVE_MATERIAL_LIVE: "OVERALL_ROI_LIVE_MATERIAL_LIVE",
  OVERALL_ROI_LIVE_MATERIAL_VIDEO: "OVERALL_ROI_LIVE_MATERIAL_VIDEO",
  OVERALL_ROI_PRODUCT_AWEME: "OVERALL_ROI_PRODUCT_AWEME",
  OVERALL_ROI_PRODUCT_MATERIAL: "OVERALL_ROI_PRODUCT_MATERIAL",
  OVERALL_ROI_PRODUCT_PRODUCT: "OVERALL_ROI_PRODUCT_PRODUCT",
  OVERALL_ROI_PRODUCT_PROJECT: "OVERALL_ROI_PRODUCT_PROJECT",
  ROI2_IMAGE_AGG_MATERIAL_ANALYSIS: "ROI2_IMAGE_AGG_MATERIAL_ANALYSIS",
  SITE_PROMOTION_POST_DATA_LIVE: "SITE_PROMOTION_POST_DATA_LIVE",
  SITE_PROMOTION_POST_DATA_OTHER: "SITE_PROMOTION_POST_DATA_OTHER",
  SITE_PROMOTION_POST_DATA_TITLE: "SITE_PROMOTION_POST_DATA_TITLE",
  SITE_PROMOTION_POST_DATA_VIDEO: "SITE_PROMOTION_POST_DATA_VIDEO",
  SITE_PROMOTION_PRODUCT_AD: "SITE_PROMOTION_PRODUCT_AD",
  SITE_PROMOTION_PRODUCT_POST_ASSIST_TASK: "SITE_PROMOTION_PRODUCT_POST_ASSIST_TASK",
  SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE: "SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE",
  SITE_PROMOTION_PRODUCT_POST_DATA_OTHER: "SITE_PROMOTION_PRODUCT_POST_DATA_OTHER",
  SITE_PROMOTION_PRODUCT_POST_DATA_TITLE: "SITE_PROMOTION_PRODUCT_POST_DATA_TITLE",
  SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO: "SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO",
  SITE_PROMOTION_PRODUCT_PRODUCT: "SITE_PROMOTION_PRODUCT_PRODUCT",
} as const;

export type QianchuanReportUniPromotionConfigGetV10DataTopics = typeof QianchuanReportUniPromotionConfigGetV10DataTopics[keyof typeof QianchuanReportUniPromotionConfigGetV10DataTopics];

