// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_qianchuan_report_today_live_room_config_get_v1_0_response_data_custom_config_datas_inner_dimensions_inner_filter_config_range_values_inner.go
// Do not edit manually.

export interface QianchuanQianchuanReportTodayLiveRoomConfigGetV10ResponseDataCustomConfigDatasInnerDimensionsInnerFilterConfigRangeValuesInner {
  label?: string;
  value?: string;
}

