// Generated from oceanengine/ad_open_sdk_go models/model_report_stardelivery_task_data_get_v3_0_filtering_metric_value_filter_operator.go
// Do not edit manually.

export const ReportStardeliveryTaskDataGetV30FilteringMetricValueFilterOperator = {
  Enum_1: 1,
} as const;

export type ReportStardeliveryTaskDataGetV30FilteringMetricValueFilterOperator = typeof ReportStardeliveryTaskDataGetV30FilteringMetricValueFilterOperator[keyof typeof ReportStardeliveryTaskDataGetV30FilteringMetricValueFilterOperator];

