// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_request_programmatic_creative_media_list.go
// Do not edit manually.

import type { QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaListBlockVideoMaterialInner, QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaListTitleMaterialInner, QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaListVideoMaterialInner } from "../models/index";

export interface QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaList {
  block_video_material?: QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaListBlockVideoMaterialInner[];
  title_material?: QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaListTitleMaterialInner[];
  video_material?: QianchuanUniAwemeAdCreateV10RequestProgrammaticCreativeMediaListVideoMaterialInner[];
}

