// Generated from oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_response_data_list_inner_promotion_related_product_inner_image_material_list_inner.go
// Do not edit manually.

import type { PromotionListV30DataListPromotionRelatedProductImageMaterialListImageMode, PromotionListV30ResponseDataListInnerPromotionRelatedProductInnerImageMaterialListInnerImagesInner } from "../models/index";

export interface PromotionListV30ResponseDataListInnerPromotionRelatedProductInnerImageMaterialListInner {
  image_mode?: PromotionListV30DataListPromotionRelatedProductImageMaterialListImageMode;
  images?: PromotionListV30ResponseDataListInnerPromotionRelatedProductInnerImageMaterialListInnerImagesInner[];
}

