// Generated from oceanengine/ad_open_sdk_go models/model_douplus_optional_items_list_v3_0_external_action.go
// Do not edit manually.

export const DouplusOptionalItemsListV30ExternalAction = {
  COMMENT_LINK_CLICK: "COMMENT_LINK_CLICK",
  DY_PRIVATE_MESSAGES: "DY_PRIVATE_MESSAGES",
  FOLLOWER_COUNT: "FOLLOWER_COUNT",
  HIGH_INTERACTION_FREQUENCY: "HIGH_INTERACTION_FREQUENCY",
  HIGH_INTERACTION_QUALITY: "HIGH_INTERACTION_QUALITY",
  LIKE_COMMENT_AMOUNT: "LIKE_COMMENT_AMOUNT",
  LIVE_ROOM_FOLLOWER_INCREASE: "LIVE_ROOM_FOLLOWER_INCREASE",
  LIVE_ROOM_POPULARITY: "LIVE_ROOM_POPULARITY",
  ONLY_FOR_ACTIVATION: "ONLY_FOR_ACTIVATION",
  VIDEO_PLAYBACK_VOLUME: "VIDEO_PLAYBACK_VOLUME",
  VIEWER_DONATION: "VIEWER_DONATION",
  VIEWER_INTERACTION: "VIEWER_INTERACTION",
} as const;

export type DouplusOptionalItemsListV30ExternalAction = typeof DouplusOptionalItemsListV30ExternalAction[keyof typeof DouplusOptionalItemsListV30ExternalAction];

