// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_list_v1_0_response_data_ad_list_inner.go 生成
// 不要手动编辑。

import type { QianchuanUniPromotionListV10ResponseDataAdListInnerAdInfo, QianchuanUniPromotionListV10ResponseDataAdListInnerProductInfoInner, QianchuanUniPromotionListV10ResponseDataAdListInnerRoomInfoInner, QianchuanUniPromotionListV10ResponseDataAdListInnerStatsInfo } from "../models/index";

export interface QianchuanUniPromotionListV10ResponseDataAdListInner {
  ad_info?: QianchuanUniPromotionListV10ResponseDataAdListInnerAdInfo;
  product_info?: QianchuanUniPromotionListV10ResponseDataAdListInnerProductInfoInner[];
  room_info?: QianchuanUniPromotionListV10ResponseDataAdListInnerRoomInfoInner[];
  stats_info?: QianchuanUniPromotionListV10ResponseDataAdListInnerStatsInfo;
}

