// Generated from oceanengine/ad_open_sdk_go models/model_shared_wallet_wallet_operation_log_get_v3_0_response_data_list_inner_operation_detail.go
// Do not edit manually.

import type { SharedWalletWalletOperationLogGetV30ResponseDataListInnerOperationDetailRelationChangeOperationDetail } from "../models/index";

export interface SharedWalletWalletOperationLogGetV30ResponseDataListInnerOperationDetail {
  relation_change_operation_detail?: SharedWalletWalletOperationLogGetV30ResponseDataListInnerOperationDetailRelationChangeOperationDetail;
}

