// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_request_multi_product_creative_list_inner_programmatic_creative_programmatic_creative_card.go 生成
// 不要手动编辑。

import type { QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization } from "../models/index";

export interface QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeCard {
  promotion_card_action_button?: string;
  promotion_card_button_smart_optimization?: QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization;
  promotion_card_image_id?: string;
  promotion_card_selling_points?: string[];
  promotion_card_title?: string;
}

