// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_update_v1_0_request_multi_product_creative_list_inner_title_material_inner.go
// Do not edit manually.

import type { QianchuanUniAwemeAdUpdateV10MultiProductCreativeListTitleMaterialTitleType, QianchuanUniAwemeAdUpdateV10RequestMultiProductCreativeListInnerTitleMaterialInnerDynamicWordsInner } from "../models/index";

export interface QianchuanUniAwemeAdUpdateV10RequestMultiProductCreativeListInnerTitleMaterialInner {
  dynamic_words?: QianchuanUniAwemeAdUpdateV10RequestMultiProductCreativeListInnerTitleMaterialInnerDynamicWordsInner[];
  title?: string;
  title_type?: QianchuanUniAwemeAdUpdateV10MultiProductCreativeListTitleMaterialTitleType;
}

