// Generated from oceanengine/ad_open_sdk_go models/model_local_project_detail_v3_0_data_audience_filter_aweme_abnormal_active.go
// Do not edit manually.

export const LocalProjectDetailV30DataAudienceFilterAwemeAbnormalActive = {
  FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_OFF: "FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_OFF",
  FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_ON: "FILTER_AWEME_ABNORMAL_ACTIVE_TYPE_ON",
} as const;

export type LocalProjectDetailV30DataAudienceFilterAwemeAbnormalActive = typeof LocalProjectDetailV30DataAudienceFilterAwemeAbnormalActive[keyof typeof LocalProjectDetailV30DataAudienceFilterAwemeAbnormalActive];

