// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_list_v3_0_response_data_record_list_inner_transfer_capital_record_list_inner_capital_sub_detail_list_inner.go
// Do not edit manually.

import type { CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType, CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus } from "../models/index";

export interface CgTransferWalletTransferListV30ResponseDataRecordListInnerTransferCapitalRecordListInnerCapitalSubDetailListInner {
  capital_sub_type?: CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListCapitalSubType;
  transfer_amount?: number;
  transfer_status?: CgTransferWalletTransferListV30DataRecordListTransferCapitalRecordListCapitalSubDetailListTransferStatus;
}

