// Generated from oceanengine/ad_open_sdk_go models/model_cg_transfer_wallet_transfer_can_transfer_balance_v3_0_data_can_transfer_detail_list_payee_transfer_amount_detail_list_capital_detail_list_capital_type.go
// Do not edit manually.

export const CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListCapitalType = {
  CREDIT_BIDDING: "CREDIT_BIDDING",
  CREDIT_BRAND: "CREDIT_BRAND",
  CREDIT_GENERAL: "CREDIT_GENERAL",
  PREPAY_BIDDING: "PREPAY_BIDDING",
  PREPAY_BRAND: "PREPAY_BRAND",
  PREPAY_GENERAL: "PREPAY_GENERAL",
} as const;

export type CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListCapitalType = typeof CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListCapitalType[keyof typeof CgTransferWalletTransferCanTransferBalanceV30DataCanTransferDetailListPayeeTransferAmountDetailListCapitalDetailListCapitalType];

