// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_creative_list_promotion_card_material_button_smart_optimization.go
// Do not edit manually.

export const QianchuanAdCreateV10CreativeListPromotionCardMaterialButtonSmartOptimization = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdCreateV10CreativeListPromotionCardMaterialButtonSmartOptimization = typeof QianchuanAdCreateV10CreativeListPromotionCardMaterialButtonSmartOptimization[keyof typeof QianchuanAdCreateV10CreativeListPromotionCardMaterialButtonSmartOptimization];

