// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_request_multi_product_creative_list_inner_creative_setting.go
// Do not edit manually.

import type { QianchuanAdCreateV10MultiProductCreativeListCreativeSettingCreativeAutoGenerate, QianchuanAdCreateV10MultiProductCreativeListCreativeSettingDynamicCreative, QianchuanAdCreateV10MultiProductCreativeListCreativeSettingIsHomepageHide, QianchuanAdCreateV10RequestMultiProductCreativeListInnerCreativeSettingCreativeCategory } from "../models/index";

export interface QianchuanAdCreateV10RequestMultiProductCreativeListInnerCreativeSetting {
  ad_keywords?: string[];
  aweme_id?: number | string;
  creative_auto_generate?: QianchuanAdCreateV10MultiProductCreativeListCreativeSettingCreativeAutoGenerate;
  creative_category?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerCreativeSettingCreativeCategory;
  dynamic_creative?: QianchuanAdCreateV10MultiProductCreativeListCreativeSettingDynamicCreative;
  is_homepage_hide?: QianchuanAdCreateV10MultiProductCreativeListCreativeSettingIsHomepageHide;
}

