// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_uni_aweme_ad_create_v1_0_programmatic_creative_media_list_video_material_image_mode.go 生成
// 不要手动编辑。

export const QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialImageMode = {
  VIDEO_LARGE: "VIDEO_LARGE",
  VIDEO_VERTICAL: "VIDEO_VERTICAL",
} as const;

export type QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialImageMode = typeof QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialImageMode[keyof typeof QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialImageMode];

