// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_multi_product_creative_list_programmatic_creative_programmatic_creative_title_list_title_type.go 生成
// 不要手动编辑。

export const QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType = {
  AWEME_CAROUSEL: "AWEME_CAROUSEL",
  COMMODITY_CARD: "COMMODITY_CARD",
  CUSTOM: "CUSTOM",
} as const;

export type QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType = typeof QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType[keyof typeof QianchuanAdCreateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeTitleListTitleType];

