// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_programmatic_creative_card_promotion_card_button_smart_optimization.go
// Do not edit manually.

export const QianchuanAdCreateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdCreateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization = typeof QianchuanAdCreateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization[keyof typeof QianchuanAdCreateV10ProgrammaticCreativeCardPromotionCardButtonSmartOptimization];

