// Generated from oceanengine/ad_open_sdk_go models/model_ad_get_v2_data_inventory_type.go
// Do not edit manually.

export const AdGetV2DataInventoryType = {
  INVENTORY_AWEME_SEARCH: "INVENTORY_AWEME_SEARCH",
  UNION_BOUTIQUE_GAME: "UNION_BOUTIQUE_GAME",
  INVENTORY_HOTSOON_FEED: "INVENTORY_HOTSOON_FEED",
  INVENTORY_TOMATO_NOVEL: "INVENTORY_TOMATO_NOVEL",
  INVENTORY_ESSAY_FEED: "INVENTORY_ESSAY_FEED",
  INVENTORY_FEED: "INVENTORY_FEED",
  INVENTORY_UNION_SPLASH_SLOT: "INVENTORY_UNION_SPLASH_SLOT",
  INVENTORY_VIDEO_FEED: "INVENTORY_VIDEO_FEED",
  INVENTORY_SEARCH: "INVENTORY_SEARCH",
  INVENTORY_TEXT_LINK: "INVENTORY_TEXT_LINK",
  INVENTORY_AWEME_FEED: "INVENTORY_AWEME_FEED",
  INVENTORY_UNION_SLOT: "INVENTORY_UNION_SLOT",
} as const;

export type AdGetV2DataInventoryType = typeof AdGetV2DataInventoryType[keyof typeof AdGetV2DataInventoryType];

