// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_detail_get_v1_0_data_multi_product_creative_list_creative_setting_dynamic_creative.go
// Do not edit manually.

export const QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingDynamicCreative = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingDynamicCreative = typeof QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingDynamicCreative[keyof typeof QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingDynamicCreative];

