// 由 oceanengine/ad_open_sdk_go models/model_star_challenge_info_v2_response_data_task_info_list_inner_demand_info_ad_sync_conf.go 生成
// 不要手动编辑。

import type { StarChallengeInfoV2ResponseDataTaskInfoListInnerDemandInfoAdSyncConfDouPlus, StarChallengeInfoV2ResponseDataTaskInfoListInnerDemandInfoAdSyncConfOceanEngine } from "../models/index";

export interface StarChallengeInfoV2ResponseDataTaskInfoListInnerDemandInfoAdSyncConf {
  dou_plus?: StarChallengeInfoV2ResponseDataTaskInfoListInnerDemandInfoAdSyncConfDouPlus;
  ocean_engine?: StarChallengeInfoV2ResponseDataTaskInfoListInnerDemandInfoAdSyncConfOceanEngine;
}

