// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_detail_get_v1_0_data_creative_list_promotion_card_material_button_smart_optimization.go
// Do not edit manually.

export const QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization = typeof QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization[keyof typeof QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization];

