// Generated from oceanengine/ad_open_sdk_go models/model_tools_bp_asset_management_share_v3_0_response_data_error_list_inner.go
// Do not edit manually.

import type { ToolsBpAssetManagementShareV30DataErrorListAllAccountsByBp, ToolsBpAssetManagementShareV30DataErrorListShareMode, ToolsBpAssetManagementShareV30ResponseDataErrorListInnerAccountInfo, ToolsBpAssetManagementShareV30ResponseDataErrorListInnerAllAccountsByCompany } from "../models/index";

export interface ToolsBpAssetManagementShareV30ResponseDataErrorListInner {
  account_info?: ToolsBpAssetManagementShareV30ResponseDataErrorListInnerAccountInfo;
  all_accounts_by_bp?: ToolsBpAssetManagementShareV30DataErrorListAllAccountsByBp;
  all_accounts_by_company?: ToolsBpAssetManagementShareV30ResponseDataErrorListInnerAllAccountsByCompany;
  error_message?: string;
  share_mode?: ToolsBpAssetManagementShareV30DataErrorListShareMode;
}

