// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_report_uni_promotion_dimension_data_author_get_v1_0_response_data.go 生成
// 不要手动编辑。

import type { QianchuanReportUniPromotionDimensionDataAuthorGetV10ResponseDataListInner, QianchuanReportUniPromotionDimensionDataAuthorGetV10ResponseDataPageInfo } from "../models/index";

export interface QianchuanReportUniPromotionDimensionDataAuthorGetV10ResponseData {
  list?: QianchuanReportUniPromotionDimensionDataAuthorGetV10ResponseDataListInner[];
  page_info?: QianchuanReportUniPromotionDimensionDataAuthorGetV10ResponseDataPageInfo;
}

