// Generated from oceanengine/ad_open_sdk_go models/model_tools_hot_material_derive_get_v3_0_response_data_task_details_inner_derive_materials_inner_strategy_detail.go
// Do not edit manually.

import type { ToolsHotMaterialDeriveGetV30DataTaskDetailsDeriveMaterialsStrategyDetailStrategy, ToolsHotMaterialDeriveGetV30ResponseDataTaskDetailsInnerDeriveMaterialsInnerStrategyDetailApplyTimesInner } from "../models/index";

export interface ToolsHotMaterialDeriveGetV30ResponseDataTaskDetailsInnerDeriveMaterialsInnerStrategyDetail {
  apply_times?: ToolsHotMaterialDeriveGetV30ResponseDataTaskDetailsInnerDeriveMaterialsInnerStrategyDetailApplyTimesInner[];
  strategy?: ToolsHotMaterialDeriveGetV30DataTaskDetailsDeriveMaterialsStrategyDetailStrategy;
  strategy_description?: string;
  strategy_name?: string;
}

