// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_update_v1_0_request_multi_product_creative_list_inner_programmatic_creative_programmatic_creative_card.go
// Do not edit manually.

import type { QianchuanAdUpdateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization } from "../models/index";

export interface QianchuanAdUpdateV10RequestMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeCard {
  promotion_card_action_button?: string;
  promotion_card_button_smart_optimization?: QianchuanAdUpdateV10MultiProductCreativeListProgrammaticCreativeProgrammaticCreativeCardPromotionCardButtonSmartOptimization;
  promotion_card_image_id?: string;
  promotion_card_selling_points?: string[];
  promotion_card_title?: string;
}

