// Generated from oceanengine/ad_open_sdk_go models/model_agent_adv_bidding_list_query_v2_filtering_account_status.go
// Do not edit manually.

export const AgentAdvBiddingListQueryV2FilteringAccountStatus = {
  STATUS_DISABLE: "STATUS_DISABLE",
  STATUS_PENDING_CONFIRM: "STATUS_PENDING_CONFIRM",
  STATUS_PENDING_VERIFIED: "STATUS_PENDING_VERIFIED",
  STATUS_CONFIRM_FAIL: "STATUS_CONFIRM_FAIL",
  STATUS_ENABLE: "STATUS_ENABLE",
  STATUS_CONFIRM_FAIL_END: "STATUS_CONFIRM_FAIL_END",
  STATUS_PENDING_CONFIRM_MODIFY: "STATUS_PENDING_CONFIRM_MODIFY",
  STATUS_CONFIRM_MODIFY_FAIL: "STATUS_CONFIRM_MODIFY_FAIL",
  STATUS_PUNISH: "STATUS_PUNISH",
  STATUS_WAIT_FOR_BPM_AUDIT: "STATUS_WAIT_FOR_BPM_AUDIT",
  STATUS_SELF_SERVICE_UNAUDITED: "STATUS_SELF_SERVICE_UNAUDITED",
  STATUS_ENABLE_AND_AVATAR_AUDITING: "STATUS_ENABLE_AND_AVATAR_AUDITING",
  STATUS_WAIT_FOR_BPM_FILE_CONTACT: "STATUS_WAIT_FOR_BPM_FILE_CONTACT",
  STATUS_WAIT_FOR_ACCOUNT_FEE: "STATUS_WAIT_FOR_ACCOUNT_FEE",
  STATUS_WAIT_FOR_PUBLIC_AUTH: "STATUS_WAIT_FOR_PUBLIC_AUTH",
} as const;

export type AgentAdvBiddingListQueryV2FilteringAccountStatus = typeof AgentAdvBiddingListQueryV2FilteringAccountStatus[keyof typeof AgentAdvBiddingListQueryV2FilteringAccountStatus];

