// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_update_v1_0_request_creative_list_inner.go
// Do not edit manually.

import type { QianchuanAdUpdateV10CreativeListImageMode, QianchuanAdUpdateV10RequestCreativeListInnerCarouselMaterial, QianchuanAdUpdateV10RequestCreativeListInnerImageMaterial, QianchuanAdUpdateV10RequestCreativeListInnerPromotionCardMaterial, QianchuanAdUpdateV10RequestCreativeListInnerTitleMaterial, QianchuanAdUpdateV10RequestCreativeListInnerVideoMaterial } from "../models/index";

export interface QianchuanAdUpdateV10RequestCreativeListInner {
  carousel_material?: QianchuanAdUpdateV10RequestCreativeListInnerCarouselMaterial;
  creative_id?: number | string;
  image_material?: QianchuanAdUpdateV10RequestCreativeListInnerImageMaterial;
  image_mode: QianchuanAdUpdateV10CreativeListImageMode;
  promotion_card_material?: QianchuanAdUpdateV10RequestCreativeListInnerPromotionCardMaterial;
  title_material?: QianchuanAdUpdateV10RequestCreativeListInnerTitleMaterial;
  video_material?: QianchuanAdUpdateV10RequestCreativeListInnerVideoMaterial;
}

