// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_ad_create_v1_0_request_multi_product_creative_list_inner.go 生成
// 不要手动编辑。

import type { QianchuanAdCreateV10MultiProductCreativeListCreativeMaterialMode, QianchuanAdCreateV10RequestMultiProductCreativeListInnerCreativeSetting, QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreative } from "../models/index";

export interface QianchuanAdCreateV10RequestMultiProductCreativeListInner {
  creative_material_mode: QianchuanAdCreateV10MultiProductCreativeListCreativeMaterialMode;
  creative_setting?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerCreativeSetting;
  product_id?: number | string;
  programmatic_creative?: QianchuanAdCreateV10RequestMultiProductCreativeListInnerProgrammaticCreative;
}

