// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_detail_get_v1_0_data_multi_product_creative_list_creative_setting_creative_auto_generate.go
// Do not edit manually.

export const QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingCreativeAutoGenerate = {
  Enum_0: 0,
  Enum_1: 1,
} as const;

export type QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingCreativeAutoGenerate = typeof QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingCreativeAutoGenerate[keyof typeof QianchuanAdDetailGetV10DataMultiProductCreativeListCreativeSettingCreativeAutoGenerate];

