// Generated from oceanengine/ad_open_sdk_go models/model_ad_get_v2_filtering_status.go
// Do not edit manually.

export const AdGetV2FilteringStatus = {
  AD_STATUS_NOT_START: "AD_STATUS_NOT_START",
  AD_STATUS_BUDGET_EXCEED: "AD_STATUS_BUDGET_EXCEED",
  AD_STATUS_NO_SCHEDULE: "AD_STATUS_NO_SCHEDULE",
  AD_STATUS_REAUDIT: "AD_STATUS_REAUDIT",
  AD_STATUS_DELETE: "AD_STATUS_DELETE",
  AD_STATUS_CREATE: "AD_STATUS_CREATE",
  AD_STATUS_BALANCE_EXCEED: "AD_STATUS_BALANCE_EXCEED",
  AD_STATUS_DISABLE: "AD_STATUS_DISABLE",
  AD_STATUS_DELIVERY_OK: "AD_STATUS_DELIVERY_OK",
  AD_STATUS_ALL: "AD_STATUS_ALL",
  AD_STATUS_AUDIT_DENY: "AD_STATUS_AUDIT_DENY",
  AD_STATUS_DONE: "AD_STATUS_DONE",
  AD_STATUS_AUDIT: "AD_STATUS_AUDIT",
  AD_STATUS_CAMPAIGN_DISABLE: "AD_STATUS_CAMPAIGN_DISABLE",
  AD_STATUS_NOT_DELETE: "AD_STATUS_NOT_DELETE",
  AD_STATUS_CAMPAIGN_EXCEED: "AD_STATUS_CAMPAIGN_EXCEED",
} as const;

export type AdGetV2FilteringStatus = typeof AdGetV2FilteringStatus[keyof typeof AdGetV2FilteringStatus];

