// Generated from oceanengine/ad_open_sdk_go models/model_brand_material_update_v3_0_material_list_material_component_aweme_anchor_anchor_type.go
// Do not edit manually.

export const BrandMaterialUpdateV30MaterialListMaterialComponentAwemeAnchorAnchorType = {
  SHOPPING_CART: "SHOPPING_CART",
} as const;

export type BrandMaterialUpdateV30MaterialListMaterialComponentAwemeAnchorAnchorType = typeof BrandMaterialUpdateV30MaterialListMaterialComponentAwemeAnchorAnchorType[keyof typeof BrandMaterialUpdateV30MaterialListMaterialComponentAwemeAnchorAnchorType];

