// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_request_creative_abstract_materials_inner_text_abstract_info.go
// Do not edit manually.

import type { CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfoBidwordListInner, CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfoWordListInner } from "../models/index";

export interface CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfo {
  abstract_text: string;
  bidword_list?: CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfoBidwordListInner[];
  word_list?: CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfoWordListInner[];
}

