// Generated from oceanengine/ad_open_sdk_go models/model_agent_info_v2_data_account_status.go
// Do not edit manually.

export const AgentInfoV2DataAccountStatus = {
  STATUS_LIMIT: "STATUS_LIMIT",
  STATUS_PENDING_CONFIRM: "STATUS_PENDING_CONFIRM",
  STATUS_PENDING_VERIFIED: "STATUS_PENDING_VERIFIED",
  STATUS_CONFIRM_FAIL_END: "STATUS_CONFIRM_FAIL_END",
  STATUS_CONFIRM_FAIL: "STATUS_CONFIRM_FAIL",
  STATUS_SELF_SERVICE_UNAUDITED: "STATUS_SELF_SERVICE_UNAUDITED",
  STATUS_ENABLE: "STATUS_ENABLE",
  STATUS_DISABLE: "STATUS_DISABLE",
  STATUS_PENDING_CONFIRM_MODIFY: "STATUS_PENDING_CONFIRM_MODIFY",
  STATUS_WAIT_FOR_PUBLIC_AUTH: "STATUS_WAIT_FOR_PUBLIC_AUTH",
  STATUS_WAIT_FOR_BPM_AUDIT: "STATUS_WAIT_FOR_BPM_AUDIT",
  STATUS_CONFIRM_MODIFY_FAIL: "STATUS_CONFIRM_MODIFY_FAIL",
} as const;

export type AgentInfoV2DataAccountStatus = typeof AgentInfoV2DataAccountStatus[keyof typeof AgentInfoV2DataAccountStatus];

