// Generated from oceanengine/ad_open_sdk_go models/model_tools_site_template_site_create_v2_request_bricks_inner_button_download_event.go
// Do not edit manually.

import type { ToolsSiteTemplateSiteCreateV2RequestBricksInnerButtonDownloadEventAndroidLink, ToolsSiteTemplateSiteCreateV2RequestBricksInnerButtonDownloadEventIosLink } from "../models/index";

export interface ToolsSiteTemplateSiteCreateV2RequestBricksInnerButtonDownloadEvent {
  android_link?: ToolsSiteTemplateSiteCreateV2RequestBricksInnerButtonDownloadEventAndroidLink;
  ios_link?: ToolsSiteTemplateSiteCreateV2RequestBricksInnerButtonDownloadEventIosLink;
}

