// Generated from oceanengine/ad_open_sdk_go models/model_local_promotion_create_v3_0_request_procedural_material.go
// Do not edit manually.

import type { LocalPromotionCreateV30RequestProceduralMaterialCarouselMaterialListInner, LocalPromotionCreateV30RequestProceduralMaterialTitleMaterialListInner, LocalPromotionCreateV30RequestProceduralMaterialVideoMaterialListInner } from "../models/index";

export interface LocalPromotionCreateV30RequestProceduralMaterial {
  carousel_material_list?: LocalPromotionCreateV30RequestProceduralMaterialCarouselMaterialListInner[];
  title_material_list: LocalPromotionCreateV30RequestProceduralMaterialTitleMaterialListInner[];
  video_material_list?: LocalPromotionCreateV30RequestProceduralMaterialVideoMaterialListInner[];
}

