// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_ad_detail_get_v1_0_response_data_multi_product_creative_list_inner_programmatic_creative_programmatic_creative_media_list_inner_carousel_images_inner.go
// Do not edit manually.

export interface QianchuanAdDetailGetV10ResponseDataMultiProductCreativeListInnerProgrammaticCreativeProgrammaticCreativeMediaListInnerCarouselImagesInner {
  url?: string;
}

