// 由 oceanengine/ad_open_sdk_go models/model_report_campaign_get_v2_filtering_inventory_types.go 生成
// 不要手动编辑。

export const ReportCampaignGetV2FilteringInventoryTypes = {
  INVENTORY_TOMATO_NOVEL: "INVENTORY_TOMATO_NOVEL",
  INVENTORY_FEED: "INVENTORY_FEED",
  INVENTORY_UNIVERSAL: "INVENTORY_UNIVERSAL",
  INVENTORY_FURNISH: "INVENTORY_FURNISH",
  INVENTORY_PIPIXIA: "INVENTORY_PIPIXIA",
  INVENTORY_SEARCH: "INVENTORY_SEARCH",
  INVENTORY_AWEME_FEED: "INVENTORY_AWEME_FEED",
  INVENTORY_FACE_U: "INVENTORY_FACE_U",
  INVENTORY_STUDY: "INVENTORY_STUDY",
  INVENTORY_AUTOMOBILE: "INVENTORY_AUTOMOBILE",
  INVENTORY_VIDEO_FEED: "INVENTORY_VIDEO_FEED",
  INVENTORY_UNION_SLOT: "INVENTORY_UNION_SLOT",
  INVENTORY_HOTSOON_FEED: "INVENTORY_HOTSOON_FEED",
  INVENTORY_BEAUTY: "INVENTORY_BEAUTY",
  UNION_BOUTIQUE_GAME: "UNION_BOUTIQUE_GAME",
} as const;

export type ReportCampaignGetV2FilteringInventoryTypes = typeof ReportCampaignGetV2FilteringInventoryTypes[keyof typeof ReportCampaignGetV2FilteringInventoryTypes];

