// Generated from oceanengine/ad_open_sdk_go models/model_creative_procedural_creative_update_v2_request_creative_abstract_materials_inner_text_abstract_info_bidword_list_inner.go
// Do not edit manually.

export interface CreativeProceduralCreativeUpdateV2RequestCreativeAbstractMaterialsInnerTextAbstractInfoBidwordListInner {
  default_word: string;
}

