// 由 oceanengine/ad_open_sdk_go models/model_qianchuan_aweme_uni_promotion_ad_material_get_v1_0_data_ad_material_infos_material_status.go 生成
// 不要手动编辑。

export const QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus = {
  DELIVERY_NOT: "DELIVERY_NOT",
} as const;

export type QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus = typeof QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus[keyof typeof QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus];

