// 由 oceanengine/ad_open_sdk_go models/model_local_promotion_update_v3_0_request_customer_material_list_inner.go 生成
// 不要手动编辑。

import type { LocalPromotionUpdateV30CustomerMaterialListImageMode, LocalPromotionUpdateV30RequestCustomerMaterialListInnerTitleMaterial, LocalPromotionUpdateV30RequestCustomerMaterialListInnerVideoMaterial } from "../models/index";

export interface LocalPromotionUpdateV30RequestCustomerMaterialListInner {
  image_mode: LocalPromotionUpdateV30CustomerMaterialListImageMode;
  title_material?: LocalPromotionUpdateV30RequestCustomerMaterialListInnerTitleMaterial;
  video_material: LocalPromotionUpdateV30RequestCustomerMaterialListInnerVideoMaterial;
}

