// Generated from oceanengine/ad_open_sdk_go models/model_promotion_list_v3_0_response_data_list_inner_material_score_info.go
// Do not edit manually.

import type { PromotionListV30DataListMaterialScoreInfoScoreNumOfMaterial, PromotionListV30DataListMaterialScoreInfoScoreTypeOfMaterial, PromotionListV30DataListMaterialScoreInfoScoreValueOfMaterial, PromotionListV30ResponseDataListInnerMaterialScoreInfoLowQualityMaterialList } from "../models/index";

export interface PromotionListV30ResponseDataListInnerMaterialScoreInfo {
  low_quality_material_list?: PromotionListV30ResponseDataListInnerMaterialScoreInfoLowQualityMaterialList;
  material_advice?: string[];
  score_num_of_material?: PromotionListV30DataListMaterialScoreInfoScoreNumOfMaterial;
  score_type_of_material?: PromotionListV30DataListMaterialScoreInfoScoreTypeOfMaterial;
  score_value_of_material?: PromotionListV30DataListMaterialScoreInfoScoreValueOfMaterial;
}

