// Generated from oceanengine/ad_open_sdk_go models/model_qianchuan_uni_promotion_ad_detail_v1_0_data_multi_product_creative_list_video_material_star_traffic.go
// Do not edit manually.

export const QianchuanUniPromotionAdDetailV10DataMultiProductCreativeListVideoMaterialStarTraffic = {
  Enum_1: 1,
} as const;

export type QianchuanUniPromotionAdDetailV10DataMultiProductCreativeListVideoMaterialStarTraffic = typeof QianchuanUniPromotionAdDetailV10DataMultiProductCreativeListVideoMaterialStarTraffic[keyof typeof QianchuanUniPromotionAdDetailV10DataMultiProductCreativeListVideoMaterialStarTraffic];

