// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const Oauth2AdvertiserGetDataListAccountType = {
  ADVERTISER: "ADVERTISER",
  AGENT: "AGENT",
  AGENT_SYSTEM_ACCOUNT: "AGENT_SYSTEM_ACCOUNT",
  CHILD_AGENT: "CHILD_AGENT",
  CUSTOMER_ADMIN: "CUSTOMER_ADMIN",
  CUSTOMER_OPERATOR: "CUSTOMER_OPERATOR",
  PLATFORM_ROLE_AD_EXCHANGE_RTB_ADMIN: "PLATFORM_ROLE_AD_EXCHANGE_RTB_ADMIN",
  PLATFORM_ROLE_AD_EXCHANGE_RTB_OPERATOR: "PLATFORM_ROLE_AD_EXCHANGE_RTB_OPERATOR",
  PLATFORM_ROLE_AWEME: "PLATFORM_ROLE_AWEME",
  PLATFORM_ROLE_ENTERPRISE_BP_ADMIN: "PLATFORM_ROLE_ENTERPRISE_BP_ADMIN",
  PLATFORM_ROLE_ENTERPRISE_BP_OPERATOR: "PLATFORM_ROLE_ENTERPRISE_BP_OPERATOR",
  PLATFORM_ROLE_GROUP_BP_ADMIN: "PLATFORM_ROLE_GROUP_BP_ADMIN",
  PLATFORM_ROLE_GROUP_BP_OPERATOR: "PLATFORM_ROLE_GROUP_BP_OPERATOR",
  PLATFORM_ROLE_LIFE: "PLATFORM_ROLE_LIFE",
  PLATFORM_ROLE_LOCAL_AGENT: "PLATFORM_ROLE_LOCAL_AGENT",
  PLATFORM_ROLE_QIANCHUAN_AGENT: "PLATFORM_ROLE_QIANCHUAN_AGENT",
  PLATFORM_ROLE_SHOP_ACCOUNT: "PLATFORM_ROLE_SHOP_ACCOUNT",
  PLATFORM_ROLE_STAR: "PLATFORM_ROLE_STAR",
  PLATFORM_ROLE_STAR_AGENT: "PLATFORM_ROLE_STAR_AGENT",
  PLATFORM_ROLE_STAR_ISV: "PLATFORM_ROLE_STAR_ISV",
  PLATFORM_ROLE_STAR_MCN: "PLATFORM_ROLE_STAR_MCN",
  PLATFORM_ROLE_YUNTU_BRAND_ISV_ADMIN: "PLATFORM_ROLE_YUNTU_BRAND_ISV_ADMIN",
} as const;

export type Oauth2AdvertiserGetDataListAccountType = typeof Oauth2AdvertiserGetDataListAccountType[keyof typeof Oauth2AdvertiserGetDataListAccountType];

