// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const OcProjectMaterialGetV30DataVideoMaterialListMaterialStatusSecond = {
  MATERIAL_STATUS_AUDIT: "MATERIAL_STATUS_AUDIT",
  MATERIAL_STATUS_AWEME_ACCOUNT_OFFLINE: "MATERIAL_STATUS_AWEME_ACCOUNT_OFFLINE",
  MATERIAL_STATUS_DELETE: "MATERIAL_STATUS_DELETE",
  MATERIAL_STATUS_DISABLE: "MATERIAL_STATUS_DISABLE",
  MATERIAL_STATUS_NO_SCHEDULE: "MATERIAL_STATUS_NO_SCHEDULE",
  MATERIAL_STATUS_OFFLINE_AUDIT: "MATERIAL_STATUS_OFFLINE_AUDIT",
  MATERIAL_STATUS_OFFLINE_BALANCE: "MATERIAL_STATUS_OFFLINE_BALANCE",
  MATERIAL_STATUS_OFFLINE_BUDGET: "MATERIAL_STATUS_OFFLINE_BUDGET",
  MATERIAL_STATUS_PRODUCT_OFFLINE: "MATERIAL_STATUS_PRODUCT_OFFLINE",
  MATERIAL_STATUS_PROJECT_DISABLE: "MATERIAL_STATUS_PROJECT_DISABLE",
  MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET: "MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET",
  MATERIAL_STATUS_TIME_NO_REACH: "MATERIAL_STATUS_TIME_NO_REACH",
  PROJECT_STATUS_DELETE: "PROJECT_STATUS_DELETE",
  PROJECT_STATUS_FROZEN: "PROJECT_STATUS_FROZEN",
  PROJECT_STATUS_REAUDIT: "PROJECT_STATUS_REAUDIT",
} as const;

export type OcProjectMaterialGetV30DataVideoMaterialListMaterialStatusSecond = typeof OcProjectMaterialGetV30DataVideoMaterialListMaterialStatusSecond[keyof typeof OcProjectMaterialGetV30DataVideoMaterialListMaterialStatusSecond];

