// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const ProjectListV30FilteringStatusSecond = {
  PROJECT_STATUS_BUDGET_EXCEED: "PROJECT_STATUS_BUDGET_EXCEED",
  PROJECT_STATUS_BUDGET_GROUP_OFFLINE_BUDGET: "PROJECT_STATUS_BUDGET_GROUP_OFFLINE_BUDGET",
  PROJECT_STATUS_NOT_START: "PROJECT_STATUS_NOT_START",
  PROJECT_STATUS_NO_SCHEDULE: "PROJECT_STATUS_NO_SCHEDULE",
  PROJECT_STATUS_REACH_DAILY_DELIVERY: "PROJECT_STATUS_REACH_DAILY_DELIVERY",
  PROJECT_STATUS_STOP: "PROJECT_STATUS_STOP",
} as const;

export type ProjectListV30FilteringStatusSecond = typeof ProjectListV30FilteringStatusSecond[keyof typeof ProjectListV30FilteringStatusSecond];

