// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const ProjectListV30FilteringStatus = {
  PROJECT_STATUS_ALL: "PROJECT_STATUS_ALL",
  PROJECT_STATUS_BUDGET_EXCEED: "PROJECT_STATUS_BUDGET_EXCEED",
  PROJECT_STATUS_BUDGET_PRE_OFFLINE_BUDGET: "PROJECT_STATUS_BUDGET_PRE_OFFLINE_BUDGET",
  PROJECT_STATUS_DELETE: "PROJECT_STATUS_DELETE",
  PROJECT_STATUS_DISABLE: "PROJECT_STATUS_DISABLE",
  PROJECT_STATUS_DONE: "PROJECT_STATUS_DONE",
  PROJECT_STATUS_ENABLE: "PROJECT_STATUS_ENABLE",
  PROJECT_STATUS_NOT_DELETE: "PROJECT_STATUS_NOT_DELETE",
  PROJECT_STATUS_NOT_START: "PROJECT_STATUS_NOT_START",
  PROJECT_STATUS_NO_SCHEDULE: "PROJECT_STATUS_NO_SCHEDULE",
} as const;

export type ProjectListV30FilteringStatus = typeof ProjectListV30FilteringStatus[keyof typeof ProjectListV30FilteringStatus];

