// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const ProjectListV30FilteringInventoryType = {
  INVENTORY_AUTOMOBILE: "INVENTORY_AUTOMOBILE",
  INVENTORY_AWEME_FEED: "INVENTORY_AWEME_FEED",
  INVENTORY_BEAUTY: "INVENTORY_BEAUTY",
  INVENTORY_FACE_U: "INVENTORY_FACE_U",
  INVENTORY_FEED: "INVENTORY_FEED",
  INVENTORY_HOMED_AGGREGATE: "INVENTORY_HOMED_AGGREGATE",
  INVENTORY_HOTSOON_FEED: "INVENTORY_HOTSOON_FEED",
  INVENTORY_PIPIXIA: "INVENTORY_PIPIXIA",
  INVENTORY_SEARCH: "INVENTORY_SEARCH",
  INVENTORY_STUDY: "INVENTORY_STUDY",
  INVENTORY_TOMATO_NOVEL: "INVENTORY_TOMATO_NOVEL",
  INVENTORY_UNION_SLOT: "INVENTORY_UNION_SLOT",
  INVENTORY_UNIVERSAL: "INVENTORY_UNIVERSAL",
  INVENTORY_VIDEO_FEED: "INVENTORY_VIDEO_FEED",
  UNION_BOUTIQUE_GAME: "UNION_BOUTIQUE_GAME",
} as const;

export type ProjectListV30FilteringInventoryType = typeof ProjectListV30FilteringInventoryType[keyof typeof ProjectListV30FilteringInventoryType];

