// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const PromotionListV30FilteringStatusSecond = {
  AUDIT: "AUDIT",
  AUDIT_DENY: "AUDIT_DENY",
  AVATAR_DISABLED: "AVATAR_DISABLED",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  AWEME_ANCHOR_DISABLED: "AWEME_ANCHOR_DISABLED",
  BALANCE_OFFLINE_BUDGET: "BALANCE_OFFLINE_BUDGET",
  BUDGET_GROUP_OFFLINE_BUDGET: "BUDGET_GROUP_OFFLINE_BUDGET",
  DISABLED: "DISABLED",
  DISABLE_BY_QUOTA: "DISABLE_BY_QUOTA",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NO_SCHEDULE: "NO_SCHEDULE",
  OFFLINE_BALANCE: "OFFLINE_BALANCE",
  PRODUCT_OFFLINE: "PRODUCT_OFFLINE",
  PROJECT_DISABLED: "PROJECT_DISABLED",
  PROJECT_OFFLINE_BUDGET: "PROJECT_OFFLINE_BUDGET",
  PROJECT_REACH_DAILY_DELIVERY: "PROJECT_REACH_DAILY_DELIVERY",
  PROMOTION_OFFLINE_BUDGET: "PROMOTION_OFFLINE_BUDGET",
  REAUDIT: "REAUDIT",
  STAR_TASK_NOT_STARTED: "STAR_TASK_NOT_STARTED",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type PromotionListV30FilteringStatusSecond = typeof PromotionListV30FilteringStatusSecond[keyof typeof PromotionListV30FilteringStatusSecond];

