// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialStatus = {
  ADV_OFFLINE_BUDGET: "MATERIAL_STATUS_ADV_OFFLINE_BUDGET",
  ADV_PRE_OFFLINE_BUDGET: "MATERIAL_STATUS_ADV_PRE_OFFLINE_BUDGET",
  AUDIT: "MATERIAL_STATUS_AUDIT",
  AVATAR_DISABLED: "MATERIAL_STATUS_AVATAR_DISABLED",
  AWEME_AC_DISABLED: "MATERIAL_STATUS_AWEME_AC_DISABLED",
  AWEME_ANCHOR_DISABLED: "MATERIAL_STATUS_AWEME_ANCHOR_DISABLED",
  AWEME_VIDEO_DISABLED: "MATERIAL_STATUS_AWEME_VIDEO_DISABLED",
  BUDGET_GROUP_OFFLINE_BUDGET: "MATERIAL_STATUS_BUDGET_GROUP_OFFLINE_BUDGET",
  DELETE: "MATERIAL_STATUS_DELETE",
  DISABLE: "MATERIAL_STATUS_DISABLE",
  ERROR_DEFAULT: "MATERIAL_STATUS_ERROR_DEFAULT",
  FROZEN: "MATERIAL_STATUS_FROZEN",
  LIVE_ROOM_OFF: "MATERIAL_STATUS_LIVE_ROOM_OFF",
  MATERIAL_DELETE: "MATERIAL_STATUS_MATERIAL_DELETE",
  NO_SCHEDULE: "MATERIAL_STATUS_NO_SCHEDULE",
  OFFLINE_AUDIT: "MATERIAL_STATUS_OFFLINE_AUDIT",
  OFFLINE_BALANCE: "MATERIAL_STATUS_OFFLINE_BALANCE",
  OFFLINE_BUDGET: "MATERIAL_STATUS_OFFLINE_BUDGET",
  OK: "MATERIAL_STATUS_OK",
  PREOFFLINE_BUGDET: "MATERIAL_STATUS_PREOFFLINE_BUGDET",
  PREONLINE: "MATERIAL_STATUS_PREONLINE",
  PRODUCT_OFFLINE: "MATERIAL_STATUS_PRODUCT_OFFLINE",
  PROJECT_DISABLE: "MATERIAL_STATUS_PROJECT_DISABLE",
  PROJECT_OFFLINE_BUDGET: "MATERIAL_STATUS_PROJECT_OFFLINE_BUDGET",
  PROJECT_PREOFFLINE_BUDGET: "MATERIAL_STATUS_PROJECT_PREOFFLINE_BUDGET",
  PROMOTION_DISABLE: "MATERIAL_STATUS_PROMOTION_DISABLE",
  PROMOTION_QUOTA_LIMIT: "MATERIAL_STATUS_PROMOTION_QUOTA_LIMIT",
  REAUDIT: "MATERIAL_STATUS_REAUDIT",
  STAR_TASK_NOT_STARTED: "MATERIAL_STATUS_STAR_TASK_NOT_STARTED",
  SYSTEM_DISABLE_QUOTA_LIMIT: "MATERIAL_STATUS_SYSTEM_DISABLE_QUOTA_LIMIT",
  TIME_DONE: "MATERIAL_STATUS_TIME_DONE",
  TIME_NO_REACH: "MATERIAL_STATUS_TIME_NO_REACH",
} as const;

export type PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialStatus = typeof PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialStatus[keyof typeof PromotionListV30DataListPromotionRelatedProductImageMaterialListImagesMaterialStatus];

