// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { PromotionUpdateV30PromotionRelatedProductAnchorRelatedType, PromotionUpdateV30PromotionRelatedProductIntelligentGeneration, PromotionUpdateV30PromotionRelatedProductUlinkType, PromotionUpdateV30RequestPromotionRelatedProductInnerAnchorMaterialListInner, PromotionUpdateV30RequestPromotionRelatedProductInnerComponentMaterialListInner, PromotionUpdateV30RequestPromotionRelatedProductInnerImageMaterialListInner, PromotionUpdateV30RequestPromotionRelatedProductInnerTitleMaterialListInner, PromotionUpdateV30RequestPromotionRelatedProductInnerVideoMaterialListInner } from "../models";

export interface PromotionUpdateV30RequestPromotionRelatedProductInner {
  anchor_material_list?: PromotionUpdateV30RequestPromotionRelatedProductInnerAnchorMaterialListInner[];
  anchor_related_type?: PromotionUpdateV30PromotionRelatedProductAnchorRelatedType;
  call_to_action_buttons?: string[];
  component_material_list?: PromotionUpdateV30RequestPromotionRelatedProductInnerComponentMaterialListInner[];
  external_url_material_list?: string[];
  image_material_list?: PromotionUpdateV30RequestPromotionRelatedProductInnerImageMaterialListInner[];
  intelligent_generation?: PromotionUpdateV30PromotionRelatedProductIntelligentGeneration;
  open_url?: string;
  title_material_list?: PromotionUpdateV30RequestPromotionRelatedProductInnerTitleMaterialListInner[];
  ulink_type?: PromotionUpdateV30PromotionRelatedProductUlinkType;
  ulink_url?: string;
  unique_product_id: number;
  video_material_list?: PromotionUpdateV30RequestPromotionRelatedProductInnerVideoMaterialListInner[];
}

