// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

import type { PromotionUpdateV30PromotionMaterialsAdvancedDcSettings, PromotionUpdateV30PromotionMaterialsBlueFlowMaterialRecommend, PromotionUpdateV30PromotionMaterialsDynamicCreativeSwitch, PromotionUpdateV30PromotionMaterialsIntelligentGeneration, PromotionUpdateV30PromotionMaterialsOriginalVideoTitle, PromotionUpdateV30PromotionMaterialsUlinkType, PromotionUpdateV30RequestPromotionMaterialsAnchorMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsCarouselMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsComponentMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsImageMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsInstantPlayMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsMiniProgramInfo, PromotionUpdateV30RequestPromotionMaterialsPlantGrassSearchWordMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsProductInfo, PromotionUpdateV30RequestPromotionMaterialsTextAbstractListInner, PromotionUpdateV30RequestPromotionMaterialsTitleMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsTrialPlayMaterialListInner, PromotionUpdateV30RequestPromotionMaterialsVideoMaterialListInner } from "../models";

export interface PromotionUpdateV30RequestPromotionMaterials {
  advanced_dc_settings?: PromotionUpdateV30PromotionMaterialsAdvancedDcSettings[];
  anchor_material_list?: PromotionUpdateV30RequestPromotionMaterialsAnchorMaterialListInner[];
  blue_flow_material_recommend?: PromotionUpdateV30PromotionMaterialsBlueFlowMaterialRecommend;
  call_to_action_buttons?: string[];
  carousel_material_list?: PromotionUpdateV30RequestPromotionMaterialsCarouselMaterialListInner[];
  component_material_list?: PromotionUpdateV30RequestPromotionMaterialsComponentMaterialListInner[];
  dynamic_creative_switch?: PromotionUpdateV30PromotionMaterialsDynamicCreativeSwitch;
  external_url_field?: string;
  external_url_material_list?: string[];
  external_url_params?: string;
  image_material_list?: PromotionUpdateV30RequestPromotionMaterialsImageMaterialListInner[];
  instant_play_material_list?: PromotionUpdateV30RequestPromotionMaterialsInstantPlayMaterialListInner[];
  intelligent_generation?: PromotionUpdateV30PromotionMaterialsIntelligentGeneration;
  mini_program_info?: PromotionUpdateV30RequestPromotionMaterialsMiniProgramInfo;
  open_url?: string;
  open_url_field?: string;
  open_url_params?: string;
  open_urls?: string[];
  original_video_title?: PromotionUpdateV30PromotionMaterialsOriginalVideoTitle;
  plant_grass_search_word_material_list?: PromotionUpdateV30RequestPromotionMaterialsPlantGrassSearchWordMaterialListInner[];
  playable_url_material_list?: string[];
  playlet_series_url_list?: string[];
  product_info?: PromotionUpdateV30RequestPromotionMaterialsProductInfo;
  text_abstract_list?: PromotionUpdateV30RequestPromotionMaterialsTextAbstractListInner[];
  title_material_list?: PromotionUpdateV30RequestPromotionMaterialsTitleMaterialListInner[];
  trial_play_material_list?: PromotionUpdateV30RequestPromotionMaterialsTrialPlayMaterialListInner[];
  ulink?: string;
  ulink_type?: PromotionUpdateV30PromotionMaterialsUlinkType;
  video_material_list?: PromotionUpdateV30RequestPromotionMaterialsVideoMaterialListInner[];
  web_url_material_list?: string[];
}

