// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const PromotionListV30FilteringStatus = {
  ALL: "ALL",
  AUDIT: "AUDIT",
  AUDIT_DENY: "AUDIT_DENY",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  AWEME_ANCHOR_DISABLED: "AWEME_ANCHOR_DISABLED",
  DELETED: "DELETED",
  DISABLED: "DISABLED",
  DISABLE_BY_QUOTA: "DISABLE_BY_QUOTA",
  FROZEN: "FROZEN",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NOT_DELETED: "NOT_DELETED",
  NO_SCHEDULE: "NO_SCHEDULE",
  OFFLINE_BALANCE: "OFFLINE_BALANCE",
  OFFLINE_BUDGET: "OFFLINE_BUDGET",
  OK: "OK",
  PREOFFLINE_BUDGET: "PREOFFLINE_BUDGET",
  PRODUCT_OFFLINE: "PRODUCT_OFFLINE",
  PROJECT_DISABLED: "PROJECT_DISABLED",
  PROJECT_OFFLINE_BUDGET: "PROJECT_OFFLINE_BUDGET",
  PROJECT_PREOFFLINE_BUDGET: "PROJECT_PREOFFLINE_BUDGET",
  REAUDIT: "REAUDIT",
  TIME_DONE: "TIME_DONE",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type PromotionListV30FilteringStatus = typeof PromotionListV30FilteringStatus[keyof typeof PromotionListV30FilteringStatus];

