// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanUniPromotionAdDetailV10DataDeliverySettingExternalAction = {
  AD_CONVERT_TYPE_CARD_ACTIVE: "AD_CONVERT_TYPE_CARD_ACTIVE",
  AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  AD_CONVERT_TYPE_LIVE_COMMENT_ACTION: "AD_CONVERT_TYPE_LIVE_COMMENT_ACTION",
  AD_CONVERT_TYPE_LIVE_ENTER_ACTION: "AD_CONVERT_TYPE_LIVE_ENTER_ACTION",
  AD_CONVERT_TYPE_LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY_7_DAYS: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY_7DAYS",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_SETTLE: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_SETTLE",
  AD_CONVERT_TYPE_NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  AD_CONVERT_TYPE_SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
} as const;

export type QianchuanUniPromotionAdDetailV10DataDeliverySettingExternalAction = typeof QianchuanUniPromotionAdDetailV10DataDeliverySettingExternalAction[keyof typeof QianchuanUniPromotionAdDetailV10DataDeliverySettingExternalAction];

