// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosAuditStatus, QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus, QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialType, QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerCarouselInfo, QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerImageMaterial, QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerStatsInfo, QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerVideoMaterial } from "../models";

export interface QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInner {
  audit_status: QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosAuditStatus;
  carousel_info?: QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerCarouselInfo;
  delivery_not_reason?: string;
  image_material?: QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerImageMaterial;
  material_status?: QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialStatus;
  material_type: QianchuanAwemeUniPromotionAdMaterialGetV10DataAdMaterialInfosMaterialType;
  stats_info?: QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerStatsInfo;
  video_material?: QianchuanAwemeUniPromotionAdMaterialGetV10ResponseDataAdMaterialInfosInnerVideoMaterial;
}

