// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const QianchuanAdDetailGetV10DataDeliverySettingExternalAction = {
  CARD_ACTIVE: "AD_CONVERT_TYPE_CARD_ACTIVE",
  LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  LIVE_COMMENT_ACTION: "AD_CONVERT_TYPE_LIVE_COMMENT_ACTION",
  LIVE_ENTER_ACTION: "AD_CONVERT_TYPE_LIVE_ENTER_ACTION",
  LIVE_PAY_ROI: "AD_CONVERT_TYPE_LIVE_PAY_ROI",
  LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  LIVE_SUCCESSORDER_PAY_7DAYS: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY_7DAYS",
  LIVE_SUCCESSORDER_SETTLE: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_SETTLE",
  NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
} as const;

export type QianchuanAdDetailGetV10DataDeliverySettingExternalAction = typeof QianchuanAdDetailGetV10DataDeliverySettingExternalAction[keyof typeof QianchuanAdDetailGetV10DataDeliverySettingExternalAction];

