// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanAwemeOrderGetV10DataListDeliverySettingExternalAction = {
  AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  AD_CONVERT_TYPE_LIVE_COMMENT_ACTION: "AD_CONVERT_TYPE_LIVE_COMMENT_ACTION",
  AD_CONVERT_TYPE_LIVE_EFFECTIVE_EFFECTIVE_VIEW: "AD_CONVERT_TYPE_LIVE_EFFECTIVE_EFFECTIVE_VIEW",
  AD_CONVERT_TYPE_LIVE_ENTER_ACTION: "AD_CONVERT_TYPE_LIVE_ENTER_ACTION",
  AD_CONVERT_TYPE_LIVE_HEAT: "AD_CONVERT_TYPE_LIVE_HEAT",
  AD_CONVERT_TYPE_LIVE_ROI: "AD_CONVERT_TYPE_LIVE_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  AD_CONVERT_TYPE_NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  AD_CONVERT_TYPE_SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
} as const;

export type QianchuanAwemeOrderGetV10DataListDeliverySettingExternalAction = typeof QianchuanAwemeOrderGetV10DataListDeliverySettingExternalAction[keyof typeof QianchuanAwemeOrderGetV10DataListDeliverySettingExternalAction];

