// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

import type { QianchuanAwemeUniPromotionOrderDetailV10DataMarketingGoal, QianchuanAwemeUniPromotionOrderDetailV10DataStatus, QianchuanAwemeUniPromotionOrderDetailV10ResponseDataAddAmountInfo, QianchuanAwemeUniPromotionOrderDetailV10ResponseDataAuditRecord, QianchuanAwemeUniPromotionOrderDetailV10ResponseDataAwemeInfo, QianchuanAwemeUniPromotionOrderDetailV10ResponseDataCouponInfosInner, QianchuanAwemeUniPromotionOrderDetailV10ResponseDataDeliverySetting, QianchuanAwemeUniPromotionOrderDetailV10ResponseDataProductInfo } from "../models";

export interface QianchuanAwemeUniPromotionOrderDetailV10ResponseData {
  ad_id?: number;
  add_amount_info?: QianchuanAwemeUniPromotionOrderDetailV10ResponseDataAddAmountInfo;
  audit_record?: QianchuanAwemeUniPromotionOrderDetailV10ResponseDataAuditRecord;
  aweme_info?: QianchuanAwemeUniPromotionOrderDetailV10ResponseDataAwemeInfo;
  coupon_infos?: QianchuanAwemeUniPromotionOrderDetailV10ResponseDataCouponInfosInner[];
  delivery_setting?: QianchuanAwemeUniPromotionOrderDetailV10ResponseDataDeliverySetting;
  marketing_goal?: QianchuanAwemeUniPromotionOrderDetailV10DataMarketingGoal;
  order_create_time?: string;
  order_id: number;
  product_info?: QianchuanAwemeUniPromotionOrderDetailV10ResponseDataProductInfo;
  status?: QianchuanAwemeUniPromotionOrderDetailV10DataStatus;
}

