// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic = {
  Enum_1: 1,
} as const;

export type QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic = typeof QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic[keyof typeof QianchuanUniAwemeAdUpdateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic];

