// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanReportUniPromotionDataGetV10DataTopic = {
  OVERALL_ROI_LIVE_AWEME: "OVERALL_ROI_LIVE_AWEME",
  OVERALL_ROI_LIVE_MATERIAL_LIVE: "OVERALL_ROI_LIVE_MATERIAL_LIVE",
  OVERALL_ROI_LIVE_MATERIAL_VIDEO: "OVERALL_ROI_LIVE_MATERIAL_VIDEO",
  OVERALL_ROI_PRODUCT_AWEME: "OVERALL_ROI_PRODUCT_AWEME",
  OVERALL_ROI_PRODUCT_MATERIAL: "OVERALL_ROI_PRODUCT_MATERIAL",
  OVERALL_ROI_PRODUCT_PRODUCT: "OVERALL_ROI_PRODUCT_PRODUCT",
  OVERALL_ROI_PRODUCT_PROJECT: "OVERALL_ROI_PRODUCT_PROJECT",
  ROI2_IMAGE_AGG_MATERIAL_ANALYSIS: "ROI2_IMAGE_AGG_MATERIAL_ANALYSIS",
  SITE_PROMOTION_POST_DATA_LIVE: "SITE_PROMOTION_POST_DATA_LIVE",
  SITE_PROMOTION_POST_DATA_OTHER: "SITE_PROMOTION_POST_DATA_OTHER",
  SITE_PROMOTION_POST_DATA_TITLE: "SITE_PROMOTION_POST_DATA_TITLE",
  SITE_PROMOTION_POST_DATA_VIDEO: "SITE_PROMOTION_POST_DATA_VIDEO",
  SITE_PROMOTION_PRODUCT_AD: "SITE_PROMOTION_PRODUCT_AD",
  SITE_PROMOTION_PRODUCT_POST_ASSIST_TASK: "SITE_PROMOTION_PRODUCT_POST_ASSIST_TASK",
  SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE: "SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE",
  SITE_PROMOTION_PRODUCT_POST_DATA_OTHER: "SITE_PROMOTION_PRODUCT_POST_DATA_OTHER",
  SITE_PROMOTION_PRODUCT_POST_DATA_TITLE: "SITE_PROMOTION_PRODUCT_POST_DATA_TITLE",
  SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO: "SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO",
  SITE_PROMOTION_PRODUCT_PRODUCT: "SITE_PROMOTION_PRODUCT_PRODUCT",
} as const;

export type QianchuanReportUniPromotionDataGetV10DataTopic = typeof QianchuanReportUniPromotionDataGetV10DataTopic[keyof typeof QianchuanReportUniPromotionDataGetV10DataTopic];

