// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization = {

} as const;

export type QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization = typeof QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization[keyof typeof QianchuanAdDetailGetV10DataCreativeListPromotionCardMaterialButtonSmartOptimization];

