// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanAdGetV10DataListStatus = {
  ADVERTISER_OFFLINE_BUDGET: "ADVERTISER_OFFLINE_BUDGET",
  ADVERTISER_PRE_OFFLINE_BUDGET: "ADVERTISER_PRE_OFFLINE_BUDGET",
  AUDIT: "AUDIT",
  AUDIT_STATUS_ERROR: "AUDIT_STATUS_ERROR",
  AWEME_ACCOUNT_DISABLED: "AWEME_ACCOUNT_DISABLED",
  CAMPAIGN_DISABLE: "CAMPAIGN_DISABLE",
  CAMPAIGN_OFFLINE_BUDGET: "CAMPAIGN_OFFLINE_BUDGET",
  CAMPAIGN_PRE_OFFLINE_BUDGET: "CAMPAIGN_PRE_OFFLINE_BUDGET",
  CREATE: "CREATE",
  DELETE: "DELETE",
  DELIVERY_OK: "DELIVERY_OK",
  DISABLE: "DISABLE",
  DRAFT: "DRAFT",
  ERROR: "ERROR",
  EXTERNAL_URL_DISABLE: "EXTERNAL_URL_DISABLE",
  FROZEN: "FROZEN",
  LIVE_ROOM_OFF: "LIVE_ROOM_OFF",
  NO_SCHEDULE: "NO_SCHEDULE",
  OFFLINE_AUDIT: "OFFLINE_AUDIT",
  OFFLINE_BALANCE: "OFFLINE_BALANCE",
  OFFLINE_BUDGET: "OFFLINE_BUDGET",
  OFFLINE_SHARED_WALLET_BALANCE: "OFFLINE_SHARED_WALLET_BALANCE",
  PRE_OFFLINE_BUDGET: "PRE_OFFLINE_BUDGET",
  PRE_ONLINE: "PRE_ONLINE",
  QUOTA_DISABLE: "QUOTA_DISABLE",
  REAUDIT: "REAUDIT",
  ROI2_DISABLE: "ROI2_DISABLE",
  SYSTEM_DISABLE: "SYSTEM_DISABLE",
  TIME_DONE: "TIME_DONE",
  TIME_NO_REACH: "TIME_NO_REACH",
} as const;

export type QianchuanAdGetV10DataListStatus = typeof QianchuanAdGetV10DataListStatus[keyof typeof QianchuanAdGetV10DataListStatus];

