// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanReportCustomConfigGetV10DataTopics = {
  ECP_BASIC_DATA: "ECP_BASIC_DATA",
  SITE_PROMOTION_POST_DATA_LIVE: "SITE_PROMOTION_POST_DATA_LIVE",
  SITE_PROMOTION_POST_DATA_OTHER: "SITE_PROMOTION_POST_DATA_OTHER",
  SITE_PROMOTION_POST_DATA_TITLE: "SITE_PROMOTION_POST_DATA_TITLE",
  SITE_PROMOTION_POST_DATA_VIDEO: "SITE_PROMOTION_POST_DATA_VIDEO",
  SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE: "SITE_PROMOTION_PRODUCT_POST_DATA_IMAGE",
  SITE_PROMOTION_PRODUCT_POST_DATA_OTHER: "SITE_PROMOTION_PRODUCT_POST_DATA_OTHER",
  SITE_PROMOTION_PRODUCT_POST_DATA_TITLE: "SITE_PROMOTION_PRODUCT_POST_DATA_TITLE",
  SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO: "SITE_PROMOTION_PRODUCT_POST_DATA_VIDEO",
} as const;

export type QianchuanReportCustomConfigGetV10DataTopics = typeof QianchuanReportCustomConfigGetV10DataTopics[keyof typeof QianchuanReportCustomConfigGetV10DataTopics];

