// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic = {
  Enum_1: 1,
} as const;

export type QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic = typeof QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic[keyof typeof QianchuanUniAwemeAdCreateV10ProgrammaticCreativeMediaListVideoMaterialStarTraffic];

