// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListBlockVideoMaterialInner, QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListTitleMaterialInner, QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListVideoMaterialInner } from "../models";

export interface QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaList {
  block_video_material?: QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListBlockVideoMaterialInner[];
  title_material?: QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListTitleMaterialInner[];
  video_material?: QianchuanUniPromotionAdDetailV10ResponseDataProgrammaticCreativeMediaListVideoMaterialInner[];
}

