// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const QianchuanAwemeSuggestBidV10DeliverySettingExternalAction = {
  AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION: "AD_CONVERT_TYPE_LIVE_CLICK_PRODUCT_ACTION",
  AD_CONVERT_TYPE_LIVE_HEAT: "AD_CONVERT_TYPE_LIVE_HEAT",
  AD_CONVERT_TYPE_LIVE_ROI: "AD_CONVERT_TYPE_LIVE_ROI",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_ACTION",
  AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY: "AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY",
  AD_CONVERT_TYPE_NEW_FOLLOW_ACTION: "AD_CONVERT_TYPE_NEW_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_FOLLOW_ACTION: "AD_CONVERT_TYPE_QC_FOLLOW_ACTION",
  AD_CONVERT_TYPE_QC_MUST_BUY: "AD_CONVERT_TYPE_QC_MUST_BUY",
  AD_CONVERT_TYPE_SHOPPING: "AD_CONVERT_TYPE_SHOPPING",
} as const;

export type QianchuanAwemeSuggestBidV10DeliverySettingExternalAction = typeof QianchuanAwemeSuggestBidV10DeliverySettingExternalAction[keyof typeof QianchuanAwemeSuggestBidV10DeliverySettingExternalAction];

