// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const ReportAgentGetV2V2DataListAccountStatus = {
  PENDING_CONFIRM: "STATUS_PENDING_CONFIRM",
  PUNISH: "STATUS_PUNISH",
  PENDING_VERIFIED: "STATUS_PENDING_VERIFIED",
  WAIT_FOR_BPM_FILE_CONTACT: "STATUS_WAIT_FOR_BPM_FILE_CONTACT",
  CONFIRM_FAIL_END: "STATUS_CONFIRM_FAIL_END",
  CONFIRM_FAIL: "STATUS_CONFIRM_FAIL",
  SELF_SERVICE_UNAUDITED: "STATUS_SELF_SERVICE_UNAUDITED",
  ENABLE: "STATUS_ENABLE",
  WAIT_FOR_ACCOUNT_FEE: "STATUS_WAIT_FOR_ACCOUNT_FEE",
  DISABLE: "STATUS_DISABLE",
  ENABLE_AND_AVATAR_AUDITING: "STATUS_ENABLE_AND_AVATAR_AUDITING",
  PENDING_CONFIRM_MODIFY: "STATUS_PENDING_CONFIRM_MODIFY",
  WAIT_FOR_PUBLIC_AUTH: "STATUS_WAIT_FOR_PUBLIC_AUTH",
  WAIT_FOR_BPM_AUDIT: "STATUS_WAIT_FOR_BPM_AUDIT",
  CONFIRM_MODIFY_FAIL: "STATUS_CONFIRM_MODIFY_FAIL",
} as const;

export type ReportAgentGetV2V2DataListAccountStatus = typeof ReportAgentGetV2V2DataListAccountStatus[keyof typeof ReportAgentGetV2V2DataListAccountStatus];

