// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const ReportCreativeGetV2FilteringStatus = {
  ALL: "CREATIVE_STATUS_ALL",
  DELIVERY_OK: "CREATIVE_STATUS_DELIVERY_OK",
  AD_DISABLE: "CREATIVE_STATUS_AD_DISABLE",
  BALANCE_EXCEED: "CREATIVE_STATUS_BALANCE_EXCEED",
  AUDIT_DENY: "CREATIVE_STATUS_AUDIT_DENY",
  AD_AUDIT: "CREATIVE_STATUS_AD_AUDIT",
  AD_REAUDIT: "CREATIVE_STATUS_AD_REAUDIT",
  NO_SCHEDULE: "CREATIVE_STATUS_NO_SCHEDULE",
  AUDIT: "CREATIVE_STATUS_AUDIT",
  CAMPAIGN_EXCEED: "CREATIVE_STATUS_CAMPAIGN_EXCEED",
  REAUDIT: "CREATIVE_STATUS_REAUDIT",
  DONE: "CREATIVE_STATUS_DONE",
  AD_AUDIT_DENY: "CREATIVE_STATUS_AD_AUDIT_DENY",
  DISABLE: "CREATIVE_STATUS_DISABLE",
  NOT_START: "CREATIVE_STATUS_NOT_START",
  CAMPAIGN_DISABLE: "CREATIVE_STATUS_CAMPAIGN_DISABLE",
  NOT_DELETE: "CREATIVE_STATUS_NOT_DELETE",
  BUDGET_EXCEED: "CREATIVE_STATUS_BUDGET_EXCEED",
  DELETE: "CREATIVE_STATUS_DELETE",
} as const;

export type ReportCreativeGetV2FilteringStatus = typeof ReportCreativeGetV2FilteringStatus[keyof typeof ReportCreativeGetV2FilteringStatus];

