// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { ReportAgentGetV2V2DataListAccountSource, ReportAgentGetV2V2DataListAccountStatus, ReportAgentGetV2V2DataListCustomerType } from "../models";

export interface ReportAgentGetV2V2ResponseDataListInner {
  account_source?: ReportAgentGetV2V2DataListAccountSource;
  account_status?: ReportAgentGetV2V2DataListAccountStatus;
  advertiser_id?: number;
  advertiser_name?: string;
  agent_id?: number;
  agent_name?: string;
  arpu_3cd?: number;
  audit_pass_time?: string;
  bid_cost?: number;
  brand_cost?: number;
  cash_balance?: number;
  cash_cost?: number;
  click?: number;
  company_id?: number;
  company_name?: string;
  cost?: number;
  cpa_cost?: number;
  cpc?: number;
  cpc_cost?: number;
  cpm?: number;
  cpm_cost?: number;
  cpt_cost?: number;
  cpv_cost?: number;
  ctr?: number;
  customer_type?: ReportAgentGetV2V2DataListCustomerType;
  first_cost_time?: string;
  first_industry?: string;
  first_recharge_amount?: number;
  first_recharge_time?: string;
  gd_cost?: number;
  grant_balance?: number;
  grants_cost?: number;
  history_cash_cost?: number;
  history_cost?: number;
  last_recharge_time?: string;
  last_renew_amount?: number;
  last_renew_time?: string;
  ocpc_cost?: number;
  ocpm_cost?: number;
  query_end_time?: number;
  register_days?: number;
  register_time?: string;
  second_industry?: string;
  show?: number;
  today_cost?: number;
  today_x_hour_click?: number;
  today_x_hour_convert?: number;
  today_x_hour_cost?: number;
  today_x_hour_cpa?: number;
  today_x_hour_cpc?: number;
  total_balance?: number;
  total_renew_amount?: number;
  total_renew_number?: number;
  transfer_amount?: number;
  transfer_count?: number;
  valid_balance?: number;
  x_hour_click_diff?: number;
  x_hour_convert_diff?: number;
  x_hour_cost_diff?: number;
  x_hour_cpa_diff?: number;
  x_hour_cpc_diff?: number;
  yesterday_ad_number?: number;
  yesterday_bid_cash_cost?: number;
  yesterday_brand_cash_cost?: number;
  yesterday_cash_cost?: number;
  yesterday_cost?: number;
  yesterday_cost_diff?: number;
  yesterday_grants_cost?: number;
  yesterday_mom_cost?: number;
  yesterday_x_hour_click?: number;
  yesterday_x_hour_convert?: number;
  yesterday_x_hour_cost?: number;
  yesterday_x_hour_cpa?: number;
  yesterday_x_hour_cpc?: number;
}

