// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const ReportAdvertiserGetV2GroupBy = {
  STAT_GROUP_BY_AGE: "STAT_GROUP_BY_AGE",
  STAT_GROUP_BY_MATERIAL_ID: "STAT_GROUP_BY_MATERIAL_ID",
  STAT_GROUP_BY_LANDING_TYPE: "STAT_GROUP_BY_LANDING_TYPE",
  STAT_GROUP_BY_CITY_NAME: "STAT_GROUP_BY_CITY_NAME",
  STAT_GROUP_BY_GENDER: "STAT_GROUP_BY_GENDER",
  STAT_GROUP_BY_FIELD_ID: "STAT_GROUP_BY_FIELD_ID",
  STAT_GROUP_BY_AC: "STAT_GROUP_BY_AC",
  STAT_GROUP_BY_CREATIVE_COMPONENT_ID: "STAT_GROUP_BY_CREATIVE_COMPONENT_ID",
  STAT_GROUP_BY_IMAGE_MODE: "STAT_GROUP_BY_IMAGE_MODE",
  STAT_GROUP_BY_PROVINCE_NAME: "STAT_GROUP_BY_PROVINCE_NAME",
  STAT_GROUP_BY_FIELD_STAT_TIME: "STAT_GROUP_BY_FIELD_STAT_TIME",
  STAT_GROUP_BY_EXTERNAL_ACTION: "STAT_GROUP_BY_EXTERNAL_ACTION",
  STAT_GROUP_BY_INVENTORY: "STAT_GROUP_BY_INVENTORY",
  STAT_GROUP_BY_CAMPAIGN_TYPE: "STAT_GROUP_BY_CAMPAIGN_TYPE",
  STAT_GROUP_BY_PRICING_CATEGORY: "STAT_GROUP_BY_PRICING_CATEGORY",
  STAT_GROUP_BY_PRICING: "STAT_GROUP_BY_PRICING",
  STAT_GROUP_BY_CREATIVE_MATERIAL_MODE: "STAT_GROUP_BY_CREATIVE_MATERIAL_MODE",
  STAT_GROUP_BY_PLATFORM: "STAT_GROUP_BY_PLATFORM",
} as const;

export type ReportAdvertiserGetV2GroupBy = typeof ReportAdvertiserGetV2GroupBy[keyof typeof ReportAdvertiserGetV2GroupBy];

