// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInnerAuthorBaseInfo, StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInnerAuthorInvitaionInfo, StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInnerAuthorOrderInfo } from "../models";

export interface StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInner {
  author_base_info: StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInnerAuthorBaseInfo;
  author_invitaion_info?: StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInnerAuthorInvitaionInfo;
  author_order_info: StarMcnProviderGetTaskAuthorListV2ResponseDataAuthorListInnerAuthorOrderInfo;
}

