// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const StarDemandListV2DataListComponentType = {
  ALL: "ALL",
  ANCHOR_CAR: "ANCHOR_CAR",
  ANCHOR_DOWNLOAD: "ANCHOR_DOWNLOAD",
  ANCHOR_ECOM: "ANCHOR_ECOM",
  ANCHOR_EDUCATION: "ANCHOR_EDUCATION",
  ANCHOR_ESTATE_SERVICE: "ANCHOR_ESTATE_SERVICE",
  ANCHOR_E_GAME: "ANCHOR_E_GAME",
  ANCHOR_HOME: "ANCHOR_HOME",
  ANCHOR_INSURANCE: "ANCHOR_INSURANCE",
  ANCHOR_INVESTMENT: "ANCHOR_INVESTMENT",
  ANCHOR_MICRO_APP_POI: "ANCHOR_MICRO_APP_POI",
  ANCHOR_MOVIE: "ANCHOR_MOVIE",
  ANCHOR_TELECOM: "ANCHOR_TELECOM",
  ANCHOR_TOURISM: "ANCHOR_TOURISM",
  ANCHOR_XIGUA: "ANCHOR_XIGUA",
  BRAND_ANCHOR: "BRAND_ANCHOR",
  CART: "CART",
  ENTERPRISE_CAR: "ENTERPRISE_CAR",
  ENTERPRISE_COUPON: "ENTERPRISE_COUPON",
  ENTERPRISE_DOWNLOAD: "ENTERPRISE_DOWNLOAD",
  ENTERPRISE_DOWNLOAD_APP: "ENTERPRISE_DOWNLOAD_APP",
  ENTERPRISE_ECOM: "ENTERPRISE_ECOM",
  ENTERPRISE_MICRO_APP: "ENTERPRISE_MICRO_APP",
  ENTERPRISE_NOVEL: "ENTERPRISE_NOVEL",
  ENTERPRISE_ORDER_SERVICE: "ENTERPRISE_ORDER_SERVICE",
  ENTERPRISE_SALON: "ENTERPRISE_SALON",
  ENTERPRISE_WEDDING_PHOTO: "ENTERPRISE_WEDDING_PHOTO",
  GAME_ANCHOR: "GAME_ANCHOR",
  LINK: "LINK",
  LIVE_ORDER_COMPONENT: "LIVE_ORDER_COMPONENT",
  MICROAPP_ANCHOR: "MICROAPP_ANCHOR",
  POI: "POI",
  VARIETY_ANCHOR: "VARIETY_ANCHOR",
} as const;

export type StarDemandListV2DataListComponentType = typeof StarDemandListV2DataListComponentType[keyof typeof StarDemandListV2DataListComponentType];

