// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeAdConvertData, StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeEffectData, StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeNaturalConvertData } from "../models";

export interface StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoData {
  real_time_ad_convert_data?: StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeAdConvertData;
  real_time_effect_data?: StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeEffectData;
  real_time_natural_convert_data?: StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemInfoDataRealTimeNaturalConvertData;
}

