// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { ToolsSiteTemplateGetV2ResponseDataListInnerBricksInnerButtonDownloadEventAndroidLink, ToolsSiteTemplateGetV2ResponseDataListInnerBricksInnerButtonDownloadEventIosLink } from "../models";

export interface ToolsSiteTemplateGetV2ResponseDataListInnerBricksInnerButtonDownloadEvent {
  android_link?: ToolsSiteTemplateGetV2ResponseDataListInnerBricksInnerButtonDownloadEventAndroidLink;
  ios_link?: ToolsSiteTemplateGetV2ResponseDataListInnerBricksInnerButtonDownloadEventIosLink;
}

