// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType = {
  OPTIMIZE_COST_EFFECT_UP_COST: "OPTIMIZE_COST_EFFECT_UP_COST",
  OPTIMIZE_COST_EFFECT_UP_ROI: "OPTIMIZE_COST_EFFECT_UP_ROI",
  OPTIMIZE_COST_EFFECT_UP_ROI_STABLE_COST: "OPTIMIZE_COST_EFFECT_UP_ROI_STABLE_COST",
  OPTIMIZE_COST_EFFECT_DOWN_COST: "OPTIMIZE_COST_EFFECT_DOWN_COST",
} as const;

export type ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType = typeof ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType[keyof typeof ToolsAdvertiserDiagnosisSuggestionGetV30DataSuggestionInfoListSevenDaysRoiSuggestionPackageSuggestionAdjustInfoDeliveryOptimizationType];

