// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

import type { ToolsBpAssetManagementShareGetV30DataSharedAccountsAllAccountsByBp, ToolsBpAssetManagementShareGetV30DataSharedAccountsShareMode, ToolsBpAssetManagementShareGetV30ResponseDataSharedAccountsInnerAccountInfo, ToolsBpAssetManagementShareGetV30ResponseDataSharedAccountsInnerAllAccountsByCompany } from "../models";

export interface ToolsBpAssetManagementShareGetV30ResponseDataSharedAccountsInner {
  account_info?: ToolsBpAssetManagementShareGetV30ResponseDataSharedAccountsInnerAccountInfo;
  all_accounts_by_bp?: ToolsBpAssetManagementShareGetV30DataSharedAccountsAllAccountsByBp;
  all_accounts_by_company?: ToolsBpAssetManagementShareGetV30ResponseDataSharedAccountsInnerAllAccountsByCompany;
  share_mode: ToolsBpAssetManagementShareGetV30DataSharedAccountsShareMode;
}

