// Generated from oceanengine/ad_open_sdk_java
// Phase: B
// Do not edit manually.

export const ToolsBidsSuggestV30DeepBidType = {
  ALI_FL: "ALI_FL",
  AUTO_MIN_SECOND_STAGE: "AUTO_MIN_SECOND_STAGE",
  BID_PER_ACTION: "BID_PER_ACTION",
  DEEP_BID_DEFAULT: "DEEP_BID_DEFAULT",
  DEEP_BID_MIN: "DEEP_BID_MIN",
  DEEP_BID_PACING: "DEEP_BID_PACING",
  DEEP_BID_TYPE_RETENTION_DAYS: "DEEP_BID_TYPE_RETENTION_DAYS",
  FORM_BID: "FORM_BID",
  MIN_SECOND_STAGE: "MIN_SECOND_STAGE",
  PACING_SECOND_STAGE: "PACING_SECOND_STAGE",
  PER_AND_SEVEN_PAY_ROI: "PER_AND_SEVEN_PAY_ROI",
  PHONE_CONNECT_BID: "PHONE_CONNECT_BID",
  ROI_COEFFICIENT: "ROI_COEFFICIENT",
  ROI_DIRECT_MAIL: "ROI_DIRECT_MAIL",
  ROI_PACING: "ROI_PACING",
  SMARTBID: "SMARTBID",
  SOCIAL_ROI: "SOCIAL_ROI",
} as const;

export type ToolsBidsSuggestV30DeepBidType = typeof ToolsBidsSuggestV30DeepBidType[keyof typeof ToolsBidsSuggestV30DeepBidType];

