// Generated from oceanengine/ad_open_sdk_go
// Do not edit manually.

export const UniProjectListGetV30FilteringStatusSecond = {
  PROJECT_STATUS_AUDIT: "PROJECT_STATUS_AUDIT",
  PROJECT_STATUS_AWEME_ACCOUNT_DISABLED: "PROJECT_STATUS_AWEME_ACCOUNT_DISABLED",
  PROJECT_STATUS_BUDGET_EXCEED: "PROJECT_STATUS_BUDGET_EXCEED",
  PROJECT_STATUS_NOT_START: "PROJECT_STATUS_NOT_START",
  PROJECT_STATUS_NO_SCHEDULE: "PROJECT_STATUS_NO_SCHEDULE",
  PROJECT_STATUS_OFFLINE_AUDIT: "PROJECT_STATUS_OFFLINE_AUDIT",
  PROJECT_STATUS_PRODUCT_OFFLINE: "PROJECT_STATUS_PRODUCT_OFFLINE",
  PROJECT_STATUS_REAUDIT: "PROJECT_STATUS_REAUDIT",
  PROJECT_STATUS_STOP: "PROJECT_STATUS_STOP",
} as const;

export type UniProjectListGetV30FilteringStatusSecond = typeof UniProjectListGetV30FilteringStatusSecond[keyof typeof UniProjectListGetV30FilteringStatusSecond];

