// Generated from tencentad/marketing-api-go-sdk pkg/model/model_campaign_type.go
// Do not edit manually.

export const CampaignType = {
  SEARCH: "CAMPAIGN_TYPE_SEARCH",
  NORMAL: "CAMPAIGN_TYPE_NORMAL",
  CONTRACT: "CAMPAIGN_TYPE_CONTRACT",
  WECHAT_OFFICIAL_ACCOUNTS: "CAMPAIGN_TYPE_WECHAT_OFFICIAL_ACCOUNTS",
  WECHAT_MOMENTS: "CAMPAIGN_TYPE_WECHAT_MOMENTS",
  UNSUPPORTED: "CAMPAIGN_TYPE_UNSUPPORTED",
  REWARDQUEST: "CAMPAIGN_TYPE_REWARDQUEST",
  OVERSEAS: "CAMPAIGN_TYPE_OVERSEAS",
  FREETRADE: "CAMPAIGN_TYPE_FREETRADE",
  CONTENT_PROMOTION: "CAMPAIGN_TYPE_CONTENT_PROMOTION",
} as const;

export type CampaignType = typeof CampaignType[keyof typeof CampaignType];

