// Generated from tencentad/marketing-api-go-sdk pkg/model/model_playable_type.go
// Do not edit manually.

export const PlayableType = {
  PLAYABLE_TYPE_DEFAULT: "PLAYABLE_TYPE_DEFAULT",
  PLAYABLE_TYPE_HOMEMADE_INTERACTION: "PLAYABLE_TYPE_HOMEMADE_INTERACTION",
  PLAYABLE_TYPE_MINIGAME_INTERACTION: "PLAYABLE_TYPE_MINIGAME_INTERACTION",
  PLAYABLE_TYPE_VIDEO_INTERACTION: "PLAYABLE_TYPE_VIDEO_INTERACTION",
  PLAYABLE_TYPE_WEBSITE_INTERACTION: "PLAYABLE_TYPE_WEBSITE_INTERACTION",
  PLAYABLE_TYPE_ZIP_INTERACTION: "PLAYABLE_TYPE_ZIP_INTERACTION",
  PLAYABLE_TYPE_COMPONENT_INTERACTION: "PLAYABLE_TYPE_COMPONENT_INTERACTION",
  NOT_INTERACT: "NOT_INTERACT",
  INLINE: "INLINE",
  TEMPLATE_GAME: "TEMPLATE_GAME",
  TEMPLATE_VIDEO: "TEMPLATE_VIDEO",
  TEMPLATE_WEB: "TEMPLATE_WEB",
  COMPRESSED_PACKAGE: "COMPRESSED_PACKAGE",
} as const;

export type PlayableType = typeof PlayableType[keyof typeof PlayableType];

