// Generated from tencentad/marketing-api-go-sdk pkg/model/model_excluded_dimension.go
// Do not edit manually.

export const ExcludedDimension = {
  EXCLUDED_DIMENSION_CAMPAIGN: "EXCLUDED_DIMENSION_CAMPAIGN",
  EXCLUDED_DIMENSION_UID: "EXCLUDED_DIMENSION_UID",
  EXCLUDED_DIMENSION_BUSINESS_MANAGER: "EXCLUDED_DIMENSION_BUSINESS_MANAGER",
  EXCLUDED_DIMENSION_COMPANY_ACCOUNT: "EXCLUDED_DIMENSION_COMPANY_ACCOUNT",
  EXCLUDED_DIMENSION_APP: "EXCLUDED_DIMENSION_APP",
  EXCLUDED_DIMENSION_PRODUCT: "EXCLUDED_DIMENSION_PRODUCT",
  EXCLUDE_DIMENSION_WORKTABLE: "EXCLUDE_DIMENSION_WORKTABLE",
} as const;

export type ExcludedDimension = typeof ExcludedDimension[keyof typeof ExcludedDimension];

