// Generated from tencentad/marketing-api-go-sdk pkg/model/model_element_type.go
// Do not edit manually.

export const ElementType = {
  ELEMENT_TYPE_TEXT: "ELEMENT_TYPE_TEXT",
  ELEMENT_TYPE_IMAGE: "ELEMENT_TYPE_IMAGE",
  ELEMENT_TYPE_VIDEO: "ELEMENT_TYPE_VIDEO",
  ELEMENT_TYPE_URL: "ELEMENT_TYPE_URL",
  ELEMENT_TYPE_ENUM: "ELEMENT_TYPE_ENUM",
  ELEMENT_TYPE_CANVAS: "ELEMENT_TYPE_CANVAS",
  ELEMENT_TYPE_STRUCT: "ELEMENT_TYPE_STRUCT",
  ELEMENT_TYPE_REFERENCE: "ELEMENT_TYPE_REFERENCE",
  ELEMENT_TYPE_BOOLEAN: "ELEMENT_TYPE_BOOLEAN",
  ELEMENT_TYPE_PHONE: "ELEMENT_TYPE_PHONE",
  ELEMENT_TYPE_FORM: "ELEMENT_TYPE_FORM",
  ELEMENT_TYPE_CONSULT: "ELEMENT_TYPE_CONSULT",
  ELEMENT_TYPE_NUMBER: "ELEMENT_TYPE_NUMBER",
  ELEMENT_TYPE_LANDING_PAGE_STRUCT: "ELEMENT_TYPE_LANDING_PAGE_STRUCT",
  STRUCT: "STRUCT",
  TEXT: "TEXT",
  URL: "URL",
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  BIRTHDAY_ACTIVITY_PAGE_CARD: "BIRTHDAY_ACTIVITY_PAGE_CARD",
  FESTIVAL_ACTIVITY_PAGE_CARD: "FESTIVAL_ACTIVITY_PAGE_CARD",
  ID: "ID",
  PHONE_BY_USER_INPUT: "PHONE_BY_USER_INPUT",
  DYNAMIC_CREATIVE: "DYNAMIC_CREATIVE",
  DEEP_LINK_TYPE: "DEEP_LINK_TYPE",
  CANVAS: "CANVAS",
  ANIMATION_EFFECT: "ANIMATION_EFFECT",
  LABEL: "LABEL",
  LANDING_PAGE_STRUCT: "LANDING_PAGE_STRUCT",
  COMPONENT: "COMPONENT",
} as const;

export type ElementType = typeof ElementType[keyof typeof ElementType];

