// Generated from tencentad/marketing-api-go-sdk pkg/model/model_task_scope.go
// Do not edit manually.

export const TaskScope = {
  UNKNOWN: "TASK_SCOPE_UNKNOWN",
  CAMPAIGN: "TASK_SCOPE_CAMPAIGN",
  ADGROUP: "TASK_SCOPE_ADGROUP",
  ADVERTISER: "TASK_SCOPE_ADVERTISER",
  SCHEDULED_TASK: "TASK_SCOPE_SCHEDULED_TASK",
  AD: "TASK_SCOPE_AD",
  ADCREATIVE: "TASK_SCOPE_ADCREATIVE",
  PROJECT: "TASK_SCOPE_PROJECT",
  BIDWORD: "TASK_SCOPE_BIDWORD",
  COMMENT: "TASK_SCOPE_COMMENT",
  DYNAMIC_CREATIVE: "TASK_SCOPE_DYNAMIC_CREATIVE",
  ADEXPORT: "TASK_SCOPE_ADEXPORT",
  COMPONENT: "TASK_SCOPE_COMPONENT",
  IMAGE: "TASK_SCOPE_IMAGE",
  VIDEO: "TASK_SCOPE_VIDEO",
} as const;

export type TaskScope = typeof TaskScope[keyof typeof TaskScope];

