// Generated from tencentad/marketing-api-go-sdk pkg/model/model_role_type.go
// Do not edit manually.

export const RoleType = {
  UNKNOWN: "ROLE_TYPE_UNKNOWN",
  ADMIN: "ROLE_TYPE_ADMIN",
  OBSERVER: "ROLE_TYPE_OBSERVER",
  OPERATOR: "ROLE_TYPE_OPERATOR",
  TREASURER: "ROLE_TYPE_TREASURER",
  ASSISTANT: "ROLE_TYPE_ASSISTANT",
  SELF_OPERATOR: "ROLE_TYPE_SELF_OPERATOR",
  ROOT: "ROLE_TYPE_ROOT",
  AGENCY_BOSS: "ROLE_TYPE_AGENCY_BOSS",
  AGENCY_ADMIN: "ROLE_TYPE_AGENCY_ADMIN",
  AGENCY_OBSERVER: "ROLE_TYPE_AGENCY_OBSERVER",
  AGENCY_TREASURER: "ROLE_TYPE_AGENCY_TREASURER",
  AGENCY_OPERATOR: "ROLE_TYPE_AGENCY_OPERATOR",
  AGENCY_PROVIDER_OPERATOR: "ROLE_TYPE_AGENCY_PROVIDER_OPERATOR",
  AGENCY_PROVIDER_OBSERVER: "ROLE_TYPE_AGENCY_PROVIDER_OBSERVER",
  AGENCY_YYB: "ROLE_TYPE_AGENCY_YYB",
  AGENCY_AGENT_OPERATOR: "ROLE_TYPE_AGENCY_AGENT_OPERATOR",
  AGENCY_SELF_OPERATOR: "ROLE_TYPE_AGENCY_SELF_OPERATOR",
  AGENCY_MDM_BOSS: "ROLE_TYPE_AGENCY_MDM_BOSS",
  AGENCY_MDM_ADMIN: "ROLE_TYPE_AGENCY_MDM_ADMIN",
  AGENCY_MDM_TREASURER: "ROLE_TYPE_AGENCY_MDM_TREASURER",
  AGENCY_MDM_OBSERVER: "ROLE_TYPE_AGENCY_MDM_OBSERVER",
  AGENCY_MDM_OPERATOR: "ROLE_TYPE_AGENCY_MDM_OPERATOR",
  AGENCY_ORBAC: "ROLE_TYPE_AGENCY_ORBAC",
  AGENCY_DESIGNER: "ROLE_TYPE_AGENCY_DESIGNER",
  SUB_AGENCY_ADMIN: "ROLE_TYPE_SUB_AGENCY_ADMIN",
} as const;

export type RoleType = typeof RoleType[keyof typeof RoleType];

