// Generated from tencentad/marketing-api-go-sdk pkg/model/model_async_report_level.go
// Do not edit manually.

export const AsyncReportLevel = {
  ADGROUP_WECHAT: "REPORT_LEVEL_ADGROUP_WECHAT",
  AD_WECHAT: "REPORT_LEVEL_AD_WECHAT",
  POI_WECHAT: "REPORT_LEVEL_POI_WECHAT",
  AD: "REPORT_LEVEL_AD",
  ADVERTISER: "REPORT_LEVEL_ADVERTISER",
  CAMPAIGN: "REPORT_LEVEL_CAMPAIGN",
  ADGROUP: "REPORT_LEVEL_ADGROUP",
  MATERIAL_VIDEO: "REPORT_LEVEL_MATERIAL_VIDEO",
  MATERIAL_IMAGE: "REPORT_LEVEL_MATERIAL_IMAGE",
  PROMOTED_OBJECT: "REPORT_LEVEL_PROMOTED_OBJECT",
  CREATIVE_TEMPLATE: "REPORT_LEVEL_CREATIVE_TEMPLATE",
  PRODUCT_CATELOG: "REPORT_LEVEL_PRODUCT_CATELOG",
  AGE: "REPORT_LEVEL_AGE",
  GENDER: "REPORT_LEVEL_GENDER",
  REGION_RECENTLY_IN: "REPORT_LEVEL_REGION_RECENTLY_IN",
  REGION_VISITED_IN: "REPORT_LEVEL_REGION_VISITED_IN",
  REGION_LIVE_IN: "REPORT_LEVEL_REGION_LIVE_IN",
  REGION_TRAVEL_IN: "REPORT_LEVEL_REGION_TRAVEL_IN",
  CITY_RECENTLY_IN: "REPORT_LEVEL_CITY_RECENTLY_IN",
  CITY_VISITED_IN: "REPORT_LEVEL_CITY_VISITED_IN",
  CITY_LIVE_IN: "REPORT_LEVEL_CITY_LIVE_IN",
  CITY_TRAVEL_IN: "REPORT_LEVEL_CITY_TRAVEL_IN",
  BIDWORD: "REPORT_LEVEL_BIDWORD",
  QUERYWORD: "REPORT_LEVEL_QUERYWORD",
} as const;

export type AsyncReportLevel = typeof AsyncReportLevel[keyof typeof AsyncReportLevel];

